### ISSUE TITLE
Full plot functionality

### ISSUE THREAD

**Issue by bnaul** [skyportal/skyportal#10]
- Photometry
    - [x] Arrows for limmag
    - [x] Toggle bands/instruments
    - [ ] Export (as CSV?)
    - [ ] Support all filters / handle unknown filter values
- Spectroscopy
    - [x] Toggle instruments
    - [x] Vertical line overlay
    - [ ] Binning
    - [ ] Export (as `tar.gz`?)
    - [ ] Handle missing spectra

**Comment by stefanv** [comment]
- [ ] Scaling plots for mobile

**Comment by stefanv** [comment]
See also #96

**Comment by dannygoldstein** [comment]
It would also be really nice if, on the photometry plot, tooltips showed the ref, new, sub triplets of each light curve point
