### ISSUE TITLE
Cache common source queries using materialized views

### ISSUE THREAD

**Issue by stefanv** [skyportal/skyportal#101]
- [ ] Determine which queries are expensive, and should be cached
- [ ] Create materialized views for these, either in the app startup script, or using Alembic
- [ ] Add logic to the app to refresh materialized views when necessary.  This would require storing some meta-data on the views, such as the view name, last refresh date, and validity period.  Views can either be updated when the query is made, or a background task can continually monitor and refresh materialized views, so that access is almost instantaneous from the user perspective.
- [ ] TODO: Figure out how we would handle the user/group permissions, i.e. would we do an overall query, and a sub query that restricts to the user/group, or will we do views for each user/group, etc.

See also:

- https://www.compose.com/articles/store-result-sets-with-materialized-views-in-postgresql/

**Comment by acrellin** [comment]
Is this still something we anticipate neding @stefanv @profjsb ?

**Comment by stefanv** [comment]
I think we can come back to this later *if necessary*.  I suspect the database is going to hold up fine without it.

When last we played around with this, it was quite hard to do this in a clean way with SQLAlchemy, so I strongly suggest we punt on it for now.
