### ISSUE TITLE
use nearest offset from PS1 in offset plot

### ISSUE THREAD

**Issue by dannygoldstein** [skyportal/skyportal#1011]
From Jesper S:

The Centroid plot at the bottom right always says 0.00, even if there is a clear offset in this case https://private.caltech.edu/source/ZTF20acfefsa

**Comment by sjoertvv** [comment]
@profjsb I'm happy to help with this. A first step, which is easier than using PS1 data, is to report the offset with respect to the reference image centroid coordinates (`ranr`, `decnr`).

**Comment by dannygoldstein** [comment]
@sjoertvv any updates here?

**Comment by sjoertvv** [comment]
@dannygoldstein sorry no, I didn't investigate because on Slack I was told this would requires changes on Kowalski, which is not something I have experience with.

**Comment by dmitryduev** [comment]
Closing in favor of https://github.com/fritz-marshal/fritz/issues/172.
