### ISSUE TITLE
Implement redshift entry in the style of the classifications widget

### ISSUE THREAD

**Issue by dannygoldstein** [skyportal/skyportal#1012]
From Jesper:

Good if redshift is put in not as free text? To make sure it is always understood as z?

**Comment by acrellin** [comment]
I do not understand the issue description. Please clarify.

**Comment by dannygoldstein** [comment]
@acrellin, currently we have a custom parser on the backend that looks for `z={float}` and uses this to set the redshift. It would be better to have a custom frontend component for entering redshifts, similar to what was done for classifications, where you can basically type in a redshift to a text field and it will be pushed to a custom backend handler. This would also allow users to enter multiple redshifts and to log the history what redshifts where entered when, where did they come from, and who entered them
