### ISSUE TITLE
Username slugs: ensure PSA is configured

### ISSUE THREAD

**Issue by stefanv** [skyportal/skyportal#1029]
[`SOCIAL_AUTH_CLEAN_USERNAME_FUNCTION`](https://python-social-auth.readthedocs.io/en/latest/configuration/settings.html) should be set to use the same slugifier as the rest of the app.

Check in `skyportal/onboarding.py` and `skyportal/handlers/api/user.py` whether slugify use is necessary.

**Comment by acrellin** [comment]
Closing as per our discussion
