### ISSUE TITLE
Requesting / tracking follow-up

### ISSUE THREAD

**Issue by dannygoldstein** [skyportal/skyportal#105]
It would be super useful if skyportal had facilities for tracking and requesting follow-up observations of an object with other telescopes. ZTF has some robotic follow-up resources (SED Machine on the Palomar 60 inch being the workhorse http://www.astro.caltech.edu/sedm/) but we also have runs on other telescopes (Keck, Palomar 200 inch, etc.). 

What we have on the GROWTH marshal, that would be great to replicate, is the ability to request photometry or spectroscopy using the robotic telescopes (I think SEDM has an API for this) and the ability to 'add' targets to upcoming runs. Then they are sorted in order of when they will be visible in the sky throughout the night to make it easy for the observers to figure out what to observe while they are on the run. 

I just wanted to get the conversation going about adding these useful features to skyportal.

**Comment by profjsb** [comment]
It would be good to get some ideas of specific (MVP-level) workflows that you're trying see here. Writing them as user stories would be most useful. For example,

 - as a logged in user, apart of some group A
     - I want to be able to flag certain sources, along with priorities
     - so that those sources can be identified in priority list (and sky position) for followup
 ...

etc.

**Comment by dannygoldstein** [comment]
OK here is my first attempt:

As a logged in user, part of some group A
* I want to be able to add an observing run (basically just a calendar night + telescope) to the database and make the run visible to my group and certain other groups
* I want to be able to add a source to the run, along with priorities, so that those sources can be identified in priority list (and sky position) for follow-up

**Comment by dannygoldstein** [comment]
Finally, I want to be able to view the run, showing the list of sources to be observed, their light curves and spectra, and their airmass and altitude as a function of time of night

**Comment by acrellin** [comment]
Closing this as we now have the followup request form and Danny's soon-to-be-merged assignments PR
