### ISSUE TITLE
Scanning / "Saving" sources

### ISSUE THREAD

**Issue by dannygoldstein** [skyportal/skyportal#107]
Just because an object passes a filter doesn't mean that it is actually interesting. The final call of whether something is truly interesting is made by humans, looking at a heavily filtered set of detections. We only request follow-up for objects that have been "scanned" by humans to avoid sending bad targets to other telescopes for follow-up. It would be great if there were some way of "saving" an object to a particular science program or group in skyportal so that we can easily show which targets are interesting.

**Comment by dannygoldstein** [comment]
As a logged in user, associated with some science program with filter A, I want to be able to:

* "Save" specific sources that pass my filter
* Have all unsaved sources be automatically deleted from the database after some period of time

**Comment by nugent68** [comment]
Hi all, second this. I am looking to flag objects of *high* interest vs. some more casual variables. It would be great if we had the ability to add a comment, or have a button, which says:

scanned: Priority high, medium, low

**Comment by acrellin** [comment]
Implemented in scanning page
