### ISSUE TITLE
Group Sources Page - Lightcurve plot improvements

### ISSUE THREAD

**Issue by shreyasahasram08** [skyportal/skyportal#1072]
In the group sources page, the lightcurve plots are displayed in MJD. This is inconvenient when scanning the sources page quickly to figure out the age of the transients saved. Changing x-axis to 'Days Ago (days)' would mirror the format of the skipper marshal and make the lightcurve much easier to interpret. Hopefully it's an easy fix. 

Not absolutely necessary, but useful: it would be great to have absolute magnitude of the transient on the opposite y-axis to apparent magnitude added once a transient gets a redshift, as this would allow us to judge the luminosity of a transient at a glance (useful for finding low-luminosity SN Ias within CLU, for example).

Thanks!

**Comment by dannygoldstein** [comment]
Addressed by #1087

**Comment by dannygoldstein** [comment]
First part of this issue is fixed, closing. Moving the second request to a new issue.
