### ISSUE TITLE
Persist error notifications in console log

### ISSUE THREAD

**Issue by stefanv** [skyportal/skyportal#1073]
Sometimes, users want to let us know what went wrong, but it is hard to do since the red notifications disappear.

Alternative: have red notifications stick around permanently until clicked.

**Comment by profjsb** [comment]
Could we have the alerts persist in (browser) LocalStorage so that they can been seen/scrolled in a notifications modal?

**Comment by profjsb** [comment]
![image](https://user-images.githubusercontent.com/480799/95483695-6b722180-0944-11eb-853f-6f70bf93d25d.jpeg)

**Comment by stefanv** [comment]
That's a great idea.

**Comment by dannygoldstein** [comment]
At the time of this writing, notifications are logged to the console on master. Closing.
