### ISSUE TITLE
Source API query contains tons of weather data

### ISSUE THREAD

**Issue by stefanv** [skyportal/skyportal#1076]
See http://localhost:5000/api/sources/16fil after `make load_demo_data`

There is so much weather data that it slows down the source query.

Could be that it comes in via the instrument linked to each photometry measurement.

**Comment by acrellin** [comment]
Adding to this issue: currently, for every comment returned with the source data, the author's entire user preferences JSON is shipped. This part can perhaps be fixed by going back to using construct_author_info_dict

**Comment by profjsb** [comment]
We currently only use "current" weather not the entire forecast. I can change the API call so that only the needed data is returned
