### ISSUE TITLE
In saving object by ID, record who saved it and when the object was saved

### ISSUE THREAD

**Issue by profjsb** [skyportal/skyportal#1083]
Request Steve Schulze

**Comment by acrellin** [comment]
This is already being done -- I suppose the question is then where to display this information. On the source page, we currently show a chip for each group a source is saved to; perhaps we could add who saved the source to that group and when as a tooltip for each group chip.

**Comment by kmshin1397** [comment]
I think the tooltip is a good idea. Maybe we can add a history icon button at the end of the group chips like you did with the redshift as well?

**Comment by Yashvi-Sharma** [comment]
Could you also add this information to API source query output?
