### ISSUE TITLE
funky postage stamp display

### ISSUE THREAD

**Issue by dannygoldstein** [skyportal/skyportal#109]
<img width="477" alt="screen shot 2018-12-06 at 11 06 12 pm" src="https://user-images.githubusercontent.com/2769632/49694687-645d0b00-fb43-11e8-811d-6935da523642.png">

The current layout of the postage stamps is a bit funky. I suggest the following changes:

* Replace SDSS with New
* Delete row three and move PS1 below ref

**Comment by dannygoldstein** [comment]
Seeing this now: 

<img width="896" alt="screen shot 2019-01-03 at 6 53 14 pm" src="https://user-images.githubusercontent.com/2769632/50671796-e4cb2c00-0f88-11e9-8697-c3fde37c29fc.png">

**Comment by dannygoldstein** [comment]
see #118

**Comment by stefanv** [comment]
This issue is Chrome-specific.
