### ISSUE TITLE
front page componets with links to sources should show new image instead of sdss/dr8

### ISSUE THREAD

**Issue by dannygoldstein** [skyportal/skyportal#1095]
Currently they appear to be showing SDSS
<img width="751" alt="Screen Shot 2020-10-14 at 10 26 35 AM" src="https://user-images.githubusercontent.com/2769632/96023765-c5bd2780-0e07-11eb-90e2-8f9edb13b5c0.png">

**Comment by dmitryduev** [comment]
This is a duplicate of #1059
