### ISSUE TITLE
use q3c

### ISSUE THREAD

**Issue by dannygoldstein** [skyportal/skyportal#110]
Source positions should be indexed with a quad tree cube for fast spatial cross-matching. 

q3c is the standard tool for this in psql.

https://github.com/segasai/q3c

Danny

**Comment by dannygoldstein** [comment]
fixed in my branch of skyportal

**Comment by stefanv** [comment]
See discussion on https://github.com/cesium-ml/baselayer/pull/59

**Comment by acrellin** [comment]
Danny's spatial backend PR covers this
