### ISSUE TITLE
Observing run starlist and offsets

### ISSUE THREAD

**Issue by yaoyuhan** [skyportal/skyportal#1110]
As a test, I assigned ZTF19acwrvzk to the Oct 30 NIRES run, and the first line of the starlist looks like this:

`ZTF..cwrvzk 04 35 23.27 +55 22 34.30 2000.0 #`

I wonder if we can show the whole name in the list:

`ZTF19acwrvzk 04 35 23.27 +55 22 34.30 2000.0 #`

It would be very useful to also generate a few standard star in the list by default. In the old Marshal, we have the following:

G191-B2B            05 05 30.60  +52 49 56.0  2000.0  ! Standard
Feige34             10 39 36.71  +43 06 10.1  2000.0  ! Standard
Feige67             12 41 51.83  +17 31 20.5  2000.0  ! Standard
Feige110            23 19 58.39  -05 09 55.8  2000.0  ! Standard
BD+28d4211          21 51 11.07  +28 51 51.8  2000.0  ! Standard
BD332642            15 51 59.89  +32 56 54.3  2000.0  ! Standard

Thanks,
Yuhan

**Comment by dannygoldstein** [comment]
Starlist name fixed in #1084

Standards forthcoming
