### ISSUE TITLE
profile photometry deduplication 

### ISSUE THREAD

**Issue by dannygoldstein** [skyportal/skyportal#1113]
https://github.com/skyportal/skyportal/pull/1111#pullrequestreview-512435390

From @dmitryduev : 

I did some performance checks using the demo alert data from Fritz (~300 alerts with alert photometry only + a few with the full alert history of several hundred points), so running the same ./kowalski.py test command every time, it's just the version of SP that is different. Here's a typical histogram of the results:

![image](https://user-images.githubusercontent.com/2769632/96631098-bd169680-12ca-11eb-9172-beabe180415c.png)

On the x axis -- the time it takes to PUT the photometry. Blue is the current implementation, orange -- this pr. The orange distribution is always shifted to the right, but the difference is not huge around the distribution maximum. What concerns me is the tail of the orange distribution. I am consistently seeing ~2x worse performance for longer light curves. We need to test this at scale (the py implementation vs pg) before it goes in.

[BTW as for the deduplication itself, both approaches work great/same lol]

**Comment by dannygoldstein** [comment]
Blue = #1071 
Orange = #1111

**Comment by dannygoldstein** [comment]
@dmitryduev Hopefully 33cb1c2 provides some improvement here

**Comment by dmitryduev** [comment]
We've been pretty happy with the deduplication performance, so closing for now.
