### ISSUE TITLE
photometry not loading for imported source

### ISSUE THREAD

**Issue by sjoertvv** [skyportal/skyportal#1121]
I've manually added a source to a few programs, but the ZTF photometry is not loading: 

https://private.caltech.edu/source/ZTF20abjwvae

On the Growth Marshal, the latest photometry is from 2020 Oct 06.

**Comment by dannygoldstein** [comment]
@sjoertvv are you still experiencing this on https://fritz.science?

**Comment by sjoertvv** [comment]
Thanks for checking, I forgot to close this. No similar issues on the new location. 

Although at the moment I can't add a source to my program if it is not yet saved by a different group (eg, I can't find ZTF20abjwvae in Fritz). I think that is how it is supposed to work? You either can safe via scanning or upload, but not simply by ZTF name. I'll also ask on Slack.
