### ISSUE TITLE
sources with no spectra throw errors

### ISSUE THREAD

**Issue by dannygoldstein** [skyportal/skyportal#114]
If a source doesn't have a spectrum then the corresponding Source page throws the following error: 

web_1  | ! App Error: Could not generate plot for source ZTFC19f

And the page says

▾ Spectroscopy
Please wait while we load your plotting data...

Most sources won't have spectra, so this is a bug. I think the page should just show an empty axis.

**Comment by dannygoldstein** [comment]
critical priority

**Comment by dannygoldstein** [comment]
Still seeing his in v0.9 (also for photometry) 

<img width="1294" alt="Screen Shot 2019-06-23 at 12 47 16 PM" src="https://user-images.githubusercontent.com/2769632/59981266-9a308100-95b5-11e9-9cfd-16efd4faa478.png">

**Comment by dannygoldstein** [comment]
Under photometry /spectroscopy instead of "Please wait while we load your plotting data.." it should say something like "This source has no photometry" or "This source has no spectroscopy..."

**Comment by acrellin** [comment]
This is fixed on master https://github.com/skyportal/skyportal/commit/dfe4db653c95357c96862b1806bd33ac53a43c59
