### ISSUE TITLE
Implement box zoom in vega-lite plots

### ISSUE THREAD

**Issue by dmitryduev** [skyportal/skyportal#1154]

**Comment by kmshin1397** [comment]
Currently not possible with vega-lite, will require moving to full vega plots:
https://github.com/vega/vega-lite/issues/4742

**Comment by dmitryduev** [comment]
Thanks for looking into this @kmshin1397! I think it should be fine to leave things as is on the Scanning page. As for the Alert page, I think we should just move over to bokeh.

**Comment by mcoughlin** [comment]
Closing given the size of the undertaking.
