### ISSUE TITLE
Perhaps we should define an `accessible_streams` parameter simllar to `accessible_groups`

### ISSUE THREAD

**Issue by dannygoldstein** [skyportal/skyportal#1159]
Perhaps we should define an `accessible_streams` parameter simllar to `accessible_groups`

_Originally posted by @dannygoldstein in https://github.com/skyportal/skyportal/pull/1125#discussion_r510547183_

**Comment by acrellin** [comment]
Duplicate of https://github.com/skyportal/skyportal/issues/1158
