### ISSUE TITLE
Watchlists

### ISSUE THREAD

**Issue by dmitryduev** [skyportal/skyportal#1165]
Implement user-defined (or group-based?) watchlists / some sort of a sentinel service. [frequently requested feature]

1. Put saved sources on a watchlist, get notifications (slack? email? text?) when an event associated with the objects happen 
2. Put in (R.A., Decl.) + radius and get notified when a candidate/source is saved, then 1.

This is more of an invitation for a discussion.

**Comment by acrellin** [comment]
Is this distinct from the current SourceNotification concept?

**Comment by dmitryduev** [comment]
I think I solved the second point here: https://github.com/fritz-marshal/fritz/pull/186.
I suggest to close this issue once that PR is merged since the first point has more to do with webhooks that we'll eventually get to + it is, as @acrellin noted, covered to some extent by the SourceNotification concept.
