### ISSUE TITLE
Impose width/max-width on Follow up request form fields

### ISSUE THREAD

**Issue by dmitryduev** [skyportal/skyportal#1166]
![image](https://user-images.githubusercontent.com/7557205/97047120-50e79d00-152d-11eb-8891-b7ffc5667ebd.png)

**Comment by dannygoldstein** [comment]
I can't reproduce this @dmitryduev. How did you get it to look this way?

**Comment by dmitryduev** [comment]
Fixed by @kmshin1397, closing.
