### ISSUE TITLE
Unable to save candidates to programs

### ISSUE THREAD

**Issue by Aishwarya113** [skyportal/skyportal#1172]
I was trying to save sources to some programs when I came across an error message for a few of those where it said, “Cannot save to group XYZ: insufficient group alert stream permissions”. These sources are added to those particular groups on Marshal, so I don’t know why this happened. For example, “ZTF20abxgwjr” has passed RCF filter and saved on Marshal, but when I try to add it on Fritz.science, I get this error. 
<img width="1440" alt="Screen Shot 2020-10-23 at 2 25 58 PM" src="https://user-images.githubusercontent.com/51973893/97055939-a7100c80-153c-11eb-8d79-9b5f4716dc09.png">

**Comment by stefanv** [comment]
Solution suggested by @dmitryduev:

> that endpoint allows you to see all data you have access to and will try to post that to a group, but if that group doesn't have enough permissions, that will fail. so it's just being very strict. We can make it post only the data a group has access to.

**Comment by dmitryduev** [comment]
Addressed in https://github.com/fritz-marshal/fritz/pull/75
