### ISSUE TITLE
Show only future runs in Assign Target to Observing Run

### ISSUE THREAD

**Issue by dmitryduev** [skyportal/skyportal#1177]
![image](https://user-images.githubusercontent.com/7557205/97065232-0d0e8b00-1561-11eb-9b0b-6e8d8f59888d.png)

**Comment by dannygoldstein** [comment]
Closing this as a wontfix for now - doing this adds some overhead involved in computing the ephemeris data for runs (sunrise, sunset, etc) which slow the page down too much.
