### ISSUE TITLE
Add FBOT into classification dropdown menu

### ISSUE THREAD

**Issue by yaoyuhan** [skyportal/skyportal#1181]
I would like to set the classification of https://fritz.science/source/ZTF20acigmel as FBOT (Fast Blue Optical Transient), but it's not in the dropdown menu. Can this be added? Thanks!

**Comment by profjsb** [comment]
We import the taxonomy from a separate project. Can you add an issue to https://github.com/profjsb/timedomain-taxonomy ? Or better yet, please make a PR so we know where this type of object fits in.

**Comment by yaoyuhan** [comment]
Ok thanks! I made a PR.

**Comment by dannygoldstein** [comment]
Fixed by #1182
