### ISSUE TITLE
Spectrum plot legend on source page is flipped order

### ISSUE THREAD

**Issue by guynir42** [skyportal/skyportal#1189]
I added a dummy spectra to one of the demo data sources. 

I used SEDM and some random MJD value. 

It renders the new spectrum just fine, but the legend items are in the wrong order:

![spectra_plot](https://user-images.githubusercontent.com/37179063/97325118-528dc980-187b-11eb-85e3-9ce9bb663262.gif)

The yellow plot is the original, nice looking spectrum from NOT and the black is my ugly five point dummy spectrum from SEDM. But the legend says the opposite!

**Comment by guynir42** [comment]
Also there could be possible issues if two spectra have very different flux normalizations.

**Comment by dannygoldstein** [comment]
@guynir42 Can you send me the data to reproduce this please

**Comment by guynir42** [comment]
I just posted a dummy spectrum, I'm not sure I still have the exact numbers I used. 
Did you try just posting a second spectrum on the demo data? 

I also just chose a random MJD so maybe that has something to do with it (the date is in the 19th century...)
