### ISSUE TITLE
Add ability to link to comment on marshal

### ISSUE THREAD

**Issue by stefanv** [skyportal/skyportal#1192]
Not sure where this should navigate to, but would be nice to be able to share a comment with colleagues.

@dmitryduev ?

**Comment by acrellin** [comment]
@stefanv is this still something you want to be able to do?

**Comment by stefanv** [comment]
It would probably have to be done as an argument to the page involved, something like https://fritz.science/source/14gqr?showComment=12345

@dmitryduev would this be very useful?  If not, we can close this.

**Comment by dmitryduev** [comment]
I'd close this :)
