### ISSUE TITLE
PS1 reticle is off by about an arcsecond

### ISSUE THREAD

**Issue by dannygoldstein** [skyportal/skyportal#120]
The PS1 reticle is always about 1 arcsecond SE of the SDSS reticle (which points to the correct location): 
<img width="282" alt="screen shot 2019-01-30 at 5 40 37 pm" src="https://user-images.githubusercontent.com/2769632/52024663-765d8900-24b6-11e9-9c17-f36c46619032.png">

<img width="288" alt="screen shot 2019-01-30 at 5 40 31 pm" src="https://user-images.githubusercontent.com/2769632/52024640-647be600-24b6-11e9-8139-817b70c49524.png">

**Comment by dannygoldstein** [comment]
medium priority

**Comment by denniscfeng** [comment]
Hi @dannygoldstein, I'm trying to see if I can fix the issue. Do you remember which source this is?

**Comment by dannygoldstein** [comment]
it should work for any source in the northern sky (dec > -30) in the SDSS footprint.

**Comment by acrellin** [comment]
https://github.com/skyportal/skyportal/pull/179
