### ISSUE TITLE
Change wording for save/request to save buttons/forms

### ISSUE THREAD

**Issue by dannygoldstein** [skyportal/skyportal#1217]
This is on fritz.science commit cf55d29

![Kapture 2020-10-28 at 20 34 26](https://user-images.githubusercontent.com/2769632/97522477-1a5eb780-195d-11eb-867e-52ee122353b4.gif)

**Comment by dmitryduev** [comment]
The other group must first accept it - see the corresponding Group Sources page. But a notification explaining that might be useful

**Comment by acrellin** [comment]
Yes, it's just a request that they save. Isn't saved yet until they accept.
