### ISSUE TITLE
PS1 cutouts on scanning page

### ISSUE THREAD

**Issue by cfremling** [skyportal/skyportal#1225]
There are too many instances where SDSS and DR8 data does not exist. PS1 images and links to PS1 for further inspection of the multi-band images are needed

**Comment by acrellin** [comment]
@cfremling cc @dmitryduev generating PS1 cutouts requires expensive external queries and is not worth doing for every candidate on the scanning page. How about a button to request the PS1 thumbnail in those instances where it's needed? That will result in far fewer expensive calls.

**Comment by cfremling** [comment]
That would be fine, a clickable link to show the color composite PS1 cutout when needed, and then also linking to the PS1 service. Linking is actually the most important since if you are wanting this info what you usually want to see is the color of the source by comparing the PS1 griz images and seeing where the source is brightest (sometime a CV in dormant state can be barely seen in just one of their filters).

Best,
Christoffer

________________________________

**Comment by dmitryduev** [comment]
This has been recently brought up again as a very useful feature, so just need to add a button to the scanning page that would upon clicking first generate the link and then pull the PS1 cutout.

**Comment by acrellin** [comment]
@dmitryduev I've thought about this a bit, and currently the only way we'd be able to pull in the changes would be to re-fetch the candidates, but we could preserve the filtering/pagination by re-submitting the page fetch from the front-end. Unfortunately we don't have a way of simply updating a single candidate, unless we add a new reducer than replaces the matching candidate in the list with the new data. Thoughts?

**Comment by dmitryduev** [comment]
Addressed in #1614.
