### ISSUE TITLE
Default to no groups selected on scanning page

### ISSUE THREAD

**Issue by cfremling** [skyportal/skyportal#1226]
Defaults on for example the scanning page need to be more reasonable. e.g.,
default to showing data from the previous night only. And definitely do not start with all programs enabled when initially visiting the page.

All similar issues users may have could alternatively be solved by having the system memorize many of the user selections across the site (when it makes sense). If I select Program. X as the only program to scan, that should still be my selection the next time I visit the page. I think the vast majority of users would agree with this.

**Comment by acrellin** [comment]
@cfremling an alternate approach would be to have no programs selected by default, showing no candidates, and then you can simply click the program(s) you want to filter on and see the results each time. This is much more likely to be implemented than saving your program selection from last time.

**Comment by acrellin** [comment]
I believe this is also how the old marshal works

**Comment by cfremling** [comment]
Right! yes this would be fine for now.

Christoffer
________________________________
