### ISSUE TITLE
Scanning page pagination + filtering seems broken

### ISSUE THREAD

**Issue by dmitryduev** [skyportal/skyportal#1233]
@kmshin1397 could you please look into this?
![bug-3](https://user-images.githubusercontent.com/7557205/97768016-4608ab80-1add-11eb-8459-5e0c8432fe75.gif)

**Comment by acrellin** [comment]
We should add pagination tests, too

**Comment by kmshin1397** [comment]
Good point Ari. I should have some time to work on this tomorrow
