### ISSUE TITLE
/users route is unimplemented

### ISSUE THREAD

**Issue by dannygoldstein** [skyportal/skyportal#124]
Would be really useful to have a /users route for admins, to be able to see the details of who is registered / has logged into the site. Currently if I go to the list of group members and click on an email address, I see something along the lines of  
<img width="536" alt="screen shot 2019-01-31 at 9 03 03 am" src="https://user-images.githubusercontent.com/2769632/52071048-0b07cb80-2537-11e9-9ac8-cf930fe19845.png">

**Comment by dannygoldstein** [comment]
high priority

**Comment by stefanv** [comment]
See #126
