### ISSUE TITLE
Have to manually change user roles by db queries

### ISSUE THREAD

**Issue by dannygoldstein** [skyportal/skyportal#125]
There should be a way to alter user roles in the browser.

Danny

**Comment by dannygoldstein** [comment]
high priority

**Comment by acrellin** [comment]
@dannygoldstein picking this back up, apologies for letting this fall through the cracks -- currently you can choose whether to make a group user an admin or not when adding them to the group via the front-end form. To change their admin status, they can simply be removed, and then re-added with the desired role. Does this satisfy the need expressed here?

**Comment by dannygoldstein** [comment]
@acrellin Is there now a frontend for this ?

**Comment by acrellin** [comment]
User roles are no changeable via the user management page
