### ISSUE TITLE
Transient failures in CI

### ISSUE THREAD

**Issue by mcoughlin** [skyportal/skyportal#1262]
For example: https://github.com/skyportal/skyportal/pull/1261, stopped at the equivalent of the make run stage. Any ideas? Also is there a way to retrigger easily from command line without just adding some extra code?

**Comment by mcoughlin** [comment]
@stefanv

**Comment by stefanv** [comment]
This looks like a legitimate CI failure?

**Comment by mcoughlin** [comment]
I suppose I misunderstand, I see:

Testing connection...Error: no token specified, and no suitable token found in .tokens.yaml
Reloading auth tokens and trying again...Error: no token specified, and no suitable token found in .tokens.yaml
Reloading auth tokens and trying again...Error: no token specified, and no suitable token found in .tokens.yaml
Reloading auth tokens and trying again...Error: no token specified, and no suitable token found in .tokens.yaml
...

Which to me looks like make run didn't converge. Maybe I am looking in the wrong place.

**Comment by dannygoldstein** [comment]
Closing as I haven't seen this in a week or so.

**Comment by dannygoldstein** [comment]
Happening on #1385, https://travis-ci.com/github/skyportal/skyportal/builds/202576392

**Comment by acrellin** [comment]
Bump the wait time up to allow more time for app to spin up

**Comment by acrellin** [comment]
In migration manager

**Comment by dmitryduev** [comment]
@acrellin haven't seen this for a while, can we close now?

**Comment by acrellin** [comment]
CI has been pretty stable, so closing for now
