### ISSUE TITLE
Add formatted preview for JSON

### ISSUE THREAD

**Issue by profjsb** [skyportal/skyportal#1277]
As a number of bots are posting JSON files to Comments, it would be useful to have a JSON previewer (in addition to the image/PDF).

**Comment by sjoertvv** [comment]
Great to see this deployed. I noticed however that files with periods in their name are not recognized as json (eg, https://fritz.science/source/ZTF20acjpwas) 

<img width="393" alt="Screen Shot 2020-12-02 at 12 13 15" src="https://user-images.githubusercontent.com/1986576/100865743-0b0ce580-3498-11eb-9305-a4e78acf3299.png">

**Comment by stefanv** [comment]
@sjoertvv Thanks for noticing that; fixed in https://github.com/skyportal/skyportal/pull/1459
