### ISSUE TITLE
Source saved by undefined user

### ISSUE THREAD

**Issue by dannygoldstein** [skyportal/skyportal#1298]
<img width="770" alt="Screen Shot 2020-11-05 at 10 17 44 PM" src="https://user-images.githubusercontent.com/2769632/98333053-c7b47980-1fb4-11eb-81ac-f8a12053096e.png">

Somehow, sources are being saved by "undefined" users. This source showed up on the frontend and was marked as having been saved to CLU by "undefined."

**Comment by dmitryduev** [comment]
It wasn't propagated when saving from the Alert page, but that has been fixed a long time ago.
