### ISSUE TITLE
Fix caching of `current_user`

### ISSUE THREAD

**Issue by bnaul** [skyportal/skyportal#13]
Currently we repeat the query for the current user's info many times; the caching mechanism in `tornado` stores the info in the `_current_user` attribute of a handler object (see [here](https://github.com/tornadoweb/tornado/blob/master/tornado/web.py#L1177-L1179)) but the different handlers don't share that attribute and so each handler that's touched calls it separately. When loading a `/source/{id}` route this currently repeats the same `SELECT * FROM users WHERE username = 'blah'` query 7 times.

Is it possible to make this attribute shared across subclasses or is that more trouble than it's worth?

**Comment by bnaul** [comment]
I think I have some more insight into this: `BaseHandler` from `baselayer` needs the current user for `flow.push` to know whom to forward the message to. That explains why every single handler is looking up the user info, since it's needed to return anything to the front end. This doesn't seem ideal but I'm not sure what to do about it, @stefanv any thoughts?

**Comment by stefanv** [comment]
There is now the option to use `BaseHandler.current_user_id`, which only queries a cookie and no longer the database.  Baselayer has been refactored to use this, preventing a database lookup whenever Flow (the WebSocket handler) is constructed.

**Comment by stefanv** [comment]
`BaseHandler.current_user_id` has been removed in the interest of simplicity.  Punting on this for now.
