### ISSUE TITLE
Add in sky lines and galaxy lines to spectrum plot 

### ISSUE THREAD

**Issue by dannygoldstein** [skyportal/skyportal#1300]

**Comment by dmitryduev** [comment]
@rjoebruch will this be closed by https://github.com/skyportal/skyportal/pull/1761?

**Comment by rjoebruch** [comment]
No they were not included in the lines dictionary.

**Comment by dmitryduev** [comment]
Added in https://github.com/skyportal/skyportal/pull/1993, closing.
