### ISSUE TITLE
Source page MUI datatable crashes with  Cannot read property 'substring' of undefined

### ISSUE THREAD

**Issue by dannygoldstein** [skyportal/skyportal#1303]
![Screen Shot 2020-11-06 at 12.32.51 AM.png](https://images.zenhubusercontent.com/59e:2c99cb0222d5de47baddd/d8bcc29e-aa65-4348-b2e5-8f7072e52bda)

To reproduce: 

1. Navigate to fritz.science/sources
2. Advance the table ~7-15 pages until the site crashes

**Comment by dmitryduev** [comment]
The cause is probably the same as for #1294

**Comment by kmshin1397** [comment]
This is due to sources having no `saved_at` field for whatever reason, leading to failure at SourceTable.jsx:350. Example I found was ZTF20acdewdg but there are probably more.

**Comment by kmshin1397** [comment]
actually that might not be it - just realized the table is displaying group.saved_at and not source.saved_at

**Comment by kmshin1397** [comment]
Ah, I think it's due to some sources not having any groups visible to the user (for example, I don't see any groups on ZTF20ackefmn - I'm assuming it was saved to a group I don't have access to). We should probably filter those out in the source handler.
