### ISSUE TITLE
Improve app color palette/dark mode

### ISSUE THREAD

**Issue by kmshin1397** [skyportal/skyportal#1305]
There are likely pages throughout the app where dark mode does not look as it should or just doesn't look good. Exploring enhancements to the overall color theme (i.e. a darker blue for the header?) would be good to do in conjunction. Potentially could expose the color theme to the configs as well.

**Comment by dannygoldstein** [comment]
@joelachance seems like this one may be up your alley - interested ?

**Comment by joelachance** [comment]
haha, i was just looking at this one :) LGTM, i'll take it! (it doesn't look like I can assign myself)
