### ISSUE TITLE
Refactor source and candidate handlers into Obj, Source, and Candidate  handlers 

### ISSUE THREAD

**Issue by dannygoldstein** [skyportal/skyportal#1307]

**Comment by kmshin1397** [comment]
Hi @dannygoldstein what's the status here, and what can I do to help?

**Comment by kmshin1397** [comment]
After further discussion, it seems more prudent to just add a DELETE handler for Objs for now, as that is functionality we don't currently have. @guynir42 Did you want to implement that or should I?

**Comment by guynir42** [comment]
I got a little tied up with things here so maybe you should go ahead and implement it. 
I will get back into it and implement the posting of Objs at some point as well. But that's probably not so urgent.

**Comment by kmshin1397** [comment]
No problem - I'll take care of the DELETE Obj functionality then.

**Comment by dmitryduev** [comment]
The DELETE Obj functionality was implemented, so closing. May reopen in the future.
