### ISSUE TITLE
Mark dates of spectra with "S" tick on photometry plot

### ISSUE THREAD

**Issue by dannygoldstein** [skyportal/skyportal#1329]
Request from Kate Maguire. Mark the dates of each of an object's visible spectra on the photometry plot with an 'S' at the top of the plot, e.g.:

![Screen Shot 2020-11-11 at 1.31.08 PM.png](https://images.zenhubusercontent.com/59e2c99cb0222d5de47baddd/656ced2a-0925-4053-a141-907b5d3e7fb3)

**Comment by dmitryduev** [comment]
@scizen9 implemented this, closing.
