### ISSUE TITLE
Add tooltips to overplotted spectral lines on spectroscopy plot 

### ISSUE THREAD

**Issue by dannygoldstein** [skyportal/skyportal#1330]
Request from Kate M. 

When you hover over a vertical rule indicating an overplotted spectral line on the spectroscopy plot, display some information about the line. Rest wavelength, and some identifier of the line (e.g., a name like H-alpha or a string indicating the atomic transition, like He 3->2.)

**Comment by guynir42** [comment]
Closed by #2486
