### ISSUE TITLE
Add option to retrieve sources by classification to SourceHandler.get

### ISSUE THREAD

**Issue by dannygoldstein** [skyportal/skyportal#1332]
Request from @mansikasliwal:

Users want to be able to retrieve all sources that have been classified a certain way across all their groups. We should be able to specify a list of (taxonomy, class_within_taxonomy) pairs to the sourcehandler to only retrieve sources that are of that class.

**Comment by kmshin1397** [comment]
This is implemented as a part of #1495, but that implementation just filters on class names instead of (taxonomy, class) pairs. Should I change that logic? @dmitryduev

**Comment by dmitryduev** [comment]
Yea, I think using the (t, c) pair is preferable: there could be classes in different taxonomies that use the same name, but mean somewhat different things. For example, what some people might call bogus (meaning "not my science") would be quite different from we call bogus in acai.
