### ISSUE TITLE
JSON decoding errors in front-end while posting transients

### ISSUE THREAD

**Issue by jvansanten** [skyportal/skyportal#1344]
While posting ~1000 transients over a timespan of 20 minutes between 2020-11-12T13:29:00 and 2020-11-12T13:53:00, I got these error popups up in the frontend:

![Screen Recording 2020-11-12 at 14 42 17](https://user-images.githubusercontent.com/938705/98989693-bd9cf880-2529-11eb-8a78-e20eecbf8d77.gif)

Each of these posts consisted of:

- 1 GET /api/candidates/{obj_id}
- 0 to 14 POST /api/candidates (usually 1, though)
- 1 GET /api/sources/{obj_id}
- 0 or 1 POST /api/sources
- 1 PUT /api/photometry

The client uses aiohttp with 20 connections per host, and exponential backoff starting at 0.1 s on status >= 500. I did not explicitly track the number of failed connections, but saw backoffs of up to 30s, or ~8 iterations.

**Comment by dannygoldstein** [comment]
@stefanv Looks like we should make some of these functions asynchronous as well?

**Comment by stefanv** [comment]
Anything that takes more than a second or two to respond, yes.

**Comment by dannygoldstein** [comment]
@jvansanten, can you let us know if you are seeing this behavior anymore ? 

it may be that between https://github.com/cesium-ml/baselayer/issues/176 and #1350, this is fixed.

**Comment by jvansanten** [comment]
I tried the same thing again today between 12:39 and 12:57 UTC, this time adding

- 0 to 3 POST /api/thumbnail
- 0 to 3 POST /api/comment

and saw the same behavior: transitory 502 on the API endpoints, and JSON decoding popups in the front-end.

**Comment by stefanv** [comment]
Have we rolled out a new baselayer and skyportal yet, Danny? Otherwise we should have seen different behavior at least.

**Comment by dannygoldstein** [comment]
We have rolled out #1350 but not https://github.com/cesium-ml/baselayer/issues/176, I will roll that out now

**Comment by dannygoldstein** [comment]
@jvansanten, we just deployed https://github.com/cesium-ml/baselayer/issues/176, are you still seeing this ?

**Comment by jvansanten** [comment]
I posted a batch of ~100 objects today, and did not see the popups. Still lots of 502 on the API endpoints, though.

**Comment by stefanv** [comment]
@jvansanten What is the sequence of API calls that causes a 502 to appear?

**Comment by stefanv** [comment]
This is quite embarrassing, but I returned 502s instead of 503s.  My apologies, it is fixed here: https://github.com/cesium-ml/baselayer/pull/179
