### ISSUE TITLE
Starlist queries trigger 502s 

### ISSUE THREAD

**Issue by dannygoldstein** [skyportal/skyportal#1349]
On the observing run page a separate starlist query is issued for each observing run assignment. Each of these queries takes several seconds. With 8 web workers on fritz.science, the web workers can get totally blocked when more than 8 queries are issued simultaneously. Somehow (I am not totally sure how) this causes the website to crash and send back 502s.

**Comment by stefanv** [comment]
What happens is that nginx marks each unresponsive server as "unavailable".  After all servers have become unavailable, only the status server is there, and it serves the 502.

**Comment by stefanv** [comment]
Endpoints should always respond immediately; an example of how to do async-type operations is what we do for finder charts:

https://github.com/skyportal/skyportal/blob/master/skyportal/handlers/api/source.py#L1128

And here is how to serve a large file for download, while allowing threads to remain active:

https://github.com/skyportal/skyportal/blob/master/skyportal/handlers/api/source.py#L1155

**Comment by dannygoldstein** [comment]
> What happens is that nginx marks each unresponsive server as "unavailable".  After all servers have become unavailable, only the status server is there, and it serves the 502.

Ah!
