### ISSUE TITLE
Expand news feed items

### ISSUE THREAD

**Issue by dannygoldstein** [skyportal/skyportal#1353]
- [x] New spectrum
- [x] New follow-up photometry
- [x] New classification
- [x] New (human) comment

**Comment by acrellin** [comment]
@dannygoldstein can you expand on the definition (from a DB perspective) of "follow-up photometry"?

**Comment by dannygoldstein** [comment]
Basically any non-alert generated photometry (i.e., everything but ZTF/LSST). To avoid hardcoding anything, we may want to make this configurable? I think it could make sense to have something in the configuration file like `news_feed_exceptions: photometry: ztf` or something along these lines.

**Comment by dannygoldstein** [comment]
I am not sure this is concretely definable from a DB perspective at present, I think users will often forget to add followup_request_id or assignment_id (based on what I've observed on fritz.science)

**Comment by dannygoldstein** [comment]
But certainly anything with a non-null `followup_request_id` or `assignment_id` would fall into the category of "followup photometry" in my mind.
