### ISSUE TITLE
Thumbnail logic

### ISSUE THREAD

**Issue by dmitryduev** [skyportal/skyportal#1361]
It looks like we may have oversimplified the logic regarding the thumbnails when we decoupled them from photometry, For example: https://fritz.science/api/sources/ZTF18abxhsyn I can see, e.g., three "new" thumbnails all pointing to the same static file.

- For inspection purposes, one can look up all thumbnails from the Alert page.
- Do we really need multiple "ZTF" cutouts?
- If yes, then we also need to add the ability to see all posted thumbnails, and not only the most recent ones
- Also, currently there's no way to check if thumbnails exist if your token has no access to the filter it's already saved to

**Comment by jvansanten** [comment]
It may make sense to distinguish between reference images (sdss, ps1, dr8, perhaps the ztf reference itself), which are associated with an object x survey, and subtraction images, which are associated with a particular photometric point. These are conceptually different, and it doesn't really make sense to display a single subtraction image for a transient.

**Comment by steveschulze** [comment]
While you are working on that, could you add an option to Fritz to inspect cut-outs (image, ref, subtraction) of each alert of a given object? This is important and extremely valuable for fast and infant-SN programs where the follow-up strategy is based on 1-2 detections.

**Comment by dmitryduev** [comment]
@steveschulze this is possible. For example:
https://fritz.science/alerts/ztf/ZTF18aaiwsqa
(click "Show Thumbnails" in the table; haven't implemented clicking on the lc yet)
API endpoint: https://fritz.science/api/alerts/ztf/ZTF18aaiwsqa/cutout?candid=1392098985715015002&cutout=template&file_format=png

**Comment by steveschulze** [comment]
Thanks Dima. :)

**Comment by acrellin** [comment]
Closing in favor of https://github.com/skyportal/skyportal/issues/1970
