### ISSUE TITLE
User preferences bloat API responses

### ISSUE THREAD

**Issue by dannygoldstein** [skyportal/skyportal#1362]
https://fritz.science/api/sources?group_ids=43

The nested annotations include user preferences, which can bloat the response. I don't think we need to return user preferences in any of the public facing handlers

**Comment by dannygoldstein** [comment]
ACL lists also bloat the responses from many endpoints that contain nested users.

**Comment by stefanv** [comment]
Yes, let's move extended user info to another private endpoint. Preferences can be served from profile, eg.

**Comment by acrellin** [comment]
Fixed in #1420
