### ISSUE TITLE
Implement dedicated stream groups

### ISSUE THREAD

**Issue by dmitryduev** [skyportal/skyportal#1368]
For bookkeeping:

- Add users to these groups based on their stream access
- Always post stream photometry to these groups

**Comment by acrellin** [comment]
@dmitryduev can you expand on how these will be used? Thanks

**Comment by acrellin** [comment]
@dmitryduev pinging you again here -- can you please expand?

**Comment by acrellin** [comment]
@dmitryduev another ping -- please expand
