### ISSUE TITLE
Store trailing zeros on redshifts in postgres 

### ISSUE THREAD

**Issue by dannygoldstein** [skyportal/skyportal#1386]
Currently the trailing zeros on redshifts are getting cut off due to being stored as doubles. We need to keep those so that we can track redshift precision

**Comment by acrellin** [comment]
Use Postgres NUMERIC & Python decimal types

**Comment by scizen9** [comment]
AFAIK, Postgres only allows one to specify the NUMERIC format for the entire column, not individual rows.  If we stored the redshift error, we could use that to format the redshift appropriately for display.

**Comment by acrellin** [comment]
Why would we not want to apply it to the entire column?

**Comment by scizen9** [comment]
Because the precision varies with target.

**Comment by dmitryduev** [comment]
This will be addressed once https://github.com/skyportal/skyportal/issues/1795 is implemented, so closing.
