### ISSUE TITLE
Refactor the members list on the group page to use paginated MUI DataTable

### ISSUE THREAD

**Issue by kmshin1397** [skyportal/skyportal#1391]

**Comment by acrellin** [comment]
@kmshin1397 you probably already considered this, but I think server side pagination would be overkill here. The users list should be a relatively small response content.

**Comment by kmshin1397** [comment]
This is now effectively ready for review, but I will wait to post the PR until #1404 goes in, as that refactor will cause some merge conflicts with changes I made working on this issue that I want to resolve.
