### ISSUE TITLE
sinceDaysAgo widget does not save by default

### ISSUE THREAD

**Issue by stefanv** [skyportal/skyportal#1437]
Open sinceDaysAgo widget preferences, type a number, and press enter.

Behavior seen: the value is not saved.
Behavior expected: value is saved.

**Comment by acrellin** [comment]
@stefanv That's a parameter for which widget?

**Comment by stefanv** [comment]
The New Sources widget, top right corner.

**Comment by stefanv** [comment]
Has been fixed.
