### ISSUE TITLE
Add tags to all OpenAPI specs

### ISSUE THREAD

**Issue by dmitryduev** [skyportal/skyportal#1438]
This would make our API docs better structured.

For example, this is what K's API docs look like:
![image](https://user-images.githubusercontent.com/7557205/100652332-a0bf3e00-32fb-11eb-9845-c26f74d888ba.png)

**Comment by dannygoldstein** [comment]
where are the tags?

**Comment by dmitryduev** [comment]
A way to group endpoints together like in the example above, to make things more easily readable.
Here's another one:
![image](https://user-images.githubusercontent.com/7557205/100658653-49719b80-3304-11eb-83a3-0faac987e863.png)

**Comment by dmitryduev** [comment]
Or you mean, what do we call them? I'd be things like "candidates", "sources", "follow-up", "sedm", "kowalski", etc
