### ISSUE TITLE
Add notifications icon to top panel

### ISSUE THREAD

**Issue by acrellin** [skyportal/skyportal#1481]
Add a notifications icon with a colored dot to indicate the presence of new, unread notifications. Events that should trigger notifications might include group admission requests (shown to relevant group admins), source save requests, activity regarding favorite sources (not yet implemented), etc.  Clicking the notifications icon could either open a new notifications page (as with GitHub) or open a drop-down w/ clickable notification items.

**Comment by dmitryduev** [comment]
As discussed at the Iteration meeting: let's also enable user mentions with "@" displayable under notification as part of this effort.
