### ISSUE TITLE
Add a GH Action to test building and running the Docker images

### ISSUE THREAD

**Issue by dmitryduev** [skyportal/skyportal#1511]
(and also loading the demo data)

**Comment by dmitryduev** [comment]
We do that on F so closing.

**Comment by kmshin1397** [comment]
@dmitryduev Aha, I remember that we closed this in the last iteration meeting. Do we want to revive it and add that SP workflow that you mentioned yesterday?

**Comment by dmitryduev** [comment]
Yes, I think it's worth it. I would only run such action on commits/merges to master (not to waste the computational resources on all the PRs).

**Comment by kmshin1397** [comment]
Yeah I think that makes sense
