### ISSUE TITLE
Frontend error for a new account

### ISSUE THREAD

**Issue by dmitryduev** [skyportal/skyportal#1520]
This is a sloppy one, haven't looked in much detail as to what's it caused by:
![image](https://user-images.githubusercontent.com/7557205/102672519-dbbbd100-4145-11eb-9d9d-ecc28ce377ba.png)

**Comment by acrellin** [comment]
Is this on the homepage? If so it's likely related to one of the many instances of `timespan.label` in `TopSources`, e.g. https://github.com/skyportal/skyportal/blob/master/static/js/components/TopSources.jsx#L225

**Comment by acrellin** [comment]
@dmitryduev what do you mean by "new account"? Did this happen after logging in as a new user for the first time?

**Comment by dmitryduev** [comment]
I created a new account, added it to a single group, saved one source, and navigated back to the landing page, but I may be missing something.

**Comment by dannygoldstein** [comment]
does it persist after a hard refresh?

**Comment by acrellin** [comment]
@dmitryduev is this still relevant/reproducible?

**Comment by dmitryduev** [comment]
Haven't seen in a while, so closing for now.
