### ISSUE TITLE
Delete candidate with obj_id

### ISSUE THREAD

**Issue by AlexGKim** [skyportal/skyportal#1525]
This is a request to be able to delete a candidate with obj_id.

I would like to delete a candidate now but I do not know how to get its candidate_id, which is required in the current API to delete candidates.

**Comment by acrellin** [comment]
@AlexGKim  Thanks for noting this issue; we have a plan for restructuring the API in a way that will address it We'll link a PR to this issue when ready.

**Comment by dannygoldstein** [comment]
@AlexGKim yes, we are working on this. Stay tuned !

**Comment by acrellin** [comment]
Closing in favor of https://github.com/skyportal/skyportal/issues/1312
