### ISSUE TITLE
Investigate best side-effect library for Redux

### ISSUE THREAD

**Issue by stefanv** [skyportal/skyportal#153]
We currently use thunks, but it's a bit clunky.  Consider one of the popular alternatives:

- https://redux-saga.js.org/docs/introduction/BeginnerTutorial.html
- https://redux-loop.js.org/

**Comment by acrellin** [comment]
@stefanv since these are pretty neatly handled within `baselayer`'s `API` module, I'm closing this for now.

**Comment by stefanv** [comment]
For whomever revisits this issue in the lonely future, I had my eyes set on https://redux-observable.js.org/docs/basics/Epics.html
