### ISSUE TITLE
unable to save new instrument because of non-enum filters

### ISSUE THREAD

**Issue by AlexGKim** [skyportal/skyportal#1532]
I am posting a new instrument with new filters that are not defined with enum values.

This is the error I get.

> JSON response: {'status': 'error', 'message': '(builtins.LookupError) "desi::b" is not among the defined enum values\n[SQL: INSERT INTO instruments (created_at, modified, name, type, band, telescope_id, filters, api_classname, listener_classname) VALUES (timezone(%(timezone_1)s, CURRENT_TIMESTAMP), timezone(%(timezone_1)s, CURRENT_TIMESTAMP), %(name)s, %(type)s, %(band)s, %(telescope_id)s, CAST(%(filters)s AS bandpasses[]), %(api_classname)s, %(listener_classname)s) RETURNING instruments.id]\n[parameters: [{\'band\': \'optical\', \'name\': \'DESI\', \'filters\': [\'desi::b\', \'desi::r\', \'desi::z\', \'desi::brz\'], \'telescope_id\': 6, \'type\': \'spectrograph\', \'listener_classname\': None, \'api_classname\': None}]]', 'data': {}, 'version': '0.9.dev0+git%aI.48d1ffe'}

**Comment by acrellin** [comment]
@AlexGKim currently the list of allowed filters is as found here: https://skyportal.io/docs/api.html#tag/instruments/paths/~1api~1instrument/post  (from sncosmo's list of built-in bandpasses https://sncosmo.readthedocs.io/en/stable/bandpass-list.html) .  If your filters are not present there, let us know and we will extend that list.

**Comment by acrellin** [comment]
@AlexGKim I'm going to close this issue, but please do open another one requesting that missing bandpasses be added if you determine that your filters are not in the list provided. Thanks
