### ISSUE TITLE
Request for new filters

### ISSUE THREAD

**Issue by AlexGKim** [skyportal/skyportal#1534]
I am requesting new filters to enumerate, which correspond to the 3 arms of the DESI spectrograph. 'desi::b', 'desi::r', and 'desi::z' would be appropriate.

**Comment by acrellin** [comment]
@AlexGKim  Are the r and z filters distinct from those listed here? https://sncosmo.readthedocs.io/en/stable/bandpass-list.html#des

**Comment by AlexGKim** [comment]
@acrellin .  Indeed they are distinct.  Let me describe what is happening in more detail.  Perhaps I am thinking of "filter" in a way inconsistent with SkyPortal's usage.  The DESI spectrograph has three channels, labeled 'g', 'r', 'z', although their throughputs do not correspond exactly with those of broadband filters.  The default output for a single object of the DESI analysis pipeline are three separate 'g', 'r', and 'z' spectra.  A non-default output is a combination of the three, labeled as 'grz'.  So I was planning to upload spectra based on these different channels or the combination.

**Comment by AlexGKim** [comment]
@acrellin .  I think we can close this issue.  I think I am trying to use "filter" in a way that they are not meant to.

**Comment by dannygoldstein** [comment]
@AlexGKim - we need the filter transmissions to add these, do you have them handy?

**Comment by AlexGKim** [comment]
@dannygoldstein , I think that what I want is not the SkyPortal concept of filter.  So I can cancel this request.

While I have your ear, in DESI we get time series of spectra, but in the SkyPortal viewer, the default is that all the spectra are plotted in the same window.  How can SkyPortal to plot multiple spectra in different windows?
