### ISSUE TITLE
More general source table columns

### ISSUE THREAD

**Issue by acrellin** [skyportal/skyportal#154]
From Danny Goldstein:

The new columns in source are fairly general, but I worry that eventually the Source table will grow to so many columns that it will be difficult to keep track of the schema. To simplify things, I wonder if it would be better to have a single metadata column with the JSONB datatype, and columns such as the following could be fields in a JSONB document (no-sql style):

simbad_class = sa.Column(sa.Unicode, nullable=True, )
simbad_info = sa.Column(JSONB, nullable=True)
gaia_info = sa.Column(JSONB, nullable=True)
tns_info = sa.Column(JSONB, nullable=True)
tns_name = sa.Column(sa.Unicode, nullable=True)

**Comment by profjsb** [comment]
As it's clear that we are now pushing non-generic fields to metadata JSONB, we should give some thought to how we might keep track of what's available for query and for display. Some possibilities:

1) Do nothing. Leave it up to the power user to determine what they want to query on in the metadata. Configured display would have to known which metadata fields are available if they want to show them (e.g., a Gaia ID or SIMBAD link).

2) Provide a look up function on available fields (that the user can see). For example, scan ~1000 random sources and assemble the union of available fields. Could be a materialized view with a long refresh time to avoid making this call often.

3) Save the available fields in a separate table as the data is loaded and check as new sources are added if that table needs to be updated. 

One idea would be that this could be part of a data/schema exploration widget.

I can see pluses and minuses of each of the above. Curious to get @stefanv and @acrellin's thoughts.

**Comment by stefanv** [comment]
I was thinking of having the custom fields be specified in the configuration file, and then exposing those fields to the API and rendering them to users.  So, I guess a pre-specified option 2.
