### ISSUE TITLE
How to plot spectra in multiple windows?

### ISSUE THREAD

**Issue by dannygoldstein** [skyportal/skyportal#1541]
While I have your ear, in DESI we get time series of spectra, but in the SkyPortal viewer, the default is that all the spectra are plotted in the same window.  How can SkyPortal to plot multiple spectra in different windows?

__Originally posted by @AlexGKim in https://github.com/skyportal/skyportal/issues/1534#issuecomment-751379135__

**Comment by dannygoldstein** [comment]
Click on "manage data" under the spectrum plot, then click on the row of the spectrum in the table you want to plot and it should expand out into a one-spectrum bokeh plot.

**Comment by AlexGKim** [comment]
I was asking on being able to have multiple plotting windows so that spectra taken on different dates would show up separately automatically.
