### ISSUE TITLE
Vega spectrum erroring with "a is undefined"

### ISSUE THREAD

**Issue by acrellin** [skyportal/skyportal#1559]

**Comment by acrellin** [comment]
@guynir42 any idea when this started happening?

**Comment by guynir42** [comment]
@acrellin I am not sure. There is a separate issue where non-existing spectra also display as an empty plot, and it's hard to say for each source what causes it. 
The empty spectra I am fixing now, but when the spectra exists is more difficult to pin down.

**Comment by guynir42** [comment]
The offending commit is 88b469fc46b02d7f0b94518e9a5ff699172d31eb

**Comment by guynir42** [comment]
Will be closed by #1561

**Comment by guynir42** [comment]
Closed by #1561
