### ISSUE TITLE
Investigate JS9 widgets for displaying thumbnails

### ISSUE THREAD

**Issue by stefanv** [skyportal/skyportal#157]
- Widgets: https://js9.si.edu/
- Example display: https://mars.lco.global/7473176/

**Comment by dannygoldstein** [comment]
@profjsb @dmitryduev want to revive this. any thoughts here?

**Comment by profjsb** [comment]
As I found, it's pretty a heavy lift (lots of extra CSS/JS) and not clear what we gain from it.

**Comment by dannygoldstein** [comment]
@profjsb OK, do you want to close this issue then ?

**Comment by dmitryduev** [comment]
Closing for now since we don't seem to have a good use case for this anymore; may repoen in the future.
