### ISSUE TITLE
Clean up test fixture DB rows upon going out of scope

### ISSUE THREAD

**Issue by kmshin1397** [skyportal/skyportal#1602]

**Comment by acrellin** [comment]
https://stackoverflow.com/a/22638709/1402177

**Comment by acrellin** [comment]
@kmshin1397   we can also re-use fixtures instead of re-creating them for each test https://factoryboy.readthedocs.io/en/stable/orms.html#factory.alchemy.SQLAlchemyOptions.sqlalchemy_get_or_create
