### ISSUE TITLE
Graphical Annotations

### ISSUE THREAD

**Issue by guynir42** [skyportal/skyportal#1620]
Use a type of annotation to show models, spectral lines, and other points of interest on top of other plots like photometry or spectra. 

There are a few things that need to be done to do this:
-Make photometry and spectra directly annotatable. Thus it will be possible to have an annotation on a source or on a spectrum or photometry (all lightcurves together as a single entity or each point?). This requires some thinking. 
-Remove the constraint on having a unique annotation for each object/origin. 
-Instead, the GET should, by default, only bring out the most recent version for that object/origin combination. Upon specific request, all versions are returned instead. 
-Figure out the schema for a graphical annotation. 
  * The annotation must include xval, yval, and optionally yerr. 
  * The yval could be numeric (continuous model) or string (discrete points such as spectra lines, or explosion time). 
  * Other information needed to produce the plot. I can't think of many other things. 
  * The graphical data can be saved inside the regular annotation data or in a separate JSONB column. 
  * The model formula, coefficients and physical parameters can be given like any regular annotation. 
  * There could be another column specifying that this is a graphical annotation. Or we skip this and figure it out by the form of the annotation data. 
-Need to add code to the plotting tools to show these models along with the original data. The plotting would be toggled by radio buttons on the side. 
-Need to figure out, for each user, which radio buttons should be showed:
  * All sources that are accessible to the user should be available but turned off by default?
  * Configuration for each user remembers which origin name was turned on, and that is always turned on for all objects?
  * Maybe instead, each user explicitly defines which annotations are toggled on or off?

**Comment by profjsb** [comment]
Ping @guynir42

**Comment by guynir42** [comment]
No longer relevant with the new analysis framework. 
Will reopen if there's a separate use-case for this.
