### ISSUE TITLE
make run fails because of error in ./baselayer/tools/fill_conf_values.py

### ISSUE THREAD

**Issue by ale-munozarancibia** [skyportal/skyportal#1628]
I downloaded the current version using

`git clone https://github.com/skyportal/skyportal.git`

and installed it following https://skyportal.io/docs/setup.html. But when I run

`make run`

I obtain the following error:

```
  File "./baselayer/tools/fill_conf_values.py", line 18
    while chunk := f.read(8192):
                 ^
SyntaxError: invalid syntax
make[1]: *** [baselayer/Makefile:70: fill_conf_values] Error 123
make: *** [Makefile:74: run] Error 2
```

I checked the downloaded file skyportal/baselayer/tools/fill_conf_values.py and noted that it's not the same currently available in https://github.com/cesium-ml/baselayer/tree/81f6f22631c39c6c174a116675fade95b0134fb0/tools/fill_conf_values.py. Do I need to use a different command to download the correct version?

**Comment by stefanv** [comment]
Please try under Python 3.8 or higher.

**Comment by ale-munozarancibia** [comment]
Ok, should the requirements change then? Now it asks `python >= 3.7`

**Comment by stefanv** [comment]
@ale-munozarancibia Yes, you're right; I'm sorry about that, it's an oversight on my part.

**Comment by stefanv** [comment]
This should be fixed now; thanks for the report @ale-munozarancibia!

**Comment by ale-munozarancibia** [comment]
You're welcome, thanks for the quick reply! In this case I had to use `/usr/bin/python3.8 -m venv skyportal_env` instead of `virtualenv skyportal_env`, maybe want to update that in https://skyportal.io/docs/setup.html.
