### ISSUE TITLE
Update 'Makefile Targets' in docs

### ISSUE THREAD

**Issue by joelachance** [skyportal/skyportal#1660]
Going through [the documentation](https://skyportal.io/docs/usage.html#important-makefile-targets), I'm noticing there's some differences between the docs and the makefile, specifically `make lint-install` vs `make lint-githook` in the docs.

Both `lint-unix` and `lint` appear in the docs, but are not in the makefile help.

**Comment by stefanv** [comment]
Thanks for spotting that @joelachance.  We have since moved to pre-commit, so the instructions are now `pip install pre-commit && pre-commit install`.
