### ISSUE TITLE
Incorporate database migrations into CI

### ISSUE THREAD

**Issue by kmshin1397** [skyportal/skyportal#1662]
Likely will take the form of a new GA workflow where we checkout the last migration point, try running any new migrations on it, etc.

**Comment by stefanv** [comment]
Something like:

1. Check out SkyPortal master.
2. Initialize the database.
3. Check out the PR branch.
4. Run the test suite as normal.

If migration fails, we'll see it.

Related: https://github.com/skyportal/skyportal/issues/1175
