### ISSUE TITLE
Reticles are off for non-square thumbnails

### ISSUE THREAD

**Issue by dmitryduev** [skyportal/skyportal#1706]
We should think about a way to handle this:
![image](https://user-images.githubusercontent.com/7557205/109352905-6c8ee700-7830-11eb-8088-b0b228d5a092.png)

These are events detected close to the CCD edge. They are always centered on the longer side.

**Comment by stefanv** [comment]
How do we know where to position the cross-hairs in this case?

**Comment by dmitryduev** [comment]
Yea, we could pad on the shorter side, but we would need to know the transient (x, y) position to do it correctly. We could actually do this on the K side as that info is available in the alerts, but does not get posted to SP.

**Comment by stefanv** [comment]
If SkyPortal does not have this information, I guess there's nothing we can do about it here?

**Comment by dmitryduev** [comment]
Yea, let's close and file an issue on K instead.

**Comment by dmitryduev** [comment]
Closing in favor of https://github.com/dmitryduev/kowalski/issues/82.
