### ISSUE TITLE
WidgetPrefsDialog expects a string

### ISSUE THREAD

**Issue by joelachance** [skyportal/skyportal#1709]
Error below:

It appears we're passing an object to `initialValues` and that prop is expecting a string.

<img width="471" alt="Screen Shot 2021-03-01 at 8 13 37 AM" src="https://user-images.githubusercontent.com/3891660/109511791-06d96f80-7a69-11eb-8ca7-b354d8697db9.png">

**Comment by kmshin1397** [comment]
Hm, I thought we fixed this some time ago (maybe like 2 weeks ago) - is this up to date with master? Does your WidgetPrefsDialog.jsx have [this section](https://github.com/skyportal/skyportal/blob/cb7ddd2e95405f7d0487542a0f72955453658943/static/js/components/WidgetPrefsDialog.jsx#L143-L145)?

**Comment by joelachance** [comment]
My branch was not up to date with master-- after a pull, it does look like this is fixed-- i'll close. Thx!
