### ISSUE TITLE
Latest baselayer doesn't work with SkyPortal

### ISSUE THREAD

**Issue by stefanv** [skyportal/skyportal#173]
This is due to the change in auth tokens having names.

See error of profile loading when SkyPortal fires up.

**Comment by acrellin** [comment]
@stefanv I'm unable to reproduce with latest master of both SkyPortal and baselayer.

**Comment by acrellin** [comment]
@stefanv did you re-run `make load_demo_data` after checking out the new branches?

**Comment by stefanv** [comment]
My mistake; sorry for the noise.
