### ISSUE TITLE
Make header/navbar narrower

### ISSUE THREAD

**Issue by dmitryduev** [skyportal/skyportal#1749]
Ours takes up a lot of space, which is mostly empty. 
I personally like the default MUI navbar height. Thoughts?

**Comment by stefanv** [comment]
I don't think it wastes that much space, but if you want to shave off a few pixels and scale down the logos, that's fine with me.

**Comment by kmshin1397** [comment]
I never really noticed (which probably means that it is also fine as is) but you're right in that the MUI default is noticeably shorter in height. I'd also be fine with moving to a narrower app bar - reclaiming unused space is always good :)

**Comment by joelachance** [comment]
My two cents: The top navbar doesn't contain much, and I agree takes up some space. This is a bigger change, but moving the four things I does contain (hamburger, logo, notifications, and profile) into the side navbar would probably make things a bit simpler in the long run.

**Comment by stefanv** [comment]
That works for me too.

**Comment by dmitryduev** [comment]
@joelachance sounds like a good idea! Would you be willing to play around with how it might look?

**Comment by joelachance** [comment]
Sure! I'll take this one.

**Comment by joelachance** [comment]
Below are some pretty rudimentary mockups. Nothing here is pixel perfect, but more of a rough sketch. These would replace the header entirely and we would only have a sidebar moving forward.

The one call-out I have here is that for the minimized layout, I'm not sure the icons are explicit enough to describe their respective pages. We may need to do something differently here (or simply not have a minimized sidebar).

For mobile, I'm thinking we have a [floating action button](https://material-ui.com/components/floating-action-button/#floating-action-button) that triggers the sidebar, as it does now.

![Screen Shot 2021-03-14 at 11 42 26 PM](https://user-images.githubusercontent.com/3891660/111104667-35525280-851f-11eb-8370-69a1ce496332.png)
![Screen Shot 2021-03-14 at 11 40 08 PM](https://user-images.githubusercontent.com/3891660/111104668-35eae900-851f-11eb-8a7c-075312b93351.png)

**Comment by avngzy** [comment]
Should I follow the mockups that joel previously did or is there anything else in mind?

**Comment by acrellin** [comment]
@avngzy Yes, following those mockups would be a great place to start, and also feel free to propose alternatives (with screenshots). Thanks!

**Comment by profjsb** [comment]
@avngzy any progress on this?

**Comment by profjsb** [comment]
Hey @avngzy I’m using ZenHub in GitHub, [click this link](https://app.zenhub.com/workspaces/fritz-5f9c5973bfc5bd000fc105fd/board) to join my workspace and see other features available in GitHub or [download the ZenHub extension](https://www.zenhub.com/extension) and sign up with your GitHub account. 
  _Posted using [ZenHub](https://www.zenhub.com)_
