### ISSUE TITLE
deleting a candidate without knowing its candidate_id

### ISSUE THREAD

**Issue by AlexGKim** [skyportal/skyportal#1762]
I want to delete all candidates associated with a filter.  I identify those candidates using a GET api/candidates with query parameters.  The response does not have the candidate_id that I need to delete candidates.

**Comment by acrellin** [comment]
@AlexGKim thanks for the issue. There is a fix here: https://github.com/skyportal/skyportal/pull/1765  that will hopefully be merged today. The API will updated such that you can delete candidates via a DELETE request to `".../api/candidates/<obj_id>/<filter_id>"`
