### ISSUE TITLE
Allow "View only"-level users to be easily added via front-end

### ISSUE THREAD

**Issue by acrellin** [skyportal/skyportal#1769]
From Daniel Perley:

> it would be useful to give people the ability to scan/see transients from a program but not allow them to save/unsave to it, i.e. have different "tiers" of membership of a program (program owner, member with saving permission, guest without saving permission).  This would help us expand program membership without the concern that people will accidentally save/unsave objects.

To be clear, the back-end infrastructure is already in place, we just need to add an option to make users "View only" when inviting them.

**Comment by dmitryduev** [comment]
I think it would be useful if someone ever decide to spin up a public instance of SP/F (with a managed set of filters, for example) that you can query.GET, but not anything else. This is not high priority.
