### ISSUE TITLE
Add webhook that triggers on source changes 

### ISSUE THREAD

**Issue by stefanv** [skyportal/skyportal#177]
This is a meta-issue for tracking all webhook related changes.

Every time that a source is uploaded or modified through the API, webhooks should fire to let external services know.  Webhooks should be configurable in the user preferences.

This will allow for external computation (e.g., classification of objects) to happen on each object.

[SQLAlchemy](https://docs.sqlalchemy.org/en/13/orm/session_events.html) is able to generate events on all object insertions / modifications.

Related issues:

-
-

**Comment by dannygoldstein** [comment]
We have developed the machinery for this -- see #1124

**Comment by stefanv** [comment]
I think this issue is unrelated, so reopening.  This issue is for external webhooks.

**Comment by profjsb** [comment]
The functionality of this issue is seen in the Slack Integration (#2201)
