### ISSUE TITLE
Photometry plot updates place buttons over plot (reverted)

### ISSUE THREAD

**Issue by acrellin** [skyportal/skyportal#1774]

**Comment by kmshin1397** [comment]
Will be addressed in an update to #1759

**Comment by scizen9** [comment]
Has this been fixed with [#1778](https://github.com/skyportal/skyportal/pull/1778)?

**Comment by scizen9** [comment]
The fix PR [#1778](https://github.com/skyportal/skyportal/pull/1778) now been merged and deployed.
