### ISSUE TITLE
Ingest sources from a broker stream

### ISSUE THREAD

**Issue by stefanv** [skyportal/skyportal#178]
This is a meta-issue for tracking progress on stream ingestion.

Currently, we ingest sources via a) direct injection into the database or b) API POST calls.  We need to be able to ingest sources from a Kafka stream, like the ones that will be used by LSST and its broker network.

A test framework is provided by LSST in the [alert stream](https://github.com/lsst-dm/alert_stream) repository.  Alert schemas and example alerts live in the [sample-avro-alert](https://github.com/lsst-dm/sample-avro-alert/tree/master) repo.

For the demo, it may be fun to show the sources as they roll in.  In practice, we may only want to show a notification if a source you are looking at has received an update.

Related issues:

-

**Comment by dannygoldstein** [comment]
This is more or less done, we are doing this with ZTF via Kowalski on Fritz.
