### ISSUE TITLE
One candidate discovered by multiple filters not appearing on Candidates page with second Group

### ISSUE THREAD

**Issue by AlexGKim** [skyportal/skyportal#1791]
On the candidates page a candidate found by a filter does not appear when selected by that filter's group.  It was identified as a candidate by another filter and does appear when selected by that filter's group.

Backgrround:
We are ingesting ZTF candidates from multiple brokers (each a different filter).  Candidates cand_id are their ZTF name.  Brokers identify the same candidates and so have the same SkyPortal cand_id.  After the candidate is identified by one stream, how do we let it know it was identified by another stream?  When a candidate is created there is filter_ids, which can be an array.  I don't find an API in which the filter_ids are updated to reflect that the same candidate was discovered by a different filter.

**Comment by acrellin** [comment]
@AlexGKim You simply need to perform another POST request, specifying the same object ID, with the new filter_id

**Comment by acrellin** [comment]
(Each `(obj_id, filter_id)` pair corresponds to its own row in the candidates table)

**Comment by AlexGKim** [comment]
Yes indeed, sorry about the noise.

**Comment by acrellin** [comment]
No problem at all, happy to help.
