### ISSUE TITLE
Add option to turn on spectra vega plot to scanning page 

### ISSUE THREAD

**Issue by dannygoldstein** [skyportal/skyportal#1798]

**Comment by dmitryduev** [comment]
@scizen9 @guynir42 @rjoebruch @profjsb would this be a useful feature to have? Sound like potentially a lot of (unnecessary?) traffic to add to the Scanning page, which is pretty heavy already.

**Comment by rjoebruch** [comment]
at this stage, I don't think it's relevant to have spectroscopy on the scanning page (which is aimed at looking through new alerts, which don't have spectroscopy). 
In a search page, post-scanning, if one wants to filter candidates based on type, spectroscopy...etc, then there it could be relevant.

**Comment by dmitryduev** [comment]
I agree with @rjoebruch, so closing for now.
