### ISSUE TITLE
Race condition for creating tables on app startup

### ISSUE THREAD

**Issue by dannygoldstein** [skyportal/skyportal#1802]
When we start the app, there is a race condition in which each web worker attempts to create the same tables on the backend database. This can lead to collisions which can derail the app startup. The following example is from the CI  for 
https://github.com/skyportal/skyportal/pull/1801/checks?check_run_id=2154337250

app_00.log:
```
Could not connect to database...sleeping 3
  > (psycopg2.errors.DuplicateTable) relation "groups" already exists

[SQL: 
CREATE TABLE groups (
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	modified TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	name VARCHAR NOT NULL, 
	nickname VARCHAR, 
	private BOOLEAN NOT NULL, 
	single_user_group BOOLEAN, 
	PRIMARY KEY (id)
)

]
(Background on this error at: http://sqlalche.me/e/13/f405)
Creating tables on database skyportal
Could not connect to database...sleeping 3
  > (psycopg2.errors.DuplicateTable) relation "token_acls" already exists

[SQL: 
CREATE TABLE token_acls (
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	modified TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	id SERIAL NOT NULL, 
	token_id VARCHAR NOT NULL, 
	acl_id VARCHAR NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(token_id) REFERENCES tokens (id) ON DELETE CASCADE, 
	FOREIGN KEY(acl_id) REFERENCES acls (id) ON DELETE CASCADE
)

]
```

app_01.log:
```
Creating tables on database skyportal
Could not connect to database...sleeping 3
  > (psycopg2.errors.DuplicateTable) relation "role_acls" already exists

[SQL: 
CREATE TABLE role_acls (
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	modified TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	id SERIAL NOT NULL, 
	role_id VARCHAR NOT NULL, 
	acl_id VARCHAR NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(role_id) REFERENCES roles (id) ON DELETE CASCADE, 
	FOREIGN KEY(acl_id) REFERENCES acls (id) ON DELETE CASCADE
)

]
```

We should create tables on only one process, and block other processes until the table creation is done.

**Comment by stefanv** [comment]
I added a patch a while ago that makes the process number available to the app factory. If the patch is not on current master, I can make a PR.

**Comment by dannygoldstein** [comment]
I think there still may be a race condition in that case- if table creation is done on process 0, but process 1 does not wait for process 0 to finish creating tables before moving along with its code, there will still be a race in which process one could issue a query to the database on tables that do not exist yet, causing process one to raise a database exception. We need a synchronization step between the workers that creates a barrier to all processes until table creation is complete

**Comment by stefanv** [comment]
That's what migration manager is for. We may need to move some things in there.

**Comment by dannygoldstein** [comment]
Yes that sounds like a reasonable way forward. Block on all processes until migration manager initializes the DB.

**Comment by profjsb** [comment]
@stefanv can this be closed now, with the migration manager?

**Comment by stefanv** [comment]
This should do the trick: https://github.com/skyportal/skyportal/pull/2564
