### ISSUE TITLE
"max auth failure count reached"

### ISSUE THREAD

**Issue by AlexGKim** [skyportal/skyportal#1822]
I am getting the log output

`log/websocket_server.log:[10:12:48 websocket_server] max auth failure count reached`

I am curious what this means and if it is something I should be worrying about.

**Comment by stefanv** [comment]
This happens if the browser is unable to authenticate the websocket.  This could happen because the server secret key changed, or because the user is not authenticated to request a websocket token.  If it's happening often, we should take a look.  A browser refresh probably fixes it.
