### ISSUE TITLE
Query parameter radius units

### ISSUE THREAD

**Issue by AlexGKim** [skyportal/skyportal#1828]
In the documentation it would be useful to give the units for the query parameter radius in the source retrieval.  What is it BTW?

http://skyportal.io/docs/api.html#tag/sources/paths/~1api~1sources~1obj_id/patch

**Comment by acrellin** [comment]
Do you mean in the [GET](http://skyportal.io/docs/api.html#tag/sources/paths/~1api~1sources/get) docs? You linked to the PATCH handler. `ra`, `dec` and `radius` are all in decimal degrees. 

Addressed in https://github.com/skyportal/skyportal/pull/1829

**Comment by AlexGKim** [comment]
Great, this is addressed in that issue.  For some reason I didn't catch that one when I searched.
