### ISSUE TITLE
error when retrieving a source with null photometry point

### ISSUE THREAD

**Issue by AlexGKim** [skyportal/skyportal#1839]
I posted to Skyportal "None" as photometry for a source, it is accepted without error, but an error occurs when I retrieve the source.

In principle the fact that the photometry is None is interesting to me so I would prefer to post it.  Otherwise I can do a None check before posting and clean out the database of these photometry.

```
:32:17 -0700] "GET /api/sources/DESI39627817075347824 HTTP/1.1" 400 145 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36"
  File "/home/akim/miniconda3/envs/skyportal_env/lib/python3.8/site-packages/sqlalchemy/ext/hybrid.py", line 895, in __get__

    return self.fget(instance)
  File "/home/akim/skyportal/skyportal/models.py", line 776, in peak_detected_at
    return max(detections, key=(lambda x: x[1]))[0] if detections else None
TypeError: '<' not supported between instances of 'float' and 'NoneType'
[08:32:17 basehandler] Error response returned by [/api/sources/DESI39627817075347824]: ['<' not supported between instances of 'float' and 'NoneType']
WARNING:tornado.access:400 GET /api/sources/DESI39627817075347824 (127.0.0.1) 66.20ms
```

**Comment by acrellin** [comment]
@kmshin1397 did you recently refactor peak_detected_at? Wondering if the changes there could be related

**Comment by acrellin** [comment]
I think we just need to filter out photometry whose mag value is `None` here https://github.com/skyportal/skyportal/blob/master/skyportal/models.py#L794

**Comment by acrellin** [comment]
@AlexGKim can you confirm that in `config.yaml` there is a valid number specified for `photometry_detection_threshold_nsigma` (under the `misc` section)?

**Comment by kmshin1397** [comment]
I did refactor it recently, but not sure how it could've led to this error as I kept this `is not None` checks in there at
https://github.com/skyportal/skyportal/blob/38f0c7b93f36e8a93e3934a2d9999c305a6b16ac/skyportal/models.py#L781
https://github.com/skyportal/skyportal/blob/38f0c7b93f36e8a93e3934a2d9999c305a6b16ac/skyportal/models.py#L793

but maybe those aren't working as intended now for whatever reason. I'll look into it.

**Comment by kmshin1397** [comment]
ah 

> @AlexGKim can you confirm that in `config.yaml` there is a valid number specified for `photometry_detection_threshold_nsigma` (under the `misc` section)?

Yeah good idea, that could explain the error

**Comment by AlexGKim** [comment]
@acrellin , it is set to a valid number

`  photometry_detection_threshold_nsigma: 3.0`

**Comment by acrellin** [comment]
@AlexGKim I am unable to reproduce. Can you please provide a complete code sample showing the exact requests needed to reproduce this issue? Thanks

**Comment by AlexGKim** [comment]
I get an error with this `http://desi2.lbl.gov:5000/source/DESI39633006406667894`

Here is a screen shot

![Uploading image.png…]()

**Comment by acrellin** [comment]
@AlexGKim I do not have access to that endpoint and the image was not successfully attached.

**Comment by AlexGKim** [comment]
![image](https://user-images.githubusercontent.com/880156/114104464-bf23e000-987f-11eb-8fe1-1021bd41a48c.png)

You should (?!) now have permissions to access that endpoint.

**Comment by acrellin** [comment]
@AlexGKim can you please tell me what the latest commit from SkyPortal
master you have deployed? The commit you're running doesn't appear to be
from our repo, so I don't know where your branch is in relation to the
latest master.

**Comment by AlexGKim** [comment]
@acrellin . I think it is 989e524

**Comment by acrellin** [comment]
@AlexGKim Thanks for the info. What would be most helpful is the request that was performed in order to post the photometry in question. You said you posted "None" for photometry, but there are a variety of things that could mean -- seeing the actual request (API call) would be very helpful to be able to figure out what's going on. Thanks.

**Comment by acrellin** [comment]
@AlexGKim I think I found the issue. It appears that you provided a negative `fluxerr` value when you POSTed the offending photometry point. We will update the handler to only allow positive values.

**Comment by acrellin** [comment]
@AlexGKim It appears the offending photometry record has an ID of `2408556`. In order to fix the issue for your instance, we just need to patch that record, providing `0.010508826627780025` as the value of `fluxerr` to replace the current `-0.010508826627780025`. Would you like me to go ahead and change that on your deployment, or would you like to do the patch yourself?

**Comment by AlexGKim** [comment]
I will try and let you know if I run into any roadblocks.

**Comment by AlexGKim** [comment]
Success, thanks!

**Comment by acrellin** [comment]
Great to hear!
