### ISSUE TITLE
Feature request "in front' spectra

### ISSUE THREAD

**Issue by AlexGKim** [skyportal/skyportal#1844]
Currently when there are multiple spectra plotted, the "in front" ordering is fixed.  I would like to control the "in front" ordering.  One way to do this is through the order of toggling of spectra visibility.

**Comment by guynir42** [comment]
I'm not sure what exactly is needed here. Is toggling the spectra visibility now working or is that the way you'd like to see this work?

**Comment by AlexGKim** [comment]
The issue is that when multiple spectra are shown, one cannot control the plotting sequence, i.e. which spectrum is on top and which spectra are overplotted.

**Comment by guynir42** [comment]
And you'd like to be able to pick one out to be on top by clicking on it?

**Comment by AlexGKim** [comment]
A "bring to front" behavior is a solution though I am open to others.

**Comment by guynir42** [comment]
OK I will think about how we can do that.
