### ISSUE TITLE
source get non-existent origin returning objects

### ISSUE THREAD

**Issue by AlexGKim** [skyportal/skyportal#1852]
The following query

```
http://desi2.lbl.gov:5000/api/sources?startDate=2021-04-06&origin=ANTARES
HTTP code: 200, OK
```

returns objects even though there are no sources with origin ANTARES.

An example output has

```
{'totalMatches': 264,
 'sources': [{'ra_err': None,
   'created_at': '2020-11-25T18:36:54.439532',
   'transient': True,
   'dec_err': None,
   'modified': '2020-11-25T18:36:54.439532',
   'varstar': False,
   'offset': 0.0,
   'ra': 93.1739727,
   'is_roid': False,
   'redshift': None,
   'dec': 58.9194678,
   'score': 0.999989986419678,
   'redshift_history': None,
   'id': 'ZTF19aaaitgl',
   'origin': 'Ampel',
```

Note the origin is not ANTARES.

**Comment by kmshin1397** [comment]
Hi @AlexGKim I believe we don't actually support filtering on the origin for the sources query, so that part would just be ignored and only the `startDate` taken into account. That can certainly be added in if it's a feature you need.

**Comment by AlexGKim** [comment]
Sorry about that, my mistake.  Not a needed feature.
