### ISSUE TITLE
Feature: ability to add annotations from the Source page

### ISSUE THREAD

**Issue by dmitryduev** [skyportal/skyportal#1856]
This would be useful for, e.g. manually adding info on period or Gaia color.

I would add an "Add annotation" button that would bring up a popup window where you can add (potentially) multiple {key: value} pairs (so there will be a "+" button to add new rows). Alternatively, can do it similar to e.g. comments with inline stuff.

@guynir42 @scizen9 would any of you guys volunteer for this?

**Comment by dmitryduev** [comment]
Since the result will most likely have a Submit button, I would tackle https://github.com/skyportal/skyportal/issues/916 as a part of  this effort.

**Comment by dmitryduev** [comment]
Default origin to username; do a pop-up.

**Comment by acrellin** [comment]
Add button to periodogram page to save period as annotation.

**Comment by guynir42** [comment]
Split this issue into specific annotations that can be added from the frontend, e.g., period.
