### ISSUE TITLE
QueuePool limit of size 5 overflow 10 reached

### ISSUE THREAD

**Issue by AlexGKim** [skyportal/skyportal#1886]
I am getting this error message.  

I```
NFO:sp_utils.py:173:postCandidate: HTTP code: 400, Bad Request
JSON response: {'status': 'error', 'message': 'QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30 (Background on this error at: http://sqlalche.me/e/3o7r)', 'data': {}, 'version': '0.9.dev0+git%aI.40fc611'}
```

There has been a significant uptick in the usage of our SkyPortal instantiation.  Any recommendations on to resolve this?

**Comment by stefanv** [comment]
We patched this today. Please make sure you run the current version, and let us know if the error persists.

**Comment by stefanv** [comment]
Apparently, this may not have been addressed completely. We will keep investigating.

**Comment by dmitryduev** [comment]
Looks like we solved this, but feel free to reopen should this come up again.
