### ISSUE TITLE
enable debug mode on travis

### ISSUE THREAD

**Issue by dannygoldstein** [skyportal/skyportal#189]
I am getting some complex errors from travis trying to build Q3C. Can you please enable debug mode in travis so I can debug them interactively?

Thanks,
Danny

**Comment by stefanv** [comment]
I can do that, but will have to email the support team.


Can q3c not be installed as a package?

**Comment by dannygoldstein** [comment]
cc @segasai

**Comment by stefanv** [comment]
This one: https://packages.ubuntu.com/bionic/postgresql-q3c

We can upgrade our version of Postgres on Travis-CI to 10, if that would help.

**Comment by dannygoldstein** [comment]
sounds good to me, what about on mac though?

**Comment by stefanv** [comment]
No such option on MacOS, you're right.

So, this is where it gets a bit hairy.  I'm still leaning towards detecting q3c and using it when it is installed, or skipping it otherwise.  If not, we are going to add a complicated additional installation step for everyone who just wants to try it out.

**Comment by dannygoldstein** [comment]
Closing as we have moved away from q3c toward https://github.com/skyportal/healpix-alchemy.
