### ISSUE TITLE
Make candidate list end time default to now

### ISSUE THREAD

**Issue by ofek-b** [skyportal/skyportal#1890]
We at the SN Working Group scanning using Fritz would like to have the time range on the candidate page default to: (now - 24h) up until (now). Currently, lower bound is usually there, but upper bound needs to be set manually.

![image](https://user-images.githubusercontent.com/53834911/115137511-45ce7f00-a02f-11eb-813e-84aadaee35f9.png)

**Comment by acrellin** [comment]
Hi @ofek-b, did you know that you can leave that blank? No candidates can have a date in the future, so leaving it blank translates to "everything up to right now."

**Comment by acrellin** [comment]
Closing as irrelevant / stalled
