### ISSUE TITLE
Display spinner in source tables while data is loading

### ISSUE THREAD

**Issue by dmitryduev** [skyportal/skyportal#1911]
...otherwise at first it looks like there's nothing there; the lag seems too long to not bother.

**Comment by guynir42** [comment]
@dmitryduev I'm not sure where you want the spinner? 
In the Sources tab there is a spinner before the table comes up.

**Comment by dmitryduev** [comment]
@guynir42 while stuff is loading into the sources table, it shows up simply as an empty table giving a false sense of absent results. The same applies when you apply a filter or sort by a column.

**Comment by guynir42** [comment]
@dmitryduev I'm not seeing this. When I open the source table (locally or on Fritz) I see a spinner and after the table loads it already has data in it. 
Maybe I am missing something?

**Comment by acrellin** [comment]
Guy, try submitting a query that filters by classification. When I do this,
nothing happens for a few seconds, then the table suddenly is updated.
During those few seconds, we should show the spinner.

**Comment by guynir42** [comment]
@acrellin when you say nothing happens, you mean the data from the last query is still there and doesn't change until a few seconds go by? (I was thinking there's a blank screen or something)

**Comment by acrellin** [comment]
Yes, that.

**Comment by acrellin** [comment]
It should behave like the scanning page. (can probably be mostly copy
pasted from there - queryInProgress)
