### ISSUE TITLE
Add section on spectral lines to the docs

### ISSUE THREAD

**Issue by dmitryduev** [skyportal/skyportal#1914]
...with references - where did all those come from etc.?
I'd put it under Advanced Usage.

@rjoebruch would you mind taking this on?

**Comment by rjoebruch** [comment]
will do, thanks

**Comment by stefanv** [comment]
@rjoebruch Just checking in to see whether you were able to make progress on this.

**Comment by rjoebruch** [comment]
changed wording from the one in may : https://github.com/skyportal/skyportal/pull/2276
