### ISSUE TITLE
`sources_table_empty` is for frontend only

### ISSUE THREAD

**Issue by stefanv** [skyportal/skyportal#193]
Remove from `/api/sysinfo` into private API.

**Comment by acrellin** [comment]
@stefanv do you want there to be a separate endpoint for this? `/api/internal/sources_table_empty`?

**Comment by stefanv** [comment]
Sure, anything `/internal/` works.  But, do we really need to know this?  We can also check if the user has access to >= 1 source, and that should accomplish the same.  Not sure whether there is a *cheap* way of doing that in the database, though, although this seems to be exactly what we'd need:

https://stackoverflow.com/questions/6587879/how-to-elegantly-check-the-existence-of-an-object-instance-variable-and-simultan
