### ISSUE TITLE
Database fields match documentation, but API expects different names

### ISSUE THREAD

**Issue by stefanv** [skyportal/skyportal#194]
Use marshmallow-sqlalchemy to make these the same.

**Comment by acrellin** [comment]
@stefanv shall I tack this onto the stream ingest PR, or wait til that's merged to do this (I anticipate merge conflicts if doing it separately before that merge)

**Comment by stefanv** [comment]
On Thu, 20 Jun 2019 11:41:03 -0700, Ari Crellin-Quick wrote:
> @stefanv shall I tack this onto the stream ingest PR, or wait til
> that's merged to do this (I anticipate merge conflicts if doing it
> separately before that merge)

The merge conflicts shouldn't be too bad, I hope.  But you can also
start a new branch based off the current PR, if you think that'd help.
