### ISSUE TITLE
api error

### ISSUE THREAD

**Issue by dannygoldstein** [skyportal/skyportal#199]
I uncommented the get method of the Photometry handler:

```   @auth_or_token
    def get(self, source_id=None):
        if source_id is not None:
            info = Photometry.get_if_owned_by(source_id, self.current_user,
                                              options=joinedload(Photometry.comments)
                                              .joinedload(Comment.user))
        else:
            info = list(self.current_user.sources)

        if info is not None:
            return self.success(info)
        else:
            return self.error(f"Could not load source {source_id}",
                              {"source_id": source_id})
```

I generated a token with no ACLS, then sent a request using that token to get the photometry of an example object. I get the following error:

In [42]: r=requests.get('http://localhost:5000/api/photometry', headers=
    ...: header, params={'source_id': 'SDSSJ1313+5151'})

In [43]: r.content
Out[43]: b'{"status": "error", "message": "\'Token\' object has no attribute \'sources\'", "data": {"version": "0.9"}}'

**Comment by stefanv** [comment]
Excellent; thanks for catching this.  It should be a trivial fix, so I hope Ari can get it squared away for you on monday.  We'll also add a test to the API test suite to make sure this doesn't happen again.

**Comment by acrellin** [comment]
@dannygoldstein thanks for the issue. This was commented out because it was never actually fully implemented in the first place - it was just a placeholder. Closed in favor of https://github.com/skyportal/skyportal/issues/201
