### ISSUE TITLE
Slow cone search that breaks down near celestial poles

### ISSUE THREAD

**Issue by dannygoldstein** [skyportal/skyportal#200]
The cone search functionality on the homepage is currently quite slow, I have a database with ~7.2k sources and have been waiting on this query for almost five minutes:

<img width="724" alt="Screen Shot 2019-06-22 at 2 05 22 PM" src="https://user-images.githubusercontent.com/2769632/59968904-d2bd5580-94f6-11e9-8553-c1b67a59fa3e.png">

The handler for these queries is as follows:

        if data['ra'] and data['dec'] and data['radius']:
            ra = float(data['ra'])
            dec = float(data['dec'])
            radius = float(data['radius'])
            q = q.filter(Source.ra <= ra + radius)\
                 .filter(Source.ra >= ra - radius)\
                 .filter(Source.dec <= dec + radius)\
                 .filter(Source.dec >= dec - radius)

Two problems here: 

1. No spatial indexing backend (i.e., q3c) means that the search needs to perform a full scan of the table (slow)

2. RA and DEC are spherical angular coordinates so the above query does not work for cone searching, especially near the poles (DEC=90, -90). Imagine you want to get all sources within 10 degrees of DEC=90 (the north pole). The above query would set limits of DEC=100 (a nonexistent coordinate) and DEC=80, and probably only for some tiny patch of RA. This would not be the right area to search for matching sources

Issues like this are why a spatial indexer that handles spherical angular queries (like q3c) is needed.

Danny

**Comment by dannygoldstein** [comment]
This is a critical bug

**Comment by stefanv** [comment]
@acrellin I am out for a few days; can you help @dannygoldstein to get q3c integrated and this addressed?

@acrellin As I mentioned on the other issue, my preference would be to use q3c if it is already installed.  This would keep installation for easy for those who simply want to try it, but will give speed improvements for those who want to use this in production.  The installation instructions would show how to install q3c and emphasize that this increases lookup speeds.

**Comment by dannygoldstein** [comment]
Fixed by #554
