### ISSUE TITLE
Candidates POST request times out causing data loader to crash

### ISSUE THREAD

**Issue by acrellin** [skyportal/skyportal#2000]
```
Posting to candidates: X
Traceback (most recent call last):
  File "tools/data_loader.py", line 240, in <module>
    error_log.append(f"/{endpoint}: {response['message']}")
TypeError: 'NoneType' object is not subscriptable
make: *** [Makefile:59: load_demo_data] Error 1
```
This has been cropping up here and there over the past few days.

**Comment by acrellin** [comment]
I've seen this locally, @scizen9 has as well, and we've been seeing this happen on GA

**Comment by stefanv** [comment]
This means that `response` is None.

**Comment by acrellin** [comment]
Right, and the logs show `504` -- no recent changes to that handler, though, and I'm seeing this very consistently locally now.

**Comment by stefanv** [comment]
504 probably does not have a body, so we need to fix:

https://github.com/skyportal/skyportal/blob/master/tools/data_loader.py#L116

**Comment by acrellin** [comment]
No longer seeing this
