### ISSUE TITLE
Run the CI daily to catch potential external-stuff-related issues early

### ISSUE THREAD

**Issue by dmitryduev** [skyportal/skyportal#2017]
...such as broken dependencies, for example. Doesn't have to be the complete suite, maybe just a subset thereof.

Add 
```
schedule:
  - cron: '* 12 * * *'
```

or something to the GHA workflow defs?

**Comment by guynir42** [comment]
@profjsb do you think this is still relevant?

**Comment by mcoughlin** [comment]
We run the CI almost daily anyways, I think we can close for now.
