### ISSUE TITLE
candidate not showing up in candidate scanning page

### ISSUE THREAD

**Issue by AlexGKim** [skyportal/skyportal#2043]
The candidate below is associated with the filter DESITRIP (filter_id=17) but does not appear in `http://desi2.lbl.gov:5000/candidates` with DESITRIP selected and dates that cover its creation.

`http://desi2.lbl.gov:5000/api/candidates/DESI39627794325440376`

> {
>   "status": "success",
>   "data": {
>     "dec_dis": null,
>     "detect_photometry_count": null,
>     "e_mag_nearest_source": null,
>     "ra_err": null,
>     "created_at": "2021-05-29T20:03:34.433121",
>     "transient": false,
>     "dec_err": null,
>     "modified": "2021-06-01T22:42:21.062117",
>     "varstar": false,
>     "offset": 0.0,
>     "ra": 212.08919011081935,
>     "is_roid": false,
>     "redshift": 0.134008165060054,
>     "dec": 0.22087949164204737,
>     "score": null,
>     "redshift_history": [
>       {
>         "value": 0.134008165060054,
>         "set_at_utc": "2021-05-29T20:03:34.484107",
>         "set_by_user_id": 384
>       },
>       {
>         "value": 0.134008165060054,
>         "set_at_utc": "2021-05-30T19:02:30.231583",
>         "set_by_user_id": 384
>       },
>       {
>         "value": 0.134008165060054,
>         "set_at_utc": "2021-05-31T19:02:36.880010",
>         "set_by_user_id": 384
>       },
>       {
>         "value": 0.134008165060054,
>         "set_at_utc": "2021-06-01T22:42:21.101687",
>         "set_by_user_id": 384
>       }
>     ],
>     "id": "DESI39627794325440376",
>     "origin": null,
>     "altdata": {
>       "fibermap": {
>         "FIBER": "2201",
>         "TILEID": "525",
>         "LAST_MJD": "59337.332",
>         "PETAL_LOC": "4"
>       },
>       "classifier": {
>         "CNNLABEL": "SN IIn"
>       }
>     },
>     "ra_dis": null,
>     "internal_key": "49e054d2-dfe1-46a8-b53c-4e1bafee16b5",
>     "dist_nearest_source": null,
>     "mag_nearest_source": null,
>     "thumbnails": [
>       {
>         "modified": "2021-05-29T20:03:34.580027",
>         "id": 150903,
>         "obj_id": "DESI39627794325440376",
>         "public_url": "https://skyserver.sdss.org/dr12/SkyserverWS/ImgCutout/getjpeg?ra=212.08919011081935&dec=0.22087949164204737&scale=0.3&width=200&height=200&opt=G&query=&Grid=on",
>         "type": "sdss",
>         "created_at": "2021-05-29T20:03:34.580027",
>         "is_grayscale": false,
>         "origin": null,
>         "file_uri": null
>       },
>       {
>         "modified": "2021-05-29T20:03:34.580027",
>         "id": 150904,
>         "obj_id": "DESI39627794325440376",
>         "public_url": "https://www.legacysurvey.org/viewer/jpeg-cutout?ra=212.08919011081935&dec=0.22087949164204737&size=200&layer=dr8&pixscale=0.262&bands=grz",
>         "type": "dr8",
>         "created_at": "2021-05-29T20:03:34.580027",
>         "is_grayscale": false,
>         "origin": null,
>         "file_uri": null
>       },
>       {
>         "modified": "2021-06-01T23:07:07.080273",
>         "id": 153280,
>         "obj_id": "DESI39627794325440376",
>         "public_url": "http://ps1images.stsci.edu/cgi-bin/fitscut.cgi?red=/rings.v3.skycell/1375/004/rings.v3.skycell.1375.004.stk.i.unconv.fits&blue=/rings.v3.skycell/1375/004/rings.v3.skycell.1375.004.stk.g.unconv.fits&green=/rings.v3.skycell/1375/004/rings.v3.skycell.1375.004.stk.r.unconv.fits&x=212.089190&y=0.220879&size=250&wcs=1&asinh=True&autoscale=99.750000",
>         "type": "ps1",
>         "created_at": "2021-06-01T23:07:07.080273",
>         "is_grayscale": false,
>         "origin": null,
>         "file_uri": null
>       }
>     ],
>     "filter_ids": [
>       17,
>       17,
>       17,
>       17
>     ],
>     "passing_alerts": [
>       {
>         "filter_id": 17,
>         "passing_alert_id": 17,
>         "passed_at": "2021-05-28T17:00:00"
>       },
>       {
>         "filter_id": 17,
>         "passing_alert_id": 17,
>         "passed_at": "2021-05-29T17:00:00"
>       },
>       {
>         "filter_id": 17,
>         "passing_alert_id": 17,
>         "passed_at": "2021-05-30T17:00:00"
>       },
>       {
>         "filter_id": 17,
>         "passing_alert_id": 17,
>         "passed_at": "2021-05-31T17:00:00"
>       }
>     ],
>     "annotations": [],
>     "is_source": false,
>     "last_detected_at": null,
>     "gal_lon": 340.56863631567563,
>     "gal_lat": 57.36078099261442,
>     "luminosity_distance": 651.8167816745546,
>     "dm": 39.07062768809296,
>     "angular_diameter_distance": 506.86601665633924
>   },
>   "version": "0.9.dev0+git%aI.e510c6c"
> }

`http://desi2.lbl.gov:5000/api/filters/17`

> {
>   "status": "success",
>   "data": {
>     "name": "DESITRIP",
>     "created_at": "2021-01-11T21:57:32.081506",
>     "stream_id": 5,
>     "modified": "2021-03-15T22:50:33.701009",
>     "id": 17,
>     "group_id": 23
>   },
>   "version": "0.9.dev0+git%aI.e510c6c"
> }

![image](https://user-images.githubusercontent.com/880156/120402075-272dfa00-c2f6-11eb-809f-cf94805edc9f.png)

**Comment by acrellin** [comment]
Hi @AlexGKim , can you confirm that it has not been hidden / rejected previously?

**Comment by AlexGKim** [comment]
I turned on "Show rejected candidates' and the candidate still does not appear.

**Comment by acrellin** [comment]
@AlexGKim I'm unable to reproduce and might need to inspect your particular DB instance to figure out what's going on

**Comment by AlexGKim** [comment]
I can tmate when you are available.

**Comment by acrellin** [comment]
@AlexGKim the issue is that the your DESITRIP filter is not actually associated with your DESITRIP group: 
``` python
>>> g = Group.query.filter(Group.name == "DESITRIP").first()                    
>>> g                                                                           
<Group(id=78, created_at=2021-03-15 22:39:47.334469, modified=2021-03-15 22:39:47.334469, name=DESITRIP, nickname=DESITRIP, private=False, single_user_group=False)>                                                                            
>>> g.streams                                                                   
[]                                                                              
>>> g.filters                                                                   
[]                                                                              
```

**Comment by acrellin** [comment]
You'll need to add the relevant stream(s) and filter to your DESITRIP group on the group page

**Comment by AlexGKim** [comment]
I have just added the stream and filter to the group page but still do not pick up the candidates.  Does this not work retroactively?

**Comment by acrellin** [comment]
Yes, it should work retroactively as long as the correct filter is associated with the group. I can take another look to ensure it was added properly

**Comment by AlexGKim** [comment]
I have figured out that the root of the problem was that I had two filters with identical names but belonging to different groups.  I will try to recover from this badness.

**Comment by acrellin** [comment]
@AlexGKim Glad you were able to find and address the cause of the issue. Please let us know if any other issues arise
