### ISSUE TITLE
Minimizing Comments Section breaks page layout

### ISSUE THREAD

**Issue by sehgalvibhor** [skyportal/skyportal#209]
Comments section flows to the top after it's collapsed, and returns back to the bottom on expanding.

### **Initial Layout:**
![image](https://user-images.githubusercontent.com/10993808/62323923-0318ec00-b4c6-11e9-8045-3f7d042b11e4.png)

### **After Comments Section is minimized/closed:** 

![image](https://user-images.githubusercontent.com/10993808/62324010-36f41180-b4c6-11e9-96af-53a2d968c6f5.png)

**Comment by acrellin** [comment]
Hi @sehgalvibhor, thanks for the note.  I am unable to reproduce this running the latest master.  Can you please tell us which browser (including version number) you're using so we can try to reproduce and debug this?  

Thanks!

**Comment by stefanv** [comment]
There is different layout for mobile and desktop.  Your browser must be *just* the right width to trigger folding when the comments box is expanded (when I imagine it is a tiny bit wider than before).

**Comment by sehgalvibhor** [comment]
@acrellin : Apologies, I should have mentioned the browser while logging this issue. I am on latest master and running Firefox 65.0, Ubuntu 18 . I am noticing this issue while checking the responsiveness of the page, the break point to notice the issue is 1268px width. Comment section jumps to top!

At 1266 px width:
![image](https://user-images.githubusercontent.com/10993808/62343898-7b54d100-b509-11e9-872e-ba99f30f22b6.png)

At 1268 px width:
![image](https://user-images.githubusercontent.com/10993808/62344310-1bf7c080-b50b-11e9-801b-fd8dca7fa624.png)

**Comment by acrellin** [comment]
Minimizing/maximizing changes the comments section div's width, which, depending on the browser window size, might make it move to below the plots so that it doesn't run off the edge of the page. I don't think this is an issue.
