### ISSUE TITLE
Comments Table for the GcnEvent table

### ISSUE THREAD

**Issue by mcoughlin** [skyportal/skyportal#2131]
Currently we can only add comments ultimately tied to objects. The events do not necessarily have any objects tied to them.

**Comment by guynir42** [comment]
Will do this as soon as the comments API reordering gets merged.

**Comment by mcoughlin** [comment]
@guynir42 can you remember what we decided about this? Was the plan to refactor the comments class so it can be used for more than just objects and spectra?

**Comment by guynir42** [comment]
@mcoughlin yes this is implemented for spectrum comments. The way it works is there's a CommentMixin class that is inherited by each type of comment: regular comment (on an Obj), CommentOnSpectrum and I will need to add another CommentOnGCN table. It should be fairly straightforward to do.

**Comment by mcoughlin** [comment]
Ok thanks @guynir42 !
