### ISSUE TITLE
Sign-in method alternative to Google

### ISSUE THREAD

**Issue by simeonreusch** [skyportal/skyportal#2144]
I would love if I could sign in to Fritz NOT using my google account. Generally, I avoid being tracked across the internet, and this includes not signing in to Google.

**Comment by stefanv** [comment]
@simeonreusch That should be quite easy to add; we use Python Social Auth which has [these backends](https://python-social-auth.readthedocs.io/en/latest/backends/index.html)

**Comment by simeonreusch** [comment]
This would make me VERY happy :-)

**Comment by simeonreusch** [comment]
Though I would suggest hosting the auth yourselves?

**Comment by stefanv** [comment]
@simeonreusch We are simply delegating the authentication process so we don't have to keep a password database.  But PSA does allow for a password store.

**Comment by simeonreusch** [comment]
I just think you should keep one. What do you mean with PSA?

**Comment by stefanv** [comment]
Python Social Auth.  Are you asking for a private deployment or an existing one?

**Comment by simeonreusch** [comment]
I am asking for Fritz.

**Comment by stefanv** [comment]
No problem; do you mind filing this on https://github.com/fritz-marshal/fritz-beta-feedback/ ?  Thanks!
