### ISSUE TITLE
Add "favorite" star button to each source row in `SourceTable`

### ISSUE THREAD

**Issue by acrellin** [skyportal/skyportal#2156]

**Comment by guynir42** [comment]
@acrellin I'm not sure what you mean. There is a column for favorites in the sources table...

**Comment by guynir42** [comment]
@acrellin just pinging this again...

**Comment by acrellin** [comment]
@guynir42 yep, it's rendering fine now. For some reason this wasn't showing up at some point, but seems fine now. Closing.
