### ISSUE TITLE
Error when expanding row of Sources table

### ISSUE THREAD

**Issue by kmshin1397** [skyportal/skyportal#2194]
![Screenshot 2021-08-10 173104.png](https://images.zenhubusercontent.com/5fa07a8dad5a55e4068346f4/609899a0-be51-42e6-b562-6000615806ce)

I was browsing on a view-only user account and saw this when I tried to expand the first row on the Sources page data table. Probably just need to add a `?` somewhere in the JSX.

**Comment by acrellin** [comment]
I believe this was addressed in https://github.com/skyportal/skyportal/pull/2285
