### ISSUE TITLE
PDF file preview and download in comments not working

### ISSUE THREAD

**Issue by dmitryduev** [skyportal/skyportal#2214]
It says "Failed to load PDF file."
The endpoint that it tries to hit looks like `https://fritz.science/api/comment/65728/attachment/object.pdf`, but that throws an error saying that it's an invalid API endpoint. Hitting `https://fritz.science/api/comment/65728/attachment/` grabs the correct file.

**Comment by dmitryduev** [comment]
@scizen9 would you like to take this one on? I recall you/@stefanv dealt with a similar issue recently...

**Comment by scizen9** [comment]
When I try to use the second URL above, it still gives an error.  If I replace 'object.pdf' with 'ztf21abubpng_full_fps_mags.pdf' it also gives an error.  Could this be the special pdf handling problem?  SEDM has been uploading loads of png files to comments and they display/download fine.
