### ISSUE TITLE
Update state upon successful spectrum upload

### ISSUE THREAD

**Issue by dmitryduev** [skyportal/skyportal#2218]
We should be updating the app state upon a successful spectrum upload for a given object.

To reproduce the behavior that is confusing to the users:
- Go to any source page
- Upload additional spectroscopy -> upload a spectrum
- Once the app declares success, click on the object name at the top of the page to go back to the Source page
- The newly uploaded spectrum will not be displayed under Spectroscopy *unless the page is refreshed*

**Comment by guynir42** [comment]
will be fixed by #2248
