### ISSUE TITLE
Uncaught exception in `get_effective_wavelength`

### ISSUE THREAD

**Issue by stefanv** [skyportal/skyportal#2249]
```
  File "/skyportal/skyportal/handlers/api/internal/plot.py", line 33, in get
    json = plot.photometry_plot(
  File "/skyportal/skyportal/plot.py", line 508, in photometry_plot
    data['effwave'] = [get_effective_wavelength(f) for f in data['filter']]
  File "/skyportal/skyportal/plot.py", line 508, in <listcomp>
    data['effwave'] = [get_effective_wavelength(f) for f in data['filter']]
  File "/skyportal/skyportal/plot.py", line 318, in get_effective_wavelength
    raise ValueError(
ValueError: Could not get bandpass for uvot::uvm2 due to sncosmo error: zero-size array to reduction operation maximum which has no identity
```

**Comment by bparazin** [comment]
I feel like this is one I could work on as well? Do you remember what obj_id this occurred for?

**Comment by stefanv** [comment]
It looks like this is an sncosmo error when it cannot download a data file and subsequently creates an empty data file.

They say they fixed it in 2017, but apparently not.  See also https://github.com/skyportal/skyportal/pull/2094

What you can do is to put a `try/except` around every invocation of this function, and handle it gracefully when it doesn't return.  Or, we can ignore this for now and see whether it comes up agian.

**Comment by bparazin** [comment]
![image](https://user-images.githubusercontent.com/56836732/134687586-9c31c5cc-52c1-41b0-ae11-4e676dd605db.png)
Hmmm, yeah. It looks like #2094 already added a try/except like you mentioned, and I'm not sure there is much else we can do about this one since the issue is in sncosmo.
