### ISSUE TITLE
Image comparison testing approach fails because of difference in fonts

### ISSUE THREAD

**Issue by stefanv** [skyportal/skyportal#2250]
Our image comparison approach is flawed in that it does not account for differences in system fonts and rendering.

Here are the test images rendered on my machine, compared to the ones in the repo.

![centroid_plot_expected_my](https://user-images.githubusercontent.com/45071/132934541-275c0df9-94bb-4c1d-b838-42c21f8080d4.png)
![centroid_plot_expected](https://user-images.githubusercontent.com/45071/132934542-fbb1cf90-8182-4198-85d9-92ea7564e909.png)

![HR_diagram_expected_my](https://user-images.githubusercontent.com/45071/132934544-795ef802-5a5b-471a-9f9c-6a6a5370c78f.png)
![HR_diagram_expected](https://user-images.githubusercontent.com/45071/132934547-3558bed5-ba8a-48f5-a9d0-c538efc686f4.png)

**Comment by acrellin** [comment]
@stefanv Where is this causing test errors? Locally or on CI? We only store those images in the repo that work against the CI test runner (different viewport size that when running locally). Closing for now, feel free to reopen if necessary.
