### ISSUE TITLE
SDSS and DR8 thumbnails don't always get created

### ISSUE THREAD

**Issue by dmitryduev** [skyportal/skyportal#2254]
This happens when running `make load_demo_data`: since that now happens asynchronously and we kill the process once the serial part is complete, probably we just don't wait long enough for them to be fetched and saved.

Also, as I've noticed, when the app is under heavy load, this could also happen in production.

**Comment by stefanv** [comment]
We should look into implementing something like [this](https://gist.github.com/wonderbeyond/d38cd85243befe863cdde54b84505784) from [this thread](https://github.com/tornadoweb/tornado/issues/1791#issuecomment-596265013) thread.

**Comment by dmitryduev** [comment]
Addressed in #2255, closing.
