### ISSUE TITLE
Center spinner in viewport

### ISSUE THREAD

**Issue by profjsb** [skyportal/skyportal#2290]
Throughout the app, when the app is pulling data/updating state, we show a spinner which is centered (vertically and horizontally) in the viewport (desktop and mobile). Right now, the spinner generally appears in the top left. There are currently 7 places where spinners are used:

```bash
egrep -r  "spinner" ./static/js/components/
./static/js/components//UnSourcedFindingChart.jsx:  spinner: {
./static/js/components//SourceList.jsx:  spinner: {
./static/js/components//CandidateList.jsx:          className={classes.spinnerDiv}
./static/js/components//UserInvitations.jsx:        className={classes.spinnerDiv}
./static/js/components//FindingChart.jsx:    <div className={classes.spinner}>
./static/js/components//Periodogram.jsx:                    <div className={classes.spinner}>
./static/js/components//UserManagement.jsx:        className={classes.spinnerDiv}
```

**Comment by dmitryduev** [comment]
https://skyportal.io/docs/adding_features.html

**Comment by avngzy** [comment]
![Screenshot 2021-11-16 at 12 16 35 AM](https://user-images.githubusercontent.com/65587962/141931873-b9f41007-acfb-4365-8316-e51ec2d579ee.png)

Is this your definition of centering?

**Comment by acrellin** [comment]
@avngzy We'd also like it to be vertically centered. Thanks!

**Comment by avngzy** [comment]
![Screenshot 2021-11-18 at 10 16 34 PM](https://user-images.githubusercontent.com/65587962/142564043-fbe2faf9-5f97-4399-b84c-41a22944cbf6.png)
Hi @acrellin , does this look better?

**Comment by stefanv** [comment]
Yes, that looks great @avngzy

**Comment by acrellin** [comment]
Yep, looks good!

**Comment by acrellin** [comment]
@avngzy Can you please open a PR with these changes? Looks good so far. Thanks

**Comment by avngzy** [comment]
Created PR #2475
