### ISSUE TITLE
Sort photometry by "last detected" etc.

### ISSUE THREAD

**Issue by guynir42** [skyportal/skyportal#2298]
We could improve the speed of queries loading many sources and filtering them by "last detected" or similar properties. 

Right now to sort on "last detected" we load all relevant objects and for each object load all accessible photometry points. Then for each point we calculate if it was detected or not and then sort by detection time. 

Instead we could add some indices that let us filter out photometry points that were detected after some date, and then test of a source has any qualifying photometry points. This should lead to some speedups.

**Comment by acrellin** [comment]
@guynir42 can you expand on what the index would consist of?

**Comment by guynir42** [comment]
I think it may be good enough to index on the `mjd` property. That way you can quickly get all the photometry points after some date. You could filter that by SNR>3 or something. Then check if there are any results.

**Comment by acrellin** [comment]
There's already an index on the `mjd` column

**Comment by mcoughlin** [comment]
@guynir42 Can we close this?

**Comment by guynir42** [comment]
Will be closed when I am done with a couple more PRs.
