### ISSUE TITLE
High-frequency classification data blinking

### ISSUE THREAD

**Issue by dmitryduev** [skyportal/skyportal#2304]
Encountered this on https://fritz.science/source/ZTFJ184250.62+055309.0:
![blink](https://user-images.githubusercontent.com/7557205/135556419-e22271a3-6054-4934-83f6-2b90affaa5a1.gif)
Blinking is high-frequency, 25 fps is not enough to capture it properly.

**Comment by stefanv** [comment]
Could you describe in words what you see?

**Comment by dmitryduev** [comment]
The height of that div oscillates at like 100Hz so that the individual classifications jump up and down.
