### ISSUE TITLE
EM-GW and sGRB Fritz filters

### ISSUE THREAD

**Issue by igorandreoni** [skyportal/skyportal#2332]
If the old ones were not imported, we should create a new Fritz filter for GW and short GRB follow-up

**Comment by igorandreoni** [comment]
This issue should be part of Michael's issue #2051. Closing here.

**Comment by dmitryduev** [comment]
Thanks @igorandreoni. I think this is not a SkyPortal issue, so closing here.

For what it's worth, I don't think it's a Fritz issue either -- filters are user-defined/contributed content that is unique to a F instance and only lives in its db. You might, however, contribute it as a filter example to the docs.
