### ISSUE TITLE
Add option to filter objects by recently posted spectra

### ISSUE THREAD

**Issue by dmitryduev** [skyportal/skyportal#2337]
There has been a request to add an option to filter out objects with recently taken spectra, to be able to see, for example, all the objects that got an SEDM spectrum in the last two nights.
Would need to check what objects have associated spectra and which of them were taken within the requested time slot.

Add this option to the Obj tables, as in:
![image](https://user-images.githubusercontent.com/7557205/136132862-1910306c-a409-4ff4-875c-c85ed9944f06.png)

**Comment by dmitryduev** [comment]
@acrellin does this look like a "good second issue" to you? @bparazin wanna try taking this one on? or any other volunteers? ;)

**Comment by acrellin** [comment]
Definitely a good second issue!
