### ISSUE TITLE
Render phase-folded light curves in Sources table

### ISSUE THREAD

**Issue by dmitryduev** [skyportal/skyportal#2351]
Render a lightweight widget with phase-folded light curves if the source is annotated with a period(s). Render a dropdown with the available periods next to the LC plot.
This is very useful when people are classifying batches of variable sources using the Sources table.

**Comment by mcoughlin** [comment]
From Guy: add new Handler for phase folded light curve if period in annotations table. See HR diagram for example

**Comment by mcoughlin** [comment]
Closed by #2670
