### ISSUE TITLE
Render root-level range sliders in classification widget in Sources table

### ISSUE THREAD

**Issue by dmitryduev** [skyportal/skyportal#2361]
Otherwise this is the situation we may end up with:
![image](https://user-images.githubusercontent.com/7557205/137003516-8f415cce-2179-4833-94a4-4ffedd31d0d4.png)

**Comment by mcoughlin** [comment]
@bfhealy I think the current situation seems ok. Do you agree? If so, I think we close.

**Comment by bfhealy** [comment]
@mcoughlin Agreed, closing this issue.
