### ISSUE TITLE
Display only most recent classification on source page

### ISSUE THREAD

**Issue by scizen9** [skyportal/skyportal#2378]
I'm seeing multiple identical classifications on the source page.

![image](https://user-images.githubusercontent.com/6845428/137521326-dabe892b-6e3a-4ec6-97f4-ff1af3c5d323.png)

Probably should only display the most recent, or only the unique classifications.

**Comment by profjsb** [comment]
Note: The latest classifications are supposed to be shown for each taxonomy on which a classification was made (accessible to the user).

**Comment by dmitryduev** [comment]
We changed this a couple days ago: https://github.com/skyportal/skyportal/issues/2356.
For the Variable people, it is preferable to be able to see everything, and not just the most recent label per taxonomy (e.g. if something is variable, periodic, and RR Lyr).

I suggest to display unique labels (per taxonomy) and in the tooltip do group by it (e.g. in this case the Ia label will show three classification in the tooltip). @acrellin do you like the idea? If everyone likes it, @scizen9 do you want to take this one on?

**Comment by guynir42** [comment]
Closed by #3261
