### ISSUE TITLE
More digits to redshift adjustment of lines in spectra plots

### ISSUE THREAD

**Issue by erezimm** [skyportal/skyportal#2386]
The current spectra graphs in the object page only allow control of the redshift of lines in multiplicities of 0.001. If a higher precision value is set skyportal rounds the requested redshift to the closest 0.001 resolution.
This is an insufficient resolution for redshift tuning of high resolution spectra such as X-shooter. 
This issue has been brought up by the Supernova working group in ZTF. We would appreciate it if more digits be added to the applied redshift in the spectra graphs.

**Comment by guynir42** [comment]
closed by #2569
