### ISSUE TITLE
Bug with photometry legend and other legend requests

### ISSUE THREAD

**Issue by erezimm** [skyportal/skyportal#2395]
If too many instruments and bands observe an object the photometry plot legend in the object page is being cut off at some point and not all bands can be selected or deselected. An example of this behavior can be seen here where the I band is unreachable:
https://fritz.science/source/ZTF20acphdcg
![image](https://user-images.githubusercontent.com/53300818/139221493-9f3f9b10-39cf-478f-a4ed-b51f6f5fe8af.png)

This issue does not seem to occur in the spectroscopy plot, however, the plot height seems to be pegged to the legend which makes the plot inconvenient for small screens as the screen cannot contain the full plot:
![image](https://user-images.githubusercontent.com/53300818/139221291-0fcc387e-045f-4e1b-86e5-a016f078f0f7.png)

We think that allowing for multicolumn legends or placing the legend in the top or bottom might solve these issues.

This issue was brought up by several people in the supernova working group and we ask would appreciate it if this issue can be solved.

**Comment by guynir42** [comment]
I believe this is sorted out in https://github.com/skyportal/skyportal/pull/2085
