### ISSUE TITLE
Requests for photometry and spectroscopy plots

### ISSUE THREAD

**Issue by erezimm** [skyportal/skyportal#2396]
Other than the issues presented in [https://github.com/skyportal/skyportal/issues/2395](url) we would also like to ask for adjustments in the way plots are presented in the object page:

1. We think the right pane in the object page should be smaller or preferably collapsable to allow for larger photometry and spectroscopy plots. 
2. The data points in the photometry points are quite small and it would be nice if they could be larger
3. A select all/deselect all button would be much appreciated in the legends of both plots.

**Comment by guynir42** [comment]
number 1 seems to be complicated, but I will leave it here for now. 
number 2 not sure if want to make the points much bigger, we may consider making it customizable. 
number 3 is closed via Skyportal #2778
