### ISSUE TITLE
error pushing new source, missing doc and pos

### ISSUE THREAD

**Issue by AlexGKim** [skyportal/skyportal#241]
I am trying to push a new source supplying `id`, `ra`, `dec`.  I get the following error

`'{"status": "error", "message": "__init__() missing 2 required positional arguments: \'doc\' and \'pos\'", "data": {"version": "0.9.dev0"}}'`

I couldn't find any information on these parameters.

**Comment by acrellin** [comment]
@AlexGKim can you paste the command that produced this error? If you are using `requests`, you may be using the `data` keyword argument, whereas using `json` instead might resolve your issue.

**Comment by acrellin** [comment]
@AlexGKim our handlers always expect `json`

**Comment by AlexGKim** [comment]
Forgive me.  I used to know that!

**Comment by stefanv** [comment]
@acrellin Perhaps we can catch this more elegantly and throw a useful error back?

**Comment by acrellin** [comment]
@stefanv yes, agreed - I'll open and issue for that and take care of it
ASAP.
