### ISSUE TITLE
Taxonomy addition: Icn 

### ISSUE THREAD

**Issue by rjoebruch** [skyportal/skyportal#2432]
Hi! could someone add to the sitewide taxonomy the "Icn" type, following the publication of these : 
https://ui.adsabs.harvard.edu/abs/2021TNSAN..76....1G/abstract 
https://arxiv.org/pdf/2111.12435.pdf
https://arxiv.org/pdf/2111.12110.pdf

thank you!

**Comment by profjsb** [comment]
Please make a PR to https://github.com/profjsb/timedomain-taxonomy

A good example of what needs changing is: https://github.com/profjsb/timedomain-taxonomy/pull/11

**Comment by acrellin** [comment]
Implemented in https://github.com/profjsb/timedomain-taxonomy/pull/14
