### ISSUE TITLE
Refactor load_demo_data to use API calls

### ISSUE THREAD

**Issue by stefanv** [skyportal/skyportal#246]
This will also ensure that we have all the necessary API endpoints

**Comment by acrellin** [comment]
@stefanv Currently we have no way of creating Super admin users via the users API - how should we handle permissions when there aren't any users in the DB yet?  Or should initial user creation still be done via direct `sqlalchemy` calls in `load_demo_data`, and then all subsequent additions be done via API calls?

**Comment by stefanv** [comment]
In order to use the API, you need a token, and you can't make a token without a user.  So, you have to start somewhere!  I think the current way we handle it—initializing the first user via a script—is reasonable.
