### ISSUE TITLE
Periodogram analysis button depends on window size

### ISSUE THREAD

**Issue by d-giles** [skyportal/skyportal#2465]
https://user-images.githubusercontent.com/14115456/144904960-7e5f3afa-6f0b-4277-968f-3ac8a3c56e4d.mov

**Comment by acrellin** [comment]
Hi @d-giles , thanks for the issue. 

This is a feature, not a bug.  When the screen size goes below a certain threshold, the rendering switches to a mobile-optimized version, which excludes certain items that are less appropriate for mobile users such as the periodogram analysis button.
