### ISSUE TITLE
python-ligo-lw 1.8.0 not working

### ISSUE THREAD

**Issue by Theodlz** [skyportal/skyportal#2482]
new version of python-ligo-lw, 1.8.0 (updated on the 13th of December 2021) causes errors. Right version should be specified in requirements.txt : python-ligo-lw 1.7.1

**Comment by mcoughlin** [comment]
Can you open a quick PR @Theodlz ?

**Comment by Theodlz** [comment]
issue is i already have a fork with many other changes and if it seems that i can't create a pull request about just one file. I'll ask another team member to do it

**Comment by mcoughlin** [comment]
Ah you aren't working on another branch so you can just make another branch?

**Comment by Theodlz** [comment]
thomas took care of the PR you should be able to see it
