### ISSUE TITLE
getting groups

### ISSUE THREAD

**Issue by AlexGKim** [skyportal/skyportal#249]
When `get`ing a group, I get the message

>{'status': 'error',
 'message': "'Token' object has no attribute 'roles'",
 'data': {'version': '0.9.dev0'}}

I am using a token that worked for get'ing and put'ing sources.

**Comment by stefanv** [comment]
This is great; keep the feedback coming!

**Comment by acrellin** [comment]
Alex, can you please include the request that triggered this response?

**Comment by AlexGKim** [comment]
```
 r=requests.get(url+"groups", headers={'Authorization': "token xxxxxxxx"})
print(url+"groups")
r.json()
http://web.skyportal.dev-cattle.stable.spin.nersc.org:60035/api/groups
{'status': 'error',
 'message': "'Token' object has no attribute 'roles'",
 'data': {'version': '0.9.dev0'}}
```

**Comment by acrellin** [comment]
Great, thanks! I'll push up a fix right away. Also, note that you are
grabbing all groups in that request, not a single group.

**Comment by AlexGKim** [comment]
Indeed my intent is to look for all groups.

Is it possible to get a glossary of `instrument_id` with their full names?

**Comment by acrellin** [comment]
I'm not sure what you mean by a glossary of instrument_id? Can you please
clarify? Thanks

**Comment by AlexGKim** [comment]
I need `instrument_id` to Upload Photometry.  I need a way to know what id to use given a instrument whose English name I know.

**Comment by acrellin** [comment]
When the instrument API is complete (coming shortly), you'll be able to
query `/api/instrument` for a list of instruments, including name, ID, etc.
Will that solve your problem?

**Comment by AlexGKim** [comment]
Yes good

**Comment by acrellin** [comment]
Great. There is now an open PR with those additions.

**Comment by AlexGKim** [comment]
In trying to `put` a telescope I get the message asking for `telescope_id`.  I thought the assignment of id's was taken care of under the hood.

```
{'status': 'error',
 'message': "put() missing 1 required positional argument: 'telescope_id'",
 'data': {'version': '0.9.dev0'}}
```

**Comment by acrellin** [comment]
@AlexGKim , PUT is for updating existing entries, and you do need to specify the ID in that case.  If you POST, then yes, it will generate and ID under the hood

**Comment by acrellin** [comment]
https://www.restapitutorial.com/lessons/httpmethods.html

**Comment by acrellin** [comment]
@AlexGKim when you create a telescope with POST, the response will contain the new ID, and you can use that for any PUT requests you need to make

**Comment by AlexGKim** [comment]
Got it thanks!
