### ISSUE TITLE
Typo in docs

### ISSUE THREAD

**Issue by jadalilleboe** [skyportal/skyportal#2522]
Noticed this small typo on "Developer Notes" page of docs. Should be xvfb. Let me know if I should change this and make a PR
![Screenshot (12)](https://user-images.githubusercontent.com/82007190/147963194-1fa1c273-d7be-4c99-90b2-fb7d1a84f53d.png)

**Comment by profjsb** [comment]
Please do a PR and reference this issue in the comments. We'll merge it quickly!
