### ISSUE TITLE
Instruments with limiting magnitude and associated exposure time

### ISSUE THREAD

**Issue by mcoughlin** [skyportal/skyportal#2527]
As part of the follow-up API, having some way of reporting a characteristic limiting magnitude for a given exposure time would be nice to then display when making a follow-up request, computing something like:

            nmag = -2.5*np.log10(np.sqrt(config_struct["exposuretime"]/exposureTime))
            limiting_mag = config_struct["magnitude"] + nmag

So adding this information as optional columns to the Instrument table (setting, for example, ZTF has 20.5 mag in 30 seconds).

**Comment by guynir42** [comment]
This has something to do with https://github.com/skyportal/skyportal/pull/2765

**Comment by mcoughlin** [comment]
Yeah related.
