### ISSUE TITLE
GCN event list link

### ISSUE THREAD

**Issue by mcoughlin** [skyportal/skyportal#2528]
Would be nice to link to / display GCNs connected to a given event. I hope there is some kind of API through:
https://heasarc.gsfc.nasa.gov/wsgi-scripts/tach/gcn_v2/tach.wsgi/

**Comment by robertdstein** [comment]
As I said in the meeting, I am happy to do this, but cannot assign myself. I am a member of the Fritz organisation, but maybe different permissions are needed here.
