### ISSUE TITLE
Difficulty configuring rate limiting

### ISSUE THREAD

**Issue by rknop** [skyportal/skyportal#2535]
I run skyportal in a docker image.  I make minimal changes to the docker.yaml file (which gets copied to config.yaml) in the top directory.  Some of these config changes don't seem to "take", however.

In particular, I'm trying to relax rate limiting.  I've got the following in my docker.yaml:
```
server:
  rate_limit: 200
  burst: 1000
  whiltelisted_ips:
    - 128.55.0.0/16
    - 128.3.30.0/24
    - 128.3.7.144/28
    - 128.3.2.17
```
I started with a more modest rate limit, and have increased it.  However, requests are still being rate limited, and looking at the logs I don't think we're anywhere near 200 requests per second.

I do notice that in the docker image, the file `baselayer/services/nginx/nginx.conf` has

`   limit_req_zone $limit_key zone=custom_rate_limit:1m rate=5r/s`

which suggests to me that it's not picking up the changes I put into the docker.yaml.  (The config.yaml file inside the image is what I expect, i.e. a copy of docker.yaml.)  I notice that `baselayer/config.yaml.defaults` has server.rate_limit set to 5, and server.burst set to 10.  I don't know if that's where things are being picked up, but it looks like that.

What's the right way to proceed?  I find the mix of configuration files a bit baffling, I have to admit.  The same directives are in multiple places.  What I'd expect is that the top level config.yaml file would override things that were elsewhere, but the changes I made there don't seem to be making any difference to what's running.

**Comment by stefanv** [comment]
Hi @rknop. I think your expectation is the right one: that directives in the config.yaml overrides everything else.  That is the way the system is supposed to function, and if it does not that is a bug.

I see what is going wrong: the Dockerfile runs `make production`, which does not regenerate any of the configuration files.  But, in your case, the nginx config file depends on the skyportal config, so it needs to be re-generated.

You can test whether this is the problem by changing the entrypoint to using `make run` instead of `make run_production`.  If that works, then I can easily fix it.

**Comment by rknop** [comment]
The file `baselayer/services/nginx/nginx.conf` looks better using `make run` instead of `make run_production`.  We're testing now to see if in practice the rate limiting is relaxed.

Is there an argument you can pass to the Makefile to make it regenerate the config files?  If so, then we can just add that as a RUN before the last line of the Dockerfile.  (I don't think a RUN line with `make run` would work, as the server process wouldn't terminate.)

**Comment by rknop** [comment]
OK, things seem to be working with `make run`.  (Of course, we'd rather use `make run_production` for production.  I'll leave it like that for now.  Let me know if there's a quick fix.)

Thanks,

-Rob

**Comment by stefanv** [comment]
You can run the command `make system_setup` after adding the configuration file.  That should be a perfectly safe stopgap measure for now.

**Comment by stefanv** [comment]
I opened #2536 to track this.
