### ISSUE TITLE
Error Bars on photometry

### ISSUE THREAD

**Issue by anticharmquark** [skyportal/skyportal#257]
Hello,
I am unable to see error bars on the photometry plots for posted sources. Is this a functionality that is built in and I am not seeing? It would be an excellent feature if not already implemented.

**Comment by anticharmquark** [comment]
Additionally, it seems that some of the photometry points remain on the plot even when they are unchecked.

**Comment by acrellin** [comment]
Also see #115 and PR #191

**Comment by dannygoldstein** [comment]
Closed by #191
