### ISSUE TITLE
Cannot clear DB

### ISSUE THREAD

**Issue by guynir42** [skyportal/skyportal#2572]
When running `make db_clear` the app fails, specifying the requirement `numpy` is required in baselayer and in skyportal (with different versions). 

If I remove the requirement in BL then it has the same conflict with "requests". 

After I remove that one as well, I get something about no password specified. I tried using `sudo make db_clear` but it doesn't work. 

The app runs without problems, but I am unable to clear the database.

**Comment by stefanv** [comment]
Please post exact error messages.

**Comment by guynir42** [comment]
When I run `sudo make db_clear` I get:
```
selenium 4.1.0 is installed but selenium<4.0.0,>=3.141.0 is required by {'selenium-requests'}

ERROR: Double requirement given: numpy==1.21.4 (from -r requirements.txt (line 1)) (already in numpy>=0.17 (from -r baselayer/requirements.txt (line 23)), name='numpy')

```

When I remove the numpy requirement in BL I get a similar thing with the requests package. 

When I remove that as well, I get:

```
Could not delete database: 
  psql: error: fe_sendauth: no password supplied

```

**Comment by guynir42** [comment]
@stefanv not sure how to do that...

**Comment by guynir42** [comment]
I used to be able to clear db only after supplying the system password.

**Comment by guynir42** [comment]
After changing the `pg_hba.conf` file to `trust` all the different users (and after that, restarting postresql) I managed to successfully clear the database.
