### ISSUE TITLE
Galaxy Table Display

### ISSUE THREAD

**Issue by mcoughlin** [skyportal/skyportal#2578]
The idea is to add a table of galaxy information (for example, galaxy ID, catalog, RA, DEC, proba, distance (Mpc), Nb. Obs, mag limit, last obs, Nb. OTs) in the form of table, with the ability to do searching / sorting (column value, increasing/decreasing order and choice of sorting header) (by default decreasing probability).

Basically the same as the sources table display:
https://github.com/mcoughlin/skyportal/blob/crossmatch3/static/js/components/GcnEventPage.jsx#L160
but for galaxies.

**Comment by mcoughlin** [comment]
@jadalilleboe I have an open PR here: https://github.com/skyportal/skyportal/pull/2596. It will need to tie into your source filtering PR in basically the same way. Plus we need to get these galaxies visualized on the skymap.

**Comment by jadalilleboe** [comment]
@mcoughlin ohh ok. Any issues that aren't being worked on?

**Comment by mcoughlin** [comment]
This mostly works.
