### ISSUE TITLE
Sources in Skymaps

### ISSUE THREAD

**Issue by mcoughlin** [skyportal/skyportal#2579]
Add a front-end element to modify the start and end time and skymap confidence levels, i.e. the parameters here:
https://github.com/mcoughlin/skyportal/blob/crossmatch3/static/js/ducks/sources.js#L73
to modify the source selection criteria from the GcnEventPage.

**Comment by mcoughlin** [comment]
@jadalilleboe Can you do this one? It isn't blocked by anything at this point. Should "just" be a few text boxes on the GcnEventPage to modify the sources action.

**Comment by jadalilleboe** [comment]
@mcoughlin What should the title be on the box for skymap confidence levels? I see there's two parameters `filterParams.localizationDateobs` and `filterParams.localizationCumprob` but I'm not sure what those stand for

**Comment by mcoughlin** [comment]
So I think the localizationDateobs should be a dropdown consisting of the localization dateobs and names i.e. in this loop: https://github.com/skyportal/skyportal/pull/2610/files#diff-1ace4e0ca4f980d24bdd1dada5fe70a70f883fbb6edf17187d6f9ca491749eabR227
and the cumulative probably should range from 0-1 and default to 0.95 or something.

**Comment by mcoughlin** [comment]
@jadalilleboe and I got this one.
