### ISSUE TITLE
PUT new group_ids to spectrum

### ISSUE THREAD

**Issue by AlexGKim** [skyportal/skyportal#2583]
There is a Spectrum to which I want to make available to people who are members of a group.  I run the command

```
curl -X PUT -s -H 'Authorization: token XXX' -d '{"group_ids": "[76]"}' https://desi-skyportal.lbl.gov/api/spectra/76957

{
  "status": "success",
  "data": {},
  "version": "0.9.dev0"
}
```
Looking at the contents of https://desi-skyportal.lbl.gov/api/spectra/76957 there appears to be no change.

People in the group with grouped 76 remain unable to see the spectrum.

Am I doing this incorrectly?

**Comment by stefanv** [comment]
I can confirm this bug.  For the test data:

```
curl -X PUT -H 'Authorization: token ...' http://localhost:5000/api/spectra/1 -d '{"group_ids": [2,7,6]}'
curl -X GET -H 'Authorization: token ... http://localhost:5000/api/spectra/1 | less
```

**Comment by stefanv** [comment]
There's a whole bunch of checking that takes place in spectrum.POST that is entirely missing from spectrum.PUT.
