### ISSUE TITLE
Stand-alone microservice example

### ISSUE THREAD

**Issue by mcoughlin** [skyportal/skyportal#2601]
With the ongoing work on light curves, kafka, etc., it would be really nice to have some kind of functional template that was almost "plug and play." This would probably look kind of like fritz, but stripped down by someone like @stefanv who knows what is important.

**Comment by stefanv** [comment]
1. Clone SkyPortal to `skyportal`
2. In the `skyportal/services` directory, add a folder `mybroker` with two files: `supervisord.conf` and `mybroker.py`.

`supervisord.conf`:

```
[program:slack]
command=/usr/bin/env python services/mybroker/mybroker.py %(ENV_FLAGS)s
environment=PYTHONPATH=".",PYTHONUNBUFFERED="1"
stdout_logfile=log/mybroker.log
redirect_stderr=true
autorestart=true
startretries=10
```

`mybroker.py` can contain anything you want, and will be fired up alongside skyportal.

**Comment by mcoughlin** [comment]
@stefanv and how do you suggest dealing with adding these files in cases where you wont want them added into SkyPortal (i.e. the kafka stuff)? Is this some kind of bash script with a cp to that directory or something else?

**Comment by stefanv** [comment]
You'll see that Fritz is basically just a glorified bash script that plugs things in where they need to go.

If you want to work with Kafka, that's a whole other ballgame since you have to use docker and set up the various containers to talk to one another.

If it would be helpful, we could also modify baselayer to look for services elsewhere, so that you can truly run skyportal side-by-side with another microservice, without even having to copy your service into skyportal.  Of course, you'd still need to update the skyportal config.yaml to tell it where to find your service.

**Comment by mcoughlin** [comment]
Yeah I have looked through it, and I guess you are right :)

I am also thinking of the light curve fitting stuff, which definitely does not necessarily require a bunch of containers, but @profjsb had suggested might make sense as being its own service (discussion here: https://github.com/skyportal/skyportal/pull/2431).

**Comment by stefanv** [comment]
We could also have baselayer support the notion of "external" services.  I.e., you provide a git address in the config, and baselayer pulls it in before deployment:

```
services:
  - lightglove:
      repository: https://github.com/mcoughlin/lightglove
      ref: 12affbedfg78
```

**Comment by mcoughlin** [comment]
And how would the IP address that is created by set and known by SP?

**Comment by stefanv** [comment]
I'm not sure what you mean; if SP needs to be aware of a service, then that service is probably not externally developed.

If SP has generic mechanisms (either to connect to a service, or for the service to connect to), those can be specified in the configuration file.

**Comment by mcoughlin** [comment]
I am thinking of Josh's line here: "This can be done as a direct call in an API or as an API call to a microservice that we build."  Doesn't that mean SP would still need to be aware somehow?

**Comment by profjsb** [comment]
A mechanism to call a generic light curve fitter (perhaps with a schema that defines in and out) very much could be a skyportal thing. We could use Michael's fitter as an example. That is we can add a microservice to do light curve fitting and in that service we configure the internals using a config.

**Comment by mcoughlin** [comment]
Just to be very concrete:
So in https://github.com/skyportal/skyportal/pull/2431, we do define a table (that should be made as generic as possible for other types of fitting) to include in SkyPortal to save the results and display them.

At the same time, we add a SP configuration parameter like:

lightcurve_fitter:
  protocol: http
  host: localhost
  port: 65100

That go in as configuration parameters and then get passed to Stefan's suggestion here?

[program:fitter]
command=/usr/bin/env python services/lightcurve_fitter/myfitter.py %(ENV_FLAGS)s
environment=PYTHONPATH=".",PYTHONUNBUFFERED="1"
stdout_logfile=log/myfitter.log
redirect_stderr=true
autorestart=true
startretries=10

which will set the IP and such properly. Is that the right way to think about this?

**Comment by mcoughlin** [comment]
I think at this point there are enough examples that folks can copy things.
