### ISSUE TITLE
New users and groups

### ISSUE THREAD

**Issue by AlexGKim** [skyportal/skyportal#263]
I would like to assign users to groups before they log into skyportal for the first time.  This seems not to be possible.

**Comment by profjsb** [comment]
And to add to this, it would be useful to have the notion of group/user invitations. Story: a group owner wants to invite someone to join their group. This amounts to adding their email address to a pre-approved list of users for that group. When the user signs up (for the first time) they are automatically allowed to be enrolled in that group (subject to their acceptance). If they have already signed up then they automatically allowed to be enrolled in that group. Optionally: when a group owner invites a user that user gets an email with the invitation link.
