### ISSUE TITLE
cannot save archival source to any group

### ISSUE THREAD

**Issue by janvanroestel** [skyportal/skyportal#2650]
Initially reported as: https://github.com/fritz-marshal/fritz/issues/388

Describe the bug
While trying to save a new archival source to Fritz, no groups were selectable and the source could not be saved

To Reproduce

Go to Archive
Search for a source that has not been saved to Fritz (e.g. 309.9166, 52.5487)
Select all lightcurves (square box on the top-left)
Click the save icon (top right)
A window named "Save selected data to Fritz" appears with 'Create new source' selected. However, none of the groups below are selectable (they are all greyed out).

![image](https://user-images.githubusercontent.com/10774087/153276317-c4f8f901-f872-4929-ac32-0b7004d2f9c8.png)

Expected behavior
The groups should be selectable so the new source can be saved to that group

Platform information:

Fritz version: v0.9.dev0+git20220127.4091810e+fritz.624b31d.
Interface: I am browsing on a desktop (Chrome)

**Comment by guynir42** [comment]
Closed in favor of Fritz #388
