### ISSUE TITLE
D3 plots in GCN events broken

### ISSUE THREAD

**Issue by stefanv** [skyportal/skyportal#2672]
```
Warning: Failed prop type: Invalid prop `sources` of type `object` supplied to `GcnEventSourcesPage`, expected an array.
    at GcnEventSourcesPage
```

Most noticeably, no graphics appears on the page.

**Comment by mcoughlin** [comment]
Yes, this is why I wanted to move here:
https://github.com/skyportal/skyportal/pull/2533
But this was turned down. I find the existing plotting completely counterintuitive and difficult to work with.

**Comment by mcoughlin** [comment]
This is vastly improved.
