### ISSUE TITLE
SQLAlchemy 2: port query statements to select statements

### ISSUE THREAD

**Issue by stefanv** [skyportal/skyportal#2691]
See also https://docs.sqlalchemy.org/en/14/changelog/migration_20.html#orm-query-unified-with-core-select

**Comment by mcoughlin** [comment]
@guynir42 Should we close this in lieu of more specific issues like the tests and such?

**Comment by guynir42** [comment]
Yes, I think we've changed most of what we can without breaking stuff in baselayer.
