### ISSUE TITLE
Tweaking the observing run page

### ISSUE THREAD

**Issue by profjsb** [skyportal/skyportal#2695]
Tweaks to the observing run page:

  - Only show recent and upcoming observing runs (say last 1 week forward in time)
  - Different Highlight color (or emoji!) the observing run that comes next in time so people can scroll to it easily
  - Give human readable dates ("3 weeks ago", "2 months from now") in addition to calendar date
  - allow user to "Show All" runs with a button at the bottom that unhides all the older runs

**Comment by mcoughlin** [comment]
Finished by #2838
