### ISSUE TITLE
Instruments page improvements

### ISSUE THREAD

**Issue by profjsb** [skyportal/skyportal#2696]
- allow filter to be added in the same way as with groups in user management (+ button):
<img width="803" alt="image" src="https://user-images.githubusercontent.com/480799/155622130-edf6714a-4606-479e-97cb-275787cbc5fe.png">

   - show all available filters, not just those that have been used before

   - properly wrap the filters in an instrument: 

<img width="927" alt="image" src="https://user-images.githubusercontent.com/480799/155622311-8c3a23be-edde-42fe-93c7-29073dbc15e2.png">

**Comment by mcoughlin** [comment]
@jadalilleboe Can you take care of the filter wrapping please? And any other visualization improvements that seem reasonable to you?

**Comment by mcoughlin** [comment]
Finished by #2838
