### ISSUE TITLE
Add link to Aladin to source page

### ISSUE THREAD

**Issue by janvanroestel** [skyportal/skyportal#2698]
Add a button that links to the Aladin webpage (https://aladin.u-strasbg.fr/AladinLite/). The link should point to the right sky coordinates and default to panstarrs.

**Comment by janvanroestel** [comment]
I've added:
      <SurveyLink
        name="Aladin"
        url={`http://aladin.unistra.fr/AladinLite/?target=${ra_to_hours(ra, "%20")}${
          dec > 0 ? "%2B" : ""
        }${dec_to_dms(dec, "%20")}&fov=0.01&survey=P%2FDSS2%2Fcolor`}
      />

to the SurveyLinkList.jsx file; but it does not show up when I load an example source page

**Comment by profjsb** [comment]
Did you restart the app (`make run`) and shift-reload the page? Can you open a PR with your changes? It's hard to debug this way.
