### ISSUE TITLE
Form to add a source - can be added to single group user

### ISSUE THREAD

**Issue by Theodlz** [skyportal/skyportal#2833]
I'm not 100% about this, but from what i understood a source belongs to a proper group, not a single group user which is just one user. Here, in the form to add a source, single group users can be selected

![image](https://user-images.githubusercontent.com/49785117/162282266-22b3726b-4b01-41e0-85fd-45f4e9a24595.png)

**Comment by mcoughlin** [comment]
@Theodlz Do we have an element that returns only the "real" groups to make this a drop in?

**Comment by Theodlz** [comment]
> @Theodlz Do we have an element that returns only the "real" groups to make this a drop in?

I dont know if the ducks returns it, but theres a a single user boolean column in the db so you could just filter the groups you display on the frontend using that ? Otherwise we did the same in the shifts page.
