### ISSUE TITLE
Image / fits display

### ISSUE THREAD

**Issue by mcoughlin** [skyportal/skyportal#2840]
Clearly SkyPortal was developed with reduced data in mind, i.e. post photometry or spectroscopy. But I was wondering about the unreduced images that go along with those. I know Guy has been thinking a bit about dealing with larger data storage for his stuff, but for SEDMv2, I am pondering whether it might be nice to also be able to store (at least the) paths to the raw images and potentially display them with js9 or something. It would be nicer than always needing to send the files by email to folks if others want to try reducing it or looking at the image for a source, etc.

**Comment by Theodlz** [comment]
@mcoughlin does our ability to store these fits as comment attachment, and to display them on the frontend (by rendering them with matplotlib) addresses this issue? If ye, we can close.

**Comment by mcoughlin** [comment]
Thanks @Theodlz !
