### ISSUE TITLE
Infinite extent warning for vega plots

### ISSUE THREAD

**Issue by jadalilleboe** [skyportal/skyportal#2843]
`WARN Infinite extent for field "date": [Infinity, -Infinity]`
`WARN Infinite extent for field "limiting_mag": [Infinity, -Infinity]`
`WARN Infinite extent for field "phase": [Infinity, -Infinity]`
`WARN Infinite extent for field "daysAgo": [Infinity, -Infinity]`
on source table page and observability page.

**Comment by guynir42** [comment]
Seems like it is not relevant anymore. Re-open if this pops up again.
