### ISSUE TITLE
Uncaught HEAD exception

### ISSUE THREAD

**Issue by profjsb** [skyportal/skyportal#2852]
It is unclear if this endpoint is being hit programatically or via the front end but either way we should make sure we gracefully handle a HEAD request to /source

```
ERROR:tornado.application:Uncaught exception HEAD /source/ZTF22aaezjuu (IP address)
HTTPServerRequest(protocol='http', host='fritz.science', method='HEAD', uri='/source/ZTF22aaezjuu', version='HTTP/1.0', remote_ip='IP address')
Traceback (most recent call last):
  File "/skyportal_env/lib/python3.8/site-packages/tornado/web.py", line 1702, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/skyportal_env/lib/python3.8/site-packages/tornado/web.py", line 264, in _unimplemented_method
    raise HTTPError(405)
tornado.web.HTTPError: HTTP 405: Method Not Allowed
```

**Comment by THE-COB** [comment]
I haven't reproduced the error yet, but it might just be a typo ("sources" instead of source). Browsing the routes in https://github.com/skyportal/skyportal/blob/master/skyportal/app_server.py, it looks like all the routes have "sources" and then some regular expression
