### ISSUE TITLE
User defined classification button

### ISSUE THREAD

**Issue by mcoughlin** [skyportal/skyportal#2858]
User defined button(s) to add to the scanning page that set classification to 1 for commonly used classifications (i.e. artifact or comet for the NEO scanning). Right now you need to click through (many) dropdowns.

**Comment by jadalilleboe** [comment]
@mcoughlin could you explain a bit more? I don't get "set classification to 1"

**Comment by mcoughlin** [comment]
Like on the scanning page, allowing the user to add a button that says "Comet" which sets that classification when pressed. @jadalilleboe

**Comment by mcoughlin** [comment]
@jadalilleboe yeah definitely very similar!
