### ISSUE TITLE
fix shift test

### ISSUE THREAD

**Issue by profjsb** [skyportal/skyportal#2859]
```
FAIL: skyportal/tests/frontend/test_shifts.py:82 in test_super_user_post_shift

        driver.click_xpath(delete_button_xpath)
        driver.wait_for_xpath_to_disappear(f'//*[text()[contains(.,"{form_name}")]]')
    
>       assert (
            len(driver.find_elements_by_xpath(f'//*[text()[contains(.,"{form_name}")]]'))
            == 0
```

**Comment by profjsb** [comment]
@Theodlz -^

**Comment by Theodlz** [comment]
Hi @profjsb, could you tell me more about the issue you are having ? This test passes both locally and on the github actions for me, and i saw that on the latest github actions on skyportal/skyportal (run by @jadalilleboe) it worked too.

**Comment by profjsb** [comment]
It's flaky (ie fails sometimes) so could be moved to flaky tests or improved (better option).

**Comment by Theodlz** [comment]
Thanks for the explanation, i'll work on it then !

**Comment by Theodlz** [comment]
Do you have a good way to test if its flaky or not ?

**Comment by mcoughlin** [comment]
We could open a PR and make empty commits and write a little script to parse the logs?

**Comment by Theodlz** [comment]
We can try. Otherwise i just ran the test with py.test using the --count argument at 50 so i can run the test 50 times in a row to try to reproduce that behavior. Out of 50 times it failed 2 times, but not where Josh showed me, but before, when checking if a shift added using the API appears on the calendar.

**Comment by stefanv** [comment]
Unfortunately, if you have on the order of 130 tests (like we do), if each test has a 2/50 failure rate the likelihood of overall failure becomes very high (>99%).  I guess all I'm trying to say is that, even if tests seem reasonably solid, we have to work hard to get them absolutely reliable.  To be fair, many of our tests currently have a much higher than 2/50 failure rate (bad).
