### ISSUE TITLE
ZTF API Session

### ISSUE THREAD

**Issue by guynir42** [skyportal/skyportal#2866]
I'm working on putting database sessions into context managers, and I ran into some unclear code in the ZTF API handler (`skyportal/facility_apis/ztf.py`). There seems to be one `Session` imported from `requests` and another `Session` defined from SQLA. Someone should go over this file and make sure all the sessions mean what they're supposed to mean, and probably do well to wrap them in context managers (`with - as` statements).

**Comment by mcoughlin** [comment]
@guynir42 So I had seen this construction:

https://github.com/skyportal/skyportal/blob/master/skyportal/facility_apis/ztf.py#L215

in other places where we run stuff in other threads. What do you think this should be?

**Comment by guynir42** [comment]
I'm not sure about this. In baselayer we scope it to the specific request id. I don't know what the right thing to do in this case. 
Maybe @stefanv has an idea. 
But there are a few other things worth addressing besides that in that file.

**Comment by stefanv** [comment]
Sessions typically belong to the request they're coming from: you can think of it as one db connection per request.  But, if we spawn tasks, then we need a new db connection—one for each thread.

**Comment by guynir42** [comment]
@stefanv I'm just wondering if the line 215 that we're discussing should contain a `scopefunc` argument?
