### ISSUE TITLE
GCN event page, can't retrieve observation plans.

### ISSUE THREAD

**Issue by Theodlz** [skyportal/skyportal#2875]
On the GCN page, after adding an observation plan and submitting it to the queue, the screen gets basically covered with errors as it can't retrieve them. After discussing it with @mcoughlin, we noticied that he did not have that problem. The conclusion is that it is linked to the postgresql version. After updating it to version 14, i encountered no error at all. 

So, i think this could be approached in 2 different ways:

1. We update the documentation requiring postgresql-14 along with instructions to install it as in the current LTS versions of most linux distros (and probably MacOS too ?), postgresql-13 is available to install, but not 14.
2. We have a look at what is causing this issue in the code, and if possible change it to something else that can work the version currently required by SkyPortal's documentation.

Also, as the page doesn't work properly on PostgreSQL versions lower than 14, it is probably why one of the flaky tests is actually broken.

**Comment by mcoughlin** [comment]
@stefanv What is the best path forward here? Can we suggest postgresql 14 in the docs?

**Comment by mcoughlin** [comment]
@Theodlz Can you please make a quick PR explicitly mentioning that postgres 14 is required for any MMA work?

**Comment by stefanv** [comment]
I think it's fine to set postgres 14 as minimum version once we use v14 features in models.

I suspect this may be an inconvenience to some existing running instances, but migrating a database isn't hard for on-premise dbs (which most of those are).

Let's try it and see if we receive feedback.
