### ISSUE TITLE
Issue with postgresql configuration : pg_hba.conf

### ISSUE THREAD

**Issue by Theodlz** [skyportal/skyportal#2876]
Currently, when adding those 2 lines:
```
host skyportal skyportal 127.0.0.1/32 trust
host skyportal_test skyportal 127.0.0.1/32 trust
```

when using postgres-12 or postgresql-13 (the version provided by ubuntu) or even postgres-14 (having to add the postgresql repo for this one), we can't run skyportal using just the make commands as they can't seem to be able to access the database.

Indeed, i tried creating a db called skyportal manually as the make command couldn't do it, and then the user skyportal can actually access the database, and we run into the same error but for skyportal_test database.

Then, we can't run make db_clear, as the user postgres doesn't seem to have access to the database either.

Here, you'll find a Dockerfile that builds a container that reproduces this error using postgresql-13 (but you can modify it to use postgresql-12 very easily) : [Dockerfile.txt](https://github.com/skyportal/skyportal/files/8561579/Dockerfile.txt)

I think that maybe the problem is the instructions in the documentation, and maybe not postgresql itself. One strange this though, is that when i installed postgresql-12 for the first time on my machine, it did work. But for other people like @thomasculino it did not work(he uses ubuntu 20.04, i use a 21.04). And now that i upgraded postgresql to version 14, it doesn't work anymore. I tried downgrading it but i have the same problem...

EDIT : i think all this makes sense, as in the config file we allow only the skyportal user to access postgres (more specifically skyportal's db) without a password on localhost, but not the 'postgres' user. But then, if i add : 

```
host skyportal postgres 127.0.0.1/32 trust
host skyportal_test postgres 127.0.0.1/32 trust
```

It still doesn't work, but adding: 

```
host skyportal postgres 127.0.0.1/32 trust
host skyportal_test postgres 127.0.0.1/32 trust
```

which basically gives access to all databases to the postgres user without a password. But obviously, for security reasons when deploying the app, giving access to a user to all databases without a password (and that also gives it the right to delete users and databases) is not something we want. 

What im thinking is that maybe it would be best to access postgres to create db and user (when running make db_clear or db_init) using sudo, so allowing only root user to do it. Could be something like: you run make db_clear > it asks for your password ?

# Update: This issue has been fixed by PR https://github.com/skyportal/skyportal/pull/2938

**Comment by stefanv** [comment]
On Ubuntu systems the postgres user should be configured to have access by default.  Did you add the host lines *after* the existing lines? From your Docker image it looks like they go in before.

**Comment by Theodlz** [comment]
Hi @stefanv , i added it before because skyportal's documentation specifically asked to do that. Also, i tried on a brand new install of postgres, and by default the postgres user doesnt have access to postgresql without a password. If i use `psql -U postgres --no-password` with the default `pg_hba.conf` file of a new postgresql installation, it doesnt work. But it makes sense no ? In the config the postgres user is not trusted to connect to any DB without a password (its peer, or scram-sha-256 but not trust)

**Comment by Theodlz** [comment]
Also, same issue on Centos, Ubuntu 20.04 and 21.04

**Comment by Theodlz** [comment]
What I noticed is that by default if you are using a docker container for postgresql (using the official image), everything is `trust` in the config file, so of course it always works in docker.

**Comment by stefanv** [comment]
Ah, thanks for checking—I remembered the order mattered, didn't realize we advised putting it first.  I wonder if Ubuntu changed anything, because we always tested on Debian / Ubuntu, and postgres user was able to access what it needed to.  I will investigate a bit more.

**Comment by Theodlz** [comment]
Great, thanks @stefanv . If i can help in any way  I'll be happy to do so.

**Comment by stefanv** [comment]
OK, so @Theodlz I think you've figured out the problem (the missing line adding skyportal and skyportal_test to pg_hba.conf).  Do you want to make a PR?

**Comment by Theodlz** [comment]
There's already one ! Sorry i forgot to put in on the issue...

Here it is : https://github.com/skyportal/skyportal/pull/2864

**Comment by Theodlz** [comment]
Done ! @stefanv you can find it here: https://github.com/skyportal/skyportal/pull/2938
