### ISSUE TITLE
Add generic `DatabaseMapper` handler to avoid repeated code

### ISSUE THREAD

**Issue by acrellin** [skyportal/skyportal#294]

**Comment by dannygoldstein** [comment]
@acrellin Do we still want to try to do this ?

**Comment by stefanv** [comment]
@dannygoldstein The idea here was to add a generic API handler (standard GET, PUT, PATCH, POST), that can then be overridden as necessary.

**Comment by kmshin1397** [comment]
At this point, it seems like we have enough custom behavior pop up per handler where making something generic would not be worth the refactoring effort. Thoughts on closing this issue @stefanv?

**Comment by stefanv** [comment]
I'll close this for now; let's keep an eye out for commonalities in handlers that we can factor out.
