### ISSUE TITLE
Source rescue handler

### ISSUE THREAD

**Issue by guynir42** [skyportal/skyportal#2963]
Maybe useful to write a handler that's only accessible to a sysadmin, 
that can grab all sources in a time range, get all the relevant attached data, 
and be able to re-post all that data later. 

Use case: 
I accidentally deleted something on the current DB. 
I want to restore a DB from yesterday. 
But there are new sources I don't want to lose. 
I can use this handler to GET all the data added in the last 24 hours. 
Then restore a DB backup. 
Then use this handler to POST everything I've downloaded, including original users and all metadata, created_at, etc.

**Comment by guynir42** [comment]
Could also be useful to have another small handler that produces a complete list of source ids, that could be used to figure out which sources need to be re-posted.

**Comment by stefanv** [comment]
This may be easier to have as a standalone script that can operate against databases, storing intermediate state that can be copied. The handler approach is problematic if we do not have both DBs accessible at the same time.
