### ISSUE TITLE
Button to add Gaia plx and BPRP annotation to generate a HR diagram

### ISSUE THREAD

**Issue by janvanroestel** [skyportal/skyportal#2980]
A button is needed that queries Gaia eDR3 and add the plx and BPRP data. If this Gaia data is present, the HR diagram should be automatically generated. Adding this annotation is currently only possible using the API, but users urgently requested that this can be done manually. The button can be similar to the e.g. Milliquaz query button

**Comment by mcoughlin** [comment]
@guynir42 Can we close this?

**Comment by guynir42** [comment]
Closed by #2988
