### ISSUE TITLE
Adding telescope should check for valid latitude and longitudes

### ISSUE THREAD

**Issue by mcoughlin** [skyportal/skyportal#2985]
https://github.com/skyportal/skyportal/blob/main/static/js/components/NewTelescope.jsx

should have a simple check on latitude and longitude.

**Comment by Theodlz** [comment]
Hi @mcoughlin . Should it check if it's null or not, or should it also check that the values are in the correct range ? (i.e -90, 90 for lon, and -180, 180 for lat)

**Comment by Theodlz** [comment]
Should be solved here: https://github.com/skyportal/skyportal/pull/2989

The issue was in fact the elevation, not just lon and lat
