### ISSUE TITLE
Update matplotlib.

### ISSUE THREAD

**Issue by jialin-wu-02** [skyportal/skyportal#299]
For version 2.1.0 matplotlib, it does not support python3.7 anymore.
![image](https://user-images.githubusercontent.com/44333110/68618396-0f75f300-047e-11ea-8695-8db3c7d0c0fe.png)
Should probably update it to the latest one if there is no obvious conflicts.

**Comment by dannygoldstein** [comment]
matplotlib is now pinned to >=3
