### ISSUE TITLE
Export to csv button does not work correctly

### ISSUE THREAD

**Issue by jadalilleboe** [skyportal/skyportal#3002]
The export to csv button on the photometry plot does not work correctly, nothing happens when clicked. should fix and also add regression tests if this was working before some of the recent changes to the photometry plot.

**Comment by mcoughlin** [comment]
xport_csv_button = make_export_csv_button(grouped_data, model_dict, obj_id)

grouped_data: <pandas.core.groupby.generic.DataFrameGroupBy object at 0x168c074f0> 
model_dict: {'ZTF/ztfg/None~unobs0': GlyphRenderer(id='1046', ...), 'ZTF/ztfg/None~obs0': GlyphRenderer(id='1055', ...), 'ZTF/ztfg/None~bin0': GlyphRenderer(id='1064', ...), 'ZTF/ztfg/None~unobsbin0': GlyphRenderer(id='1073', ...), 'ZTF/ztfg/None~obserr0': GlyphRenderer(id='1081', ...), 'ZTF/ztfg/None~binerr0': GlyphRenderer(id='1088', ...), 'all0': ColumnDataSource(id='1106', ...), 'bold0': ColumnDataSource(id='1107', ...), 'ZTF/ztfr/None~unobs1': GlyphRenderer(id='1115', ...), 'ZTF/ztfr/None~obs1': GlyphRenderer(id='1124', ...), 'ZTF/ztfr/None~bin1': GlyphRenderer(id='1133', ...), 'ZTF/ztfr/None~unobsbin1': GlyphRenderer(id='1142', ...), 'ZTF/ztfr/None~obserr1': GlyphRenderer(id='1150', ...), 'ZTF/ztfr/None~binerr1': GlyphRenderer(id='1157', ...), 'all1': ColumnDataSource(id='1175', ...), 'bold1': ColumnDataSource(id='1176', ...)}

The console error gives: Uncaught SyntaxError: Arg string terminates parameters early
with the offending line as: (function anonymous(ZTF/ztfg/None~bin0,ZTF/ztfg/None~binerr0,ZTF/ztfg/None~obs0,ZTF/ztfg/None~obserr0,ZTF/ztfg/None~unobs0,ZTF/ztfg/None~unobsbin0,ZTF/ztfr/None~bin1,ZTF/ztfr/None~binerr1,ZTF/ztfr/None~obs1,ZTF/ztfr/None~obserr1,ZTF/ztfr/None~unobs1,ZTF/ztfr/None~unobsbin1,all0,all1,bold0,bold1,n_labels,cb_obj,cb_data
) 

anything obvious here @jadalilleboe @guynir42 ?

**Comment by jadalilleboe** [comment]
@mcoughlin I have a fix here: [https://github.com/jadalilleboe/skyportal/tree/fix_export_button](https://github.com/jadalilleboe/skyportal/tree/fix_export_button)
The issue was that I changed how the keys are formatted in the model_dict for ease of programatically toggling visibility, but the plotJS functions are expecting the specific old format. However #3012 changes the format of the keys again so the fix will need to be changed with that.

**Comment by mcoughlin** [comment]
@jadalilleboe ahhhh.
