### ISSUE TITLE
Performance of the Observability Page

### ISSUE THREAD

**Issue by robertdstein** [skyportal/skyportal#3014]
I find that most times I attempt to use the Observability page for a source, it does not work correctly. Often the hours above airmass works for some but not all observatories, and then the actual time plot does not appear at all. See attached picture as an example. I have anecdotally found waiting does not fix the problem, at some point the missing plots stop appearing. Perhaps there is a timeout. Selecting a specific telescope does not seem to work for me either, again perhaps because of a timeout,

I *suspect* that the issue is that the page is very slow because too many things are being requested at once (i.e observability for all 66 telescopes). If that is the case, this could very easily be fixed by showing no observability plots at all as a default. The dropdown menu could remain as is, and then people select the right observatory to see the corresponding plot. I anyway find this easier as a user than scrolling through the dozens of plots in search of the correct observatory, so as far as I can tell there would be no drawback to this change.

<img width="1509" alt="Screenshot 2022-05-31 at 7 56 59 PM" src="https://user-images.githubusercontent.com/14312838/171319447-ca1797d3-25b3-4cdc-8070-dd6c178bc231.png">

**Comment by profjsb** [comment]
@robertdstein will you be able to work on this?

**Comment by robertdstein** [comment]
I thought given the javascript requirement this might be a good first issue for my SURF student Leo, when he starts in 2 weeks. In any case, I would certainly value some input about whether my suggested solution sounds like it would actually fix the problem.

**Comment by robertdstein** [comment]
Closed by recent PR https://github.com/skyportal/skyportal/pull/3067
