### ISSUE TITLE
Automating email and SMS notification given specific requirements

### ISSUE THREAD

**Issue by mcoughlin** [skyportal/skyportal#3042]
Right now, we can set allowEmailAlerts and allowSMSAlert (in addition to slack notifications). Best I can tell,  allowEmailAlerts and allowSMSAlerts do not do anything, and their behavior should be merged with the slack infrastructure (where different types of notifications are allowed).

**Comment by mcoughlin** [comment]
@Theodlz Absolutely. And the SMS/calls (we need to have voice as an option) in particular need to have timezone options.

**Comment by Theodlz** [comment]
Like you can be called only between 10AM and 5PM UTC or something ? A user can just set the date as local in a form and we store it in UTC in the db

**Comment by mcoughlin** [comment]
@Theodlz exactly. That's how we had it in the growth-too-marshal. Clearly some of the work on the shifts overlaps here.

**Comment by Theodlz** [comment]
Yeah they could simply be notified by SMS only when they are on shifts or something

**Comment by mcoughlin** [comment]
@Theodlz I don't want to completely tie to shifts, i.e. i know some people will want it every day of their lives. so some setting or if you are shift.

**Comment by Theodlz** [comment]
Ok, so we can add this in  the user preferences : contact by SMS when :

**Comment by mcoughlin** [comment]
@Theodlz can we close this?
