### ISSUE TITLE
Fix up some buttons/text entries following the MUI v5 upgrade

### ISSUE THREAD

**Issue by profjsb** [skyportal/skyportal#3075]
See https://github.com/skyportal/skyportal/pull/3051#issuecomment-1154157040
(cc @mcoughlin)

**Comment by jadalilleboe** [comment]
Regarding the buttons, I think 3 or 4 general use button components should be made and used all throughout the application. Like a blue one for submit/add actions, grey for other actions, and maybe a few others. That would be much easier to deal with/make changes to than 100 mui buttons with varying variants and such

**Comment by mcoughlin** [comment]
Varying varients is very poetic @jadalilleboe
