### ISSUE TITLE
Downloading certain spectra loses flux errors and metadata

### ISSUE THREAD

**Issue by mcoughlin** [skyportal/skyportal#3121]
**Describe the bug:**
For certain sources, downloading a spectrum through the Fritz website (Manage Data -> Spectra -> Download) results in a .csv file that contains only the wavelengths and fluxes. Metadata is viewable for these spectra on Fritz via the "Show Altdata" button on the data page and the flux errors are accessible through the API, but these data are not included in the downloaded file.

Alternative text: When downloading a spectrum manually from Fritz (i.e Manage Data tab) we would like for the file to also contain the spectrum header if it contains any. Currently, the spectrum that is downloaded is a .csv file that only contains the spectrum data (i.e wavelength and flux).

**Examples of affected sources:**
https://fritz.science/manage_data/ZTF22aacrugz (spec ID 6759)
https://fritz.science/manage_data/ZTF22aaabovk (spec IDs 6414, 6425)

**Expected behavior:**
Spectra downloaded from the Fritz website should include the metadata, wavelengths, fluxes, and flux errors.

Alternative text: The download file should either be a .txt file or .ascii file that also contains the header information that is uploaded

Copied from https://github.com/fritz-marshal/fritz/issues/398 and https://github.com/fritz-marshal/fritz-beta-feedback/issues/106

**Comment by jadalilleboe** [comment]
@mcoughlin so is the "spectrum header"? basically the download should be replaced with this original_file_string key?
<img width="739" alt="Screen Shot 2022-09-26 at 11 31 08 AM" src="https://user-images.githubusercontent.com/82007190/192331917-b6dae9a8-b0c0-4da9-83f8-b0a206fa8ab9.png">

**Comment by mcoughlin** [comment]
@jadalilleboe Yeah that is the header, and I guess making it possible to download the header and/or the flux_err would be good.

**Comment by jadalilleboe** [comment]
@mcoughlin so it looks like some spectra don't have the header included in the original_file_string, such as [https://fritz.science/api/spectrum/439](https://fritz.science/api/spectrum/439) I'm guessing because there's multiple ways to upload a spectra, like from an ascii file or not. so is there a way to get the header if it's not in the original_file_string key? The download has the header and flux_err column if it's included in the original_file_string.

**Comment by mcoughlin** [comment]
Ok so in that case, then it seems like things are already behaving as they should! I was just reposting an issue posted in that fritz forum.
