### ISSUE TITLE
More user friendly coordinate search

### ISSUE THREAD

**Issue by mcoughlin** [skyportal/skyportal#3123]
User indicated that searching for a sources requires many small actions and  streamlining this process is requested

**Feature Summary**
Users have coordinates they want to copy paste to search.

**Usage / behavior**
 Fritz should:

- use a single line for coordinates (instead of 1 for ra and one for dec). This allows a single copy-paste of coordinates
- accept coordinate formats: "ra dec" OR "ra, dec" OR "HHMMSS.S DDMMSS.S" OR "HH:MM:SS.S DD:MM:SS.S"

**alternative solution**

**Implementation details**
some custom python code to check to format and maybe astropy coordinates to transform everything to ra dec in degrees?

Copied from https://github.com/fritz-marshal/fritz/issues/276

**Comment by guynir42** [comment]
@nlynn try this one?
