### ISSUE TITLE
Increase size of classification font on source page

### ISSUE THREAD

**Issue by mcoughlin** [skyportal/skyportal#3125]
The classification is shown with very small font size. I recommend increasing it so that it is immediately visible that a transient is classified, since it's currently easy to miss.

Copied from https://github.com/fritz-marshal/fritz-beta-feedback/issues/59.

**Comment by leoyang33** [comment]
I'd like to work on this (cannot assign this to myself on GitHub yet).

**Comment by mcoughlin** [comment]
@leoyang33 We will work on getting it configured such that you can ASAP.
