### ISSUE TITLE
Annotation sorting

### ISSUE THREAD

**Issue by mcoughlin** [skyportal/skyportal#3127]
**Description:**
When sorting using the drop menu from the "Annotation Sorting" section, the sorting doesn't work. However, when pressing on the icon directly above the objects, the sorting works. (in the picture, 1 doesn't work, 2 does work). 

**screenshot:**
![issue_fritz](https://user-images.githubusercontent.com/43962165/135758883-cc2e1def-6fa9-4551-910f-90b5db678339.png)

Copied from https://github.com/fritz-marshal/fritz-beta-feedback/issues/114

**Comment by santier14** [comment]
@Adiman007 @mcoughlin still needed ?

**Comment by mcoughlin** [comment]
I am closing this for now.
