### ISSUE TITLE
Smaller GW event

### ISSUE THREAD

**Issue by mcoughlin** [skyportal/skyportal#3128]
Find one.

**Comment by robertdstein** [comment]
So one thing I didn't understand was why we couldn't use 190814bv. @mcoughlin could you explain the constraints on what the GW event are?

**Comment by mcoughlin** [comment]
@robertdstein its probably fine, the localization is tiny and in the South

**Comment by mcoughlin** [comment]
We are using GW190814 now in the demo data. Let's see if that takes care of enough issues.
