### ISSUE TITLE
Add GLADE catalog to demo data

### ISSUE THREAD

**Issue by mcoughlin** [skyportal/skyportal#3142]
http://glade.elte.hu/

Right now our demo data is too small to be useful for development.

**Comment by StephenTheCoder** [comment]
So I was trying to fix this issue but the GLADE+ file was pretty large (about 6.2 GB) and my computer had a tough time compiling it and Github was acting slow. I'll send the directions here so people with a better device can fix it and hopefully not experience the slowness from Github.

1) Open up GLADE's website and download GLADE+ 

2) Put GLADE+ in the Skyportal folder in GitHub

3) Replace db_demo.yaml lines 512 and 514
Old:
511 galaxy_catalog:
512  - catalog_name: CLU_mini
513    catalog_data:
514      file: ../data/CLU_mini.hdf5
New:
511 galaxy_catalog:
512  - catalog_name: GLADE+
513    catalog_data:
514      file: ../data/GLADE+.txt

4) Save it and add it to current branch

5) Run pre-commit and then commit the file

6) Push it and add a PR to fix the issue.

Hopefully this helps!

**Comment by mcoughlin** [comment]
@StephenTheCoder Can you start by taking say the first 100 lines of the catalog and seeing if that posts OK?

**Comment by mcoughlin** [comment]
Thanks @StephenTheCoder. My guess is the header will need to be modified a bit so the right columns go in (name, ra, dec, etc.).

**Comment by StephenTheCoder** [comment]
I made a PR with the 100 lines (and accidentally added test_post.py). I ran pre-commit so hopefully there are no errors.

**Comment by Theodlz** [comment]
One thing we could do to, a bit more complicated but I'll be happy to give you some help or at least find some ressources on how to do it, would be to use heapix coordinates, or a Fibonacci sphere to have evenly spaced points on a sphere. Then, you can iterate on those points  calculate their ra and dec coordinates and for each point find the first galaxies that is close enough to it. That way we can obtain a subset of the glade catalog, with galaxies all around the skymap, evenly spaced, so we can be pretty sure that any event will have some galaxies within its localization.

**Comment by Theodlz** [comment]
I wrote a quick jupyter notebook with some stuff that could help. Just tell me if you are interested @StephenTheCoder
