### ISSUE TITLE
Individual GCN Event page loads indefinitely

### ISSUE THREAD

**Issue by leoyang33** [skyportal/skyportal#3146]
When clicking on a date on the GCN Events page, the resulting page does not load. Seems to be a server issue as it works on a local instance.

**Comment by mcoughlin** [comment]
@leoyang33 we know about some performance issues we have been pushing on over the last week to improve. We will see how things look after Monday and reassess.

**Comment by mcoughlin** [comment]
It's loading currently, still a bit on the slow side. I think we would benefit from a bit more RAM.
