### ISSUE TITLE
Update documentation to reflect Postgres 14 requirement

### ISSUE THREAD

**Issue by robertdstein** [skyportal/skyportal#3198]
Following a string of PRs, skyportal is now only compatible with Postgres 14. The docs should be updated to reflect that.

**Comment by robertdstein** [comment]
Also need to update docker-compose.yaml? https://github.com/skyportal/skyportal/blob/main/docker-compose.yaml#L13

**Comment by mcoughlin** [comment]
@robertdstein I did open a PR for that last week actually.

**Comment by robertdstein** [comment]
> Also need to update docker-compose.yaml? https://github.com/skyportal/skyportal/blob/main/docker-compose.yaml#L13

This bit solved by #3151
