### ISSUE TITLE
Allow Source Table to filter by Localizations

### ISSUE THREAD

**Issue by mcoughlin** [skyportal/skyportal#3207]
In GcnSelectionForm.jsx, we can filter sources by Localizations and time.

In SourceTableFilterForm.jsx, we can filter by almost everything but Localizations.

We should:
(i) modify the SourceTableFilterForm.jsx to also filter on Localizations.
(ii) Consider using this table in place of the GcnSelectionForm, which is much more limited in capability.

**Comment by mcoughlin** [comment]
@Theodlz Anything else we want to do here? Is there any traction with option (ii) or is that form here to stay?

**Comment by mcoughlin** [comment]
@Theodlz ping. Otherwise I think we close.

**Comment by Theodlz** [comment]
We should talk about (ii). I'm not sure I understand how we could replace the selection form by this, considering that the gcn selection form is here to use other params like the cumProb and such, and also to query galaxies and obs.

Coming back to the cumprob, right now it is fixed to 0.95 when filtering by event. We could add that to the SourceTableFilterForm.jsx I guess (making it required when filtering by event)?

**Comment by mcoughlin** [comment]
@Theodlz yeah it was a dumb idea. But the cumulative probability in the form would be good.
