### ISSUE TITLE
Add tests for Analysis Service page

### ISSUE THREAD

**Issue by profjsb** [skyportal/skyportal#3232]
Following #3193, we need to test a few things: 

  1) that an admin or someone with a Manage Services auth can add/delete analysis services
  2) that a user without proper permissions can only view analysis services
  3) that when a new analysis service is added via the API that it shows up in the dropdown menu

(@mcoughlin please assign this issue as you see fit)

**Comment by mcoughlin** [comment]
Fixed in https://github.com/skyportal/skyportal/pull/3233
