### ISSUE TITLE
Make GcnEvents table sortable by column

### ISSUE THREAD

**Issue by mcoughlin** [skyportal/skyportal#3238]
Currently sorting does not do anything.

**Comment by mcoughlin** [comment]
@Theodlz Anything more to be done here?

**Comment by Theodlz** [comment]
Hey @mcoughlin. In the last PR i added the frontend and backend necessary to start implementing the sorting. Then, the only one I added is the sorting by dateobs. I'm not sure what we could sort the event by? We can definitely filter them (that's something to add next for sure). We talked about the tags but even then I'm not sure it really works. If events had ONE tag each maybe we could sort by alphabetic order, but here what could we do?

**Comment by mcoughlin** [comment]
@Theodlz ah yes filtering is the clear thing to be doing. Good point on that.
