### ISSUE TITLE
Can't assign targets to run on same day

### ISSUE THREAD

**Issue by robertdstein** [skyportal/skyportal#3249]
In the same vein as #3073, you presently cannot assign targets to a run that has already happened, but the run is assumed to have finished at 00:01 on the assigned run date. I would suggest we mimic #3073, and set the default behaviour for assigning a source to be "all observing runs except those which began >24 hours ago".

**Comment by virajkaram** [comment]
This is pretty frustrating for several users. Would really appreciate if this was fixed soon.

**Comment by mcoughlin** [comment]
@virajkaram Please submit a PR.

**Comment by robertdstein** [comment]
I think this would require knowledge of javascript/react/frontend for a fix, right? Not sure about @virajkaram but I definitely am lacking the expertise here.
