### ISSUE TITLE
GcnEvent Names

### ISSUE THREAD

**Issue by mcoughlin** [skyportal/skyportal#3257]
For now, we track everything by dateobs, which is a convenient ground truth for events. However, events will be much more commonly known by their GRB or GW name. Unfortunately, these names aren't assigned until later and not usually in an easy programmatic way, so we need to:

(i) Add a column to models/gcn.py called display_name or similar.
(ii) Add a new permission called "Manage gcns" or similar
(iii) Add a front-end element where the display name can be set if you have this permission
(iv) Modify the Recent Gcn Events and Gcn Events table to show this name in a new column
(v) Make it possible to filter the GcnEvents table by this name

**Comment by robertdstein** [comment]
I think this directly overlaps with what @leoyang33 was already working on. One key point I would make: I do not think  it is a good idea to bake in the idea that there is a unique name for each event (a la classifications). Instead we should code up something that allows multiple names (GW170817, GRB170817A, AT2017gfo) for a single event.

**Comment by mcoughlin** [comment]
@robertdstein @Theodlz ah that's nice, like aliases or similar? And allow it to be a list?

**Comment by robertdstein** [comment]
Yes exactly. The names can then be used to parse the circulars associated to that name (e.g https://gcn.gsfc.nasa.gov/other/220724A.gcn3)

**Comment by Theodlz** [comment]
Sounds great! Its quite easy to have a column on the gcn event table that is a list of strings.
Unless leo is already working on it, I'll be happy to open a PR.

**Comment by robertdstein** [comment]
@leoyang33 is indeed already working on this, so can we assign this to him instead? I hope it doesn't conflict with any work you already did @Theodlz.

**Comment by Theodlz** [comment]
Not at all! Let's assign him.

**Comment by Theodlz** [comment]
For some reason, I'm not able to assign him. Maybe @mcoughlin can ?

**Comment by robertdstein** [comment]
I think none of the SURF students are in the Skyportal organisation, so we cannot directly assign issues to them. We were doing it exclusively via comments thus far. So maybe we just say "This issue is officially assigned to @leoyang33".
