### ISSUE TITLE
Default time range for scanning is unclear

### ISSUE THREAD

**Issue by robertdstein** [skyportal/skyportal#3269]
The default times on the candidate scanning page appear to be "from 24 hours ago to now". An example:

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/14312838/181116997-0ec73493-0680-4fce-a7f0-49fcf099e538.png">

While that all looks reasonable, this screenshot comes from my laptop in California, not in a UTC timezone. The scanning page very explicitly states that the times are in UTC.

So either:

- The default end time is not "the time now, in my timezone" but instead "the time now, in the UTC timezone". Obviously that would be very bad/confusing default behaviour.
- OR the default is indeed "Now", in which case the labels on the time boxes are wrong. In that case, we should fix the labels.

**Comment by jadalilleboe** [comment]
@vyom1611 this would be a good one as well

**Comment by vyom1611** [comment]
Would it be better to add a Time zone label for your current Time zone or just remove the "UTC" ?
