### ISSUE TITLE
Source list ordering is inconsistent

### ISSUE THREAD

**Issue by acrellin** [skyportal/skyportal#327]
From Danny Goldstein: 

To reproduce:
1. Scroll to some page != 1
2. Note the source at the top of the page
3. Keep scrolling to a future page
4. Click on some source on that page
5. Click the back button
6. Keep scrolling, eventually you will see the source from step 2 at the top of the page

Perhaps the current page number is getting cleared when navigating away from source list page

**Comment by acrellin** [comment]
@dannygoldstein I wasn't able to reproduce this. I clicked away to a specific source page, then came back and kept paging through the results, and never encountered a duplicate until I paged back to the original page it appeared on.

**Comment by acrellin** [comment]
@dannygoldstein is this while sources are actively being added to the DB?

**Comment by dannygoldstein** [comment]
Sorry just saw this now. No, I was not actively adding sources to the DB. But many sources did all have the same score. It appears to be fixed when there is a clearer definition of the source ordering (i.e., most sources have a different score).

**Comment by acrellin** [comment]
@dannygoldstein  have you seen this occur at all in recent months?

**Comment by dannygoldstein** [comment]
Nope, haven't seen this in a while.
