### ISSUE TITLE
Reminders - Notifications Preferences

### ISSUE THREAD

**Issue by Theodlz** [skyportal/skyportal#3324]
We added reminders in SkyPortal, and it would make sense to integrate them with the Notification Framework.
That means adding code to the `user_notification.py` model and to the `NotificationPreferences.jsx` so users can choose if they want to be notified on reminders by email, SMS and/or slack, just like any other notification type.

**Comment by astitvaveergarg** [comment]
Hello There, I am intrested to take up this issue, but i need to get a background Idea of the Thing. Can We have a Meet?

**Comment by mcoughlin** [comment]
In short, you need to add to the list here https://github.com/skyportal/skyportal/blob/main/skyportal/models/user_notification.py#L312 to listen for Reminders https://github.com/skyportal/skyportal/blob/main/skyportal/models/reminder.py#L103 

Then you need to add to https://github.com/skyportal/skyportal/blob/main/static/js/components/NotificationPreferences.jsx#L74 an option for the Reminders.

We will have an onboarding meeting in September.

**Comment by astitvaveergarg** [comment]
Well This looks fine For me, however I may take sometime to understand and checkout how the things Work, Please Do assign me the issue, and I will Start Working on the Same.

**Comment by mcoughlin** [comment]
Go ahead @astitvaveergarg. Just saying you want to work on something in an issue is enough.

**Comment by astitvaveergarg** [comment]
Sure Thanks.
