### ISSUE TITLE
Galaxy Page - Issue with the list of galaxies

### ISSUE THREAD

**Issue by Theodlz** [skyportal/skyportal#3325]
The galaxy page seems to show more galaxies at once than it should (as if it wasn't using the pagination correctly). This results in slowdowns of the frontend (maybe even the backend), and the list not loading correctly.

**Comment by StephenTheCoder** [comment]
It seems to be that the first page is showing a ton of galaxies but when you go to the second page, the problem seems to be resolved (and it seems to fix after going back to the first page). I encountered this bug on Fritz's GCN Events page as well.
