### ISSUE TITLE
saved archival photometry does not appear on source page

### ISSUE THREAD

**Issue by janvanroestel** [skyportal/skyportal#3326]
bug: I tried to use the Fritz portal 'archive' tab to save a new source with photometry, which did save a new source, but no lightcurves appeared. I tried again to save 4 lightcurves to this new source, but again no lightcurves appeared (I did get an error message only saying "2"). I then tried to save photometry via the API (python code that worked a few months ago). The response is "200" for the PUT photometry API call, but again, nothing appeared on the Fritz source page. 

The source I tried this for is: https://fritz.science/source/ZTFJ064618.65+395838.0
![image](https://user-images.githubusercontent.com/10774087/183640154-73c89955-a281-4450-ae6a-e83d14ee935c.png)

**Comment by mcoughlin** [comment]
@janvanroestel is the main issue that there is no new photometry? Because there is a lot of photometry in the figure.

**Comment by mcoughlin** [comment]
I am going to close now, feel free to reopen if reproducible.
