### ISSUE TITLE
Group Sources CSV fails to download

### ISSUE THREAD

**Issue by bfhealy** [skyportal/skyportal#3363]
After clicking "Download CSV" above a list of sources within a group, the CSV download does not start.

**Comment by mcoughlin** [comment]
Got this one in #3364. Feel free to reopen post next deploy if it does not meet the needs.

**Comment by bfhealy** [comment]
Thanks Michael - the download button is working now, but it provides a CSV of sources from the sitewide group, rather than the user's current group.

**Comment by mcoughlin** [comment]
@bfhealy can you check again today? We deployed again last night and I think I got the fix in.

**Comment by bfhealy** [comment]
@mcoughlin Yes, downloads are working well now! Thanks!
