### ISSUE TITLE
Inconsistency when filtering sources by comment

### ISSUE THREAD

**Issue by bfhealy** [skyportal/skyportal#3365]
Filtering sources by the Comment, Comment Author and Comment Created (UTC) fields produces inconsistent results. Some comments are successfully found, but many are not. If additional information like the source ID or classification is included in the filter, the comment filters work as expected.

**Comment by mcoughlin** [comment]
@bfhealy Could you maybe take a little gif and post it to show us what you mean?

**Comment by bfhealy** [comment]
Sure, here's a gif of searching for a comment with and without the source id:
![fritz_comment_filter](https://user-images.githubusercontent.com/42810347/185241591-6a4da382-8515-4316-b4f2-818230851db4.gif)

**Comment by bfhealy** [comment]
The same happens when filtering by the text of the comment or post date.

**Comment by mcoughlin** [comment]
@bfhealy Close if complete?

**Comment by mcoughlin** [comment]
@bfhealy We also have now fixed annotation queries, so should be able to make effective API queries against multiple annotation flags now: https://github.com/skyportal/skyportal/blob/main/skyportal/tests/api/test_sources.py#L1966

**Comment by bfhealy** [comment]
@mcoughlin Nice, that will be helpful! On the topic of annotations, I was thinking it would be worth my time to write a script that posts updated annotations, for example to correct an uploaded period on Fritz.

**Comment by mcoughlin** [comment]
@bfhealy agree!
