### ISSUE TITLE
Persistent data

### ISSUE THREAD

**Issue by mcoughlin** [skyportal/skyportal#3386]
We should have one folder in the config that corresponds to all the permanent data (like the thumbnails) but for the analysis framework, data on disk, etc as well.

**Comment by profjsb** [comment]
I agree with this and have a local PR for this in the works.

**Comment by stefanv** [comment]
W.r.t. backing up with snapshots.

Snapshots are either "crash consistent" (as if the machine crashed) or
"application consistent" (shut down app, did backup).  Crash
consistent should be fine for us.

Still need to look into how to remove older backups.

**Comment by Theodlz** [comment]
We have this persistent directory now (specified in config, and on a persistent volume in production). Closing.
