### ISSUE TITLE
Posting revised period annotations 

### ISSUE THREAD

**Issue by bfhealy** [skyportal/skyportal#3389]
A beneficial new feature would be the ability to add/revise a period annotation via the Photometry section of a Source page. Placing a button near the *2 and /2 buttons would be a logical spot to allow new periods to be posted quickly. Where there is already an existing 'uploadedperiod' annotation, it may be beneficial to keep it and add something like 'revisedperiod' as a new annotation.

**Comment by mcoughlin** [comment]
@thomasculino @Theodlz What is the best path forward for this? https://github.com/skyportal/skyportal/blob/main/skyportal/plot.py#L1293 
Looks like you push data to .js scripts. Do you expect that a refactor of the annotation handler (to make it possible to import a post_annotation or similar) and then calling that is doable from this stuff? Or what is the most reasonable path forward?

**Comment by jadalilleboe** [comment]
@mcoughlin yes I think it would be reasonable to be able to make an api call from the .js scripts. See this for an example: [https://github.com/skyportal/skyportal/blob/main/static/js/plotjs/update_data_point_size.js](https://github.com/skyportal/skyportal/blob/main/static/js/plotjs/update_data_point_size.js) we use the fetch api.

**Comment by mcoughlin** [comment]
@Theodlz this might be a good first PR for the new group of students. What do you think?
