### ISSUE TITLE
Downloading additional source information

### ISSUE THREAD

**Issue by bfhealy** [skyportal/skyportal#3396]
In addition to the current columns provided in the file from a 'Download CSV' request for sources, users may benefit from having the option to download additional information like classification probabilities and annotations. Adding this functionality to downloads via the frontend would complement programmatic access to this information.

**Comment by jadalilleboe** [comment]
Hi @bfhealy do you mean adding these columns to the csv that's already being generated or creating new options to download specifically classification probabilities and annotations? And for annotations is that the data in the "Auto-annotations" table on a specific source page?

**Comment by jadalilleboe** [comment]
@bfhealy So I see annotations data has this structure:
<img width="398" alt="Screen Shot 2022-09-19 at 12 32 21 PM" src="https://user-images.githubusercontent.com/82007190/191078430-a7b60153-fb0c-45c8-a965-84c55a047a56.png">
I'm confused about the key-value thing, how would we want this structured in the csv?

**Comment by bfhealy** [comment]
@jadalilleboe I'm thinking that annotation values could be placed in a column named for the key and separated by a semicolon if necessary. This convention is analogous to the classification/probability columns that are currently downloaded. Below is a visualization of a few rows downloaded using my scope script.

If there are multiple period origins (e.g. 'revisedperiod' in addition to 'uploadedperiod', I'm thinking they could be added to the existing period_origin and period columns with a semicolon in between. The key for both of those origins is called 'period', so using the same column for both periods seems appropriate.

<img width="1114" alt="Screen Shot 2022-09-19 at 1 07 10 PM" src="https://user-images.githubusercontent.com/42810347/191084680-24709a6d-e226-4ce8-bdd8-d5377cc5e3b4.png">
