### ISSUE TITLE
Displaying subclasses for slider classification

### ISSUE THREAD

**Issue by bfhealy** [skyportal/skyportal#3398]
On group source pages, the dropdown accessed to the left of each source id shows additional information and allows quick classification of the source using sliders to assign probabilities. Especially for the stellar variable taxonomy branch, there are many subclasses that are all displayed each time a user opens that classification dropdown.

Users could spend less time scrolling through these subclasses, many of which will not be pertinent to a given source, with a modification to the way the subclasses are displayed. One solution without adding more dropdown menus (extra clicking) is to only display the children of a parent class if the parent has a nonzero probability: for an unclassified source, using the current taxonomy, the user might only see Cataclysmic - Eclipsing - Rotating - Eruptive - Pulsating - microlensing under Stellar variable.  The subclasses would become visible if one or more of these sliders is moved to a nonzero probability.

See #2366 for another discussion about the slider classification system.

**Comment by jadalilleboe** [comment]
@vyom1611 this would be a good one for you
