### ISSUE TITLE
Classifications Documentation

### ISSUE THREAD

**Issue by bfhealy** [skyportal/skyportal#3431]
Currently, if I filter sources by non-classification A, I will still see sources that have multiple classifications including A, B, etc. The filter will only exclude sources if A is the sole classification. To make this filtering more consistent with filtering by existing classifications, we could change the behavior to exclude sources if A is in the list of classifications.

**Comment by mcoughlin** [comment]
This is now complete. @bfhealy, could I ask you to open a PR on skyportal in the docs (probably adding a new page) giving some documentation as to how to effectively interact with the classifications APIs and such? We can expand it as the labeling tools get built out with @jadalilleboe and others.

**Comment by bfhealy** [comment]
@mcoughlin Sure thing, I'll put together a new documentation page for that.
