### ISSUE TITLE
Installtion problem in macOS12.

### ISSUE THREAD

**Issue by harshkumar13** [skyportal/skyportal#3499]
During the installation of system dependencies, following error is encountered on macOS:- 

command: "brew install supervisor nginx postgresql node  llvm libomp gsl rust"
Output:
<Error: You are using macOS 12.
We do not provide support for this pre-release version.>

Seems like the current version is not supported on macOS12

**Comment by harshkumar13** [comment]
Hi,

Thanks for thw suggestion. I looked into the issue a bit more. I updated
brew and problem still persist. Looks like the problem is with xcose in my
pc. I will try to resolve it first and get back to you if it remains the
same.


Regards,

**Comment by mcoughlin** [comment]
Feel free to reopen as necessary.
