### ISSUE TITLE
Duplicate rows in group source downloads

### ISSUE THREAD

**Issue by bfhealy** [skyportal/skyportal#3516]
When downloading group sources from Fritz using the frontend or api, the result sometimes contains duplicate rows (although always the correct number of total rows, so some sources are missing). I have not encountered this problem for smaller groups (<~ 1000 sources), but for larger groups I get a variable number of duplicates each time I download. Some additional info:
- There are no duplicates on any single page; they instead appear on separate pages.
- The number of duplicates increases for a large ratio of total sources to number per page.
- I have been unable to replicate this behavior on my local SkyPortal instance, including in scenarios where sources are members of multiple groups or other sources are in the process of being posted.

It is possible that modifying this call of `grab_query_results`:
https://github.com/skyportal/skyportal/blob/91a293fada374b87d7285294199dfbfbf7c25ef2/skyportal/handlers/api/source.py#L1026

by setting `use_cache=True`, see
https://github.com/skyportal/skyportal/blob/03f7c79afbe0bedde859ff1a94355f9644da7298/skyportal/handlers/api/candidate.py#L1234

will solve the problem. We'd also have to decide on how long to maintain the cache.

**Comment by mcoughlin** [comment]
@guynir42 What do you think of trying this and seeing how it goes this week?

**Comment by guynir42** [comment]
You mean adding `use_cache=True` to the download CSV option?

**Comment by mcoughlin** [comment]
@guynir42 yes.

**Comment by bfhealy** [comment]
Unfortunately PR #3569 has not resolved the duplicate row issue with Fritz. I am still unable to replicate the issue locally.

**Comment by bfhealy** [comment]
Testing on a group of ~10,000 sources in preview did not produce any duplicates. It seems this issue is specific to fritz.science.
