### ISSUE TITLE
Incorrect API documentation for `api/group.py`

### ISSUE THREAD

**Issue by stefanv** [skyportal/skyportal#352]
https://skyportal.io/docs/api.html#/paths/~1api~1groups~1group_id/get

https://skyportal.io/docs/api.html#/paths/~1api~1groups/get

Returned JSON has different fields

**Comment by acrellin** [comment]
Can you explain what the issue is? This isn't clear.

**Comment by stefanv** [comment]
The fields returned are different from those described in the docstrings.

**Comment by acrellin** [comment]
@stefanv we need to figure out a way to nest our model schemas as properties of larger dictionaries, ideally in a general way across all our API docs. Currently this issue applies to many of the API docs. In the API docs we have: 
```
          responses:
            200:
              content:
                application/json:
                  schema: SingleGroup
```
but the response body's JSON is actually of the form
```
{'status', 'success',
'data': {'group': {...} }
``` 
Let's chat about how to update our schemas accordingly

**Comment by acrellin** [comment]
Also, I see that for the groups endpoint, the docs issue is threefold: a) the issue described in the previous comment, b) the schema includes more relationships than are actually shipped, and c) our GET `api/groups` endpoint is a hack-job from the early SkyPortal days that returns "user_groups" and "all_groups", which should probably be split into separate queries or moved to a private endpoint.
