### ISSUE TITLE
Fix scary cross UI

### ISSUE THREAD

**Issue by jadalilleboe** [skyportal/skyportal#3526]
Used in a few places in the app. Maybe change to a trash can or something more intuitive
![2022-09-30_09_50_20](https://user-images.githubusercontent.com/82007190/193322281-5ca9fc43-5722-4dfd-b4b9-9a3369f2691d.png)

**Comment by stefanv** [comment]
Also ensure that clicking on the button does not delete directly, but asks for confirmation (may already be the case).

**Comment by mcoughlin** [comment]
Got this one.
