### ISSUE TITLE
Improve rendering of descriptions on "list" type pages

### ISSUE THREAD

**Issue by jadalilleboe** [skyportal/skyportal#3527]
![2022-09-30_09_52_14](https://user-images.githubusercontent.com/82007190/193322740-cd615d7c-9062-47d6-a9a1-2def6144f946.png)
Improve filters list display
![2022-09-30_09_53_00](https://user-images.githubusercontent.com/82007190/193322742-f75551cf-5ce7-496b-af1e-ecb53c9bbedf.png)
Unordered lists should be rendered using MUI primitives
![2022-09-30_09_59_42](https://user-images.githubusercontent.com/82007190/193322891-670b9bbf-927d-436f-99b1-8e3008721123.png)

**Comment by santier14** [comment]
@jadalilleboe @mcoughlin @Adiman007 something reachable by France ? Also on the same thing on the name of GCN. I said to @Theodlz that I hate having a GCN event mamed  "2022-09-30". but better GW20220930 ? I think @Theodlz added some alias

**Comment by Theodlz** [comment]
Hi @santier14 , the aliases of an even also have a dedicated column to be displayed in the events list. For sure we can do something like: if there is no aliases we display the longer name (trigger time), but if there is one we display it that instead?

**Comment by Theodlz** [comment]
This if condition to display the alias if it exists is probably just a matter of modifying one line of code!

**Comment by Theodlz** [comment]
We already have individual issues opened to fix these lists, closing this one
