### ISSUE TITLE
Several spots with missing padding

### ISSUE THREAD

**Issue by jadalilleboe** [skyportal/skyportal#3528]
![2022-09-30_10_01_00](https://user-images.githubusercontent.com/82007190/193323243-a301439f-bcc2-48a1-ad74-8438a6e97146.png)
![2022-09-30_10_05_54](https://user-images.githubusercontent.com/82007190/193323288-88cd735d-aacf-4c33-8443-761d23e22c22.png)
![2022-09-30_09_59_01](https://user-images.githubusercontent.com/82007190/193323655-d40deb18-8319-442e-8be0-33a5eaecd673.png)

**Comment by Theodlz** [comment]
Those have all been fixed
