### ISSUE TITLE
Jumpy scrolling in source classifications

### ISSUE THREAD

**Issue by bfhealy** [skyportal/skyportal#3533]
When scrolling to the bottom of a source's classification list, the menu jumps around and some classifications are difficult to reach.

![classification-scrolling](https://user-images.githubusercontent.com/42810347/193338088-4118a0d3-fd6f-4517-abf8-8d86b19e6613.gif)

**Comment by mcoughlin** [comment]
@bfhealy I think I got this one when updating the delete stuff. The List box wasn't quite big enough.
