### ISSUE TITLE
Failing tests for shifts

### ISSUE THREAD

**Issue by guynir42** [skyportal/skyportal#3561]
The following tests have been failing since last week. 
Has something to do with posting shifts on the frontend.
skyportal/tests/frontend/test_reminders.py::test_reminder_on_shift
skyportal/tests/frontend/test_reminders.py::test_reminder_on_sources
kyportal/tests/frontend/test_shifts.py::test_shift

**Comment by mcoughlin** [comment]
These seem to be passing now.
