### ISSUE TITLE
Filter by non-classification sometimes times out

### ISSUE THREAD

**Issue by bfhealy** [skyportal/skyportal#3602]
When filtering group sources by non-classification, if the specified classification is common among the sources, the query will time out and throw a 504 error (followed by a JSON decoding error, e.g. #3574). This happens locally and on Fritz. Filtering by classification using the same label does not time out.

**Comment by mcoughlin** [comment]
I guess the difference comes down to: https://github.com/skyportal/skyportal/blob/main/skyportal/handlers/api/source.py#L680
vs.
https://github.com/skyportal/skyportal/blob/main/skyportal/handlers/api/source.py#L740

Maybe just so much more not in vs. in.

**Comment by mcoughlin** [comment]
I think this is mostly now addressed. Feel free to reopen.
