### ISSUE TITLE
Replace aplpy with astropy.visualziation.wcsaxes

### ISSUE THREAD

**Issue by lpsinger** [skyportal/skyportal#361]
Aplpy is used for generating thumbnail images from FITS files. This can be done just as easily these days with astropy.visualziation.wcsaxes, with fewer dependencies. Also, aplpy does not seem to be very actively maintained these days.

**Comment by profjsb** [comment]
Might be a good quick fix but note that we're planning on using js9 eventually (https://js9.si.edu/).

**Comment by dannygoldstein** [comment]
aplpy is no longer used
