### ISSUE TITLE
Github Actions Migrations

### ISSUE THREAD

**Issue by mcoughlin** [skyportal/skyportal#3652]
The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by Theodlz** [comment]
Are you referring to https://github.com/skyportal/skyportal/blob/main/.github/workflows/test_migrations.yaml? If looks like it has been updated since then. At least the syntax looks like the updated one.

**Comment by mcoughlin** [comment]
Thanks @Theodlz ! this was just an old message i noted back then.
