### ISSUE TITLE
Reintroduce exact redshift and velocity shift to the spectra tile via direct input box

### ISSUE THREAD

**Issue by erezimm** [skyportal/skyportal#3669]
Hi,

In the last update the spectra tile in the object page was updated to include sliders instead of an input box for the redshift, velocity and smoothing.
This is inconvenient to testing exact redshift (and velocities) in a resolution lower than one slider tick (and the slider tick is very high for local universe studies at ~0.01).
This makes this feature unusable for any object without a stated redshift.

Thank you,
Erez

**Comment by mcoughlin** [comment]
<img width="833" alt="Screenshot 2022-11-14 at 6 26 02 AM" src="https://user-images.githubusercontent.com/2291947/201659689-bfef4a07-3af3-4f5c-93a5-7da266e80408.png">

Just inputting a number and clicking enter seems to work fine. What are you seeing?

**Comment by erezimm** [comment]
Ahh I see now that it is not visible on mobile properly since one need to scroll to see the input boxes (I was working looking on an ipad)
![image](https://user-images.githubusercontent.com/53300818/201688308-348694de-9bb6-48d3-aa21-dc5a6f6f9098.png)

Maybe the proportions could somehow be changed?

Thanks!

**Comment by mcoughlin** [comment]
@erezimm I think the main issue is that "mobile" is hard to handle because the size of the windows vary. Maybe @guynir42 has ideas?

**Comment by guynir42** [comment]
@mcoughlin I mean, we could make the new buttons a little smaller in the vertical direction, that may be enough to pull the input box into view for at least some of the mobile devices. In terms of overall view these buttons do take up a lot of space. 
I would say that I don't know if there is any way to make sure those boxes are always in view but they should be scrollable at least.

**Comment by mcoughlin** [comment]
@erezimm Since they are scrollable, I guess your issue is that the plot scrolls out of view when you change the redshift? What if instead the sliders were above the buttons?

**Comment by erezimm** [comment]
I'm not sure if the sliders above the buttons make sense - the first thing we usually check is for lines since and then play with the velocity and redshift - so it makes sense to have the lines above the sliders.
But once knowing the input boxes are there i guess this isn't really an issue. My problem was that on mobile (and on an ipad apparently) there was no indication that the spectrum tile is scrollable, while it was quite clear on a desktop browser.
I'm not sure how many people make the same mistake and generally i think it would be better for the tiles to be all shown at once instead of scrollable, but it's definitely not a big issue.

Thanks for the quick replies!

**Comment by guynir42** [comment]
@mcoughlin Another thing we could do is just make sure the accordion opens up tall enough to contain all the components no matter what. It would push down the other accordions just a little and would save the users a lot of trouble. I don't know how to do that, but maybe there is some JS magic for that.

**Comment by mcoughlin** [comment]
@jadalilleboe ?
