### ISSUE TITLE
ZTF Forced Photometry integration

### ISSUE THREAD

**Issue by robertdstein** [skyportal/skyportal#3672]
It would be great if ZTF forced photometry could be requested directly through Fritz, similar to ATLAS.

Yashvi Sharma and Tomas Ahumada have already volunteered to tackle this.

**Comment by mcoughlin** [comment]
We already have this for the IPAC service, see the docs.

**Comment by robertdstein** [comment]
https://youtu.be/OVVjRkmF1EM
