### ISSUE TITLE
Starlist fails to generate in some cases

### ISSUE THREAD

**Issue by robertdstein** [skyportal/skyportal#3685]
For some objects, the finder chart cannot be generated. A message appears to say generation is in progress, but then opens an empty tab with no finder (see e.g https://fritz.science/source/ZTF22abrahwy or https://fritz.science/source/ZTF22abkpgye). If those objects are assigned to an observing run, the starlist cannot be generated and an error message appears `Can only get separation to another SkyCoord or a coordinate frame with data` (see e.g https://fritz.science/run/1338). 

My GUI looks like this:

<img width="1507" alt="image" src="https://user-images.githubusercontent.com/14312838/202346533-f4fa65d1-1e13-4335-8f13-87dcccfe9de5.png">

**Comment by mcoughlin** [comment]
@robertdstein I am trying to add a bit more error handling here: https://github.com/skyportal/skyportal/pull/3686
Of course, all the servers seem fine this morning, so hard to rule out there may be other issues.

**Comment by mcoughlin** [comment]
Will close for now. Reopen if you see again.
