### ISSUE TITLE
Super-admins see all classifications regardless of group membership

### ISSUE THREAD

**Issue by bfhealy** [skyportal/skyportal#3736]
Currently, super-admins see classifications and receive notifications about new ones even when they are posted only to groups of which the super-admin is not a member. This could be the intended behavior, but I am posting this issue to make sure in light of recent dev team discussions.

**Comment by mcoughlin** [comment]
@bfhealy I think it is the notification part that seems unnecessary. @Theodlz Is this trivial to filter out?

**Comment by Theodlz** [comment]
Hi @mcoughlin and @bfhealy

Yes, it seems trivial enough. In the models, it is defined that super admins have access to anything, so naturally, they receive said notifications for any object. 
I guess the only thing to add is when we loop through users that are interested in being notified for a given classification (which is on a given source), verifying that they have access to said source, which means verifying that their groups are in the groups that have access to it.

I can take care of that issue unless someone else wants to?

**Comment by mcoughlin** [comment]
@Theodlz If it is quick for you, then I think that is great.

**Comment by santier14** [comment]
@mcoughlin @Adiman007 @Theodlz can you think France can help on this issue pls ?

**Comment by Theodlz** [comment]
You mean if the students can do it? If that's you question then yes. They just need to modify the method that creates user notifications (more specifically the bit of code that does that for new classifications) to verify that the users do not just have access to the classification in the db, but instead are part of the group it was posted to.

**Comment by Theodlz** [comment]
Super admins do not seem to be notified about classifications they didn't ask notifications for anymore. Closing.
