### ISSUE TITLE
Update taxonomy group ids - PATCH method

### ISSUE THREAD

**Issue by bfhealy** [skyportal/skyportal#3762]
In the API, there are currently only GET, POST and DEL methods for taxonomies. To update the list of group ids for an otherwise unchanged taxonomy, is there need of a new PATCH method?

**Comment by mcoughlin** [comment]
@bfhealy Yes looks like it. You could just copy over the patch methods with small modifications from the other handlers, they look very very similar generally.

**Comment by bfhealy** [comment]
Addressed by #3764.
