### ISSUE TITLE
docker-compose enhancements requests

### ISSUE THREAD

**Issue by dmitryduev** [skyportal/skyportal#377]
- Can you add
```
version: "3.3"

services:
```
to the top of the `docker-compose.yaml` file? That will ensure the "skyportal_default" network gets created so that other dockerized services running on the same machine may connect to it and talk to skyportal.

- Please also add persistent volumes so that the data do not get wiped out every "docker-compose down".

**Comment by stefanv** [comment]
Certainly! If you have the changes already, feel free to make a PR, otherwise we'll do it soon.

**Comment by stefanv** [comment]
The postgres db is usually stored locally. Did it get changed to storing it inside of the container? If so, we should address that.

**Comment by dmitryduev** [comment]
Created a [PR](https://github.com/skyportal/skyportal/pull/379) for the first point

**Comment by dmitryduev** [comment]
Addressed the second point in #379 as well, so once that is merged, this issue can be closed.
[I am creating a persistent docker volume rather than mounting a local directory -- is that ok with you?]

**Comment by stefanv** [comment]
> Addressed the second point in #379 as well, so once that is merged, this issue can be closed.
> [I am creating a persistent docker volume rather than mounting a local directory -- is that ok with you?]

Sorry, Dima, I didn't see this until I had already made the other PR!
