### ISSUE TITLE
Source filtering delete should remove all filters

### ISSUE THREAD

**Issue by mcoughlin** [skyportal/skyportal#3780]
In SourceTableFilterForm.jsx:

Let's say I pick catalog A and entry A to filter on. Then, on top of the table you see the 2 filters being applied and you can click on them to delete one of them. If I delete the entry, well as discussed earlier the handler sends back an error saying the entry doesn't exist, and the table doesn't show up anymore. What could be much cleaner is that on delete of an element, both filtering are removed.

However, I don't think that catching the deletes of the filters is something we do yet, so we would need to figure it out... It's not critical per say, but it does force you to reload SkyPortal, which can take a while sometimes, or at least change page and come back.

**Comment by Adiman007** [comment]
hi @mcoughlin ,
@kodeurfou and I opened a pull request for this issue here : https://github.com/skyportal/skyportal/pull/3810  .
So far we managed the crash when one filter is removed while its necessary for another by resetting all filters and we managed to remove all the chips

**Comment by mcoughlin** [comment]
Thanks @Adiman007 and @KodeurFou for taking care of this.
