### ISSUE TITLE
Hiding classification vote totals

### ISSUE THREAD

**Issue by bfhealy** [skyportal/skyportal#3816]
To avoid biasing labelers in favor/against a classification, I received a suggestion to hide vote totals. If we do this, we could choose to always hide them or allow their display to be toggled.

<img width="166" alt="Screen Shot 2023-01-05 at 11 25 16 AM" src="https://user-images.githubusercontent.com/42810347/210842629-e82eb4aa-bee4-4d72-9e14-4fc891f1daf4.png">

**Comment by mcoughlin** [comment]
@bfhealy ah that's a cool one. Like a little eye icon to see them?

**Comment by bfhealy** [comment]
@mcoughlin Yes, I think an icon like that would be a good way to control viewing the votes.
