### ISSUE TITLE
Add upvote by default to new posted classifications

### ISSUE THREAD

**Issue by bfhealy** [skyportal/skyportal#3817]
If a user posts a new classification to a source, they are expressing a vote of confidence in that label. It would thus make sense to add an upvote to that classification by default. This would help ensure that new classifications do not become under-weighted in votes compared to existing classifications as labelers review them.

**Comment by mcoughlin** [comment]
@bfhealy i think we do that already. Can you check?

**Comment by bfhealy** [comment]
@mcoughlin Ah yes, we do that already. Closing this issue.
