### ISSUE TITLE
Ingesting stellar variable data from Kowalski

### ISSUE THREAD

**Issue by bfhealy** [skyportal/skyportal#3831]
Posting this issue to discuss development on ingesting stellar variable data from Kowalski. It was mentioned on the call to avoid hitting Kowalski too hard with automatic queries, instead attaching queries to buttons like the ones below in a source's auto-annotations panel. 

<img width="509" alt="Screen Shot 2023-01-10 at 12 18 29 PM" src="https://user-images.githubusercontent.com/42810347/211630956-f996e42f-c58f-432a-9d35-ddda28ed5a20.png">

(Mentioning @mansikasliwal in lieu of assigning - I think if you comment on this issue you can be assigned.)

**Comment by mcoughlin** [comment]
@bfhealy So I guess the question is: how is it best to organize the data to be sure these classifications are easy to post? I guess adding some version of your scope code to https://github.com/mcoughlin/skyportal/blob/main/skyportal/handlers/api/annotation_services.py? And can maybe post those classifications directly. What do you think?

**Comment by bfhealy** [comment]
@mcoughlin I think using a modified version of scope code is a good idea for this issue. Is there a specific available collection on Kowalski that I should look at for examples of the data we'd be posting? If it's some combination of classifications and annotations then scope code definitely has the functionality for that.

**Comment by mcoughlin** [comment]
@bfhealy I am thinking that the button should basically do whatever the calculation is that you do to post sources with classifications. And should take the current catalog as default but make it changable.

**Comment by bfhealy** [comment]
@mcoughlin How do you think we should handle Kowalski token authentication? Perhaps the `query_kowalski` code in the `catalog.py` handler could be adapted? Or we could add a dialog box prompting the user to enter their K token, but this could get tedious if it's required every time the button is clicked.

**Comment by mcoughlin** [comment]
Yeah I think we should adopt that existing code. We have been using allocations to password protect things.

**Comment by Theodlz** [comment]
@bfhealy is this the scope button that is now on Fritz, or something entirely different?

**Comment by bfhealy** [comment]
@Theodlz This is the current scope button on Fritz.

**Comment by Theodlz** [comment]
Great. If everything has been addressed, can I close this issue? @bfhealy
