### ISSUE TITLE
Photometry 'one phase/two phases' radio buttons not working

### ISSUE THREAD

**Issue by bfhealy** [skyportal/skyportal#3937]
Below a source's photometry plot, the radio buttons that indicate whether to display one or two phases of a folded light curve do not change the plotted points.

**Comment by mcoughlin** [comment]
@bfhealy So I think it's missing the correct:

phase_selection.js_on_event( 
        'button_click',

but not obvious what that event is for these!

**Comment by Theodlz** [comment]
The plots have been redesigned with plotly, so this bokeh-related issue isn't relevant anymore
