### ISSUE TITLE
Shifts test is broken

### ISSUE THREAD

**Issue by guynir42** [skyportal/skyportal#3953]
The `test_shifts` test is not working. 
The failure happens when trying to delete a comment from the frontend. 
The delete button only appears when hovering over the comment. 
There's a command to click that comment but that is not the same as hover. 
I don't know how to solve this but I think this is one of the remaining tests that don't work.

**Comment by Theodlz** [comment]
Hi @guynir42. I'm looking at the login failures right now, and I'll have a look at the test very soon.

**Comment by Theodlz** [comment]
It seems that the problem isn't the test but the CommentList component that is broken. I'm opening a PR.

**Comment by guynir42** [comment]
@Theodlz looks like the test is failing? Can I close this?

**Comment by Theodlz** [comment]
Hi Guy. let's leave it open. I closed my PR because @mcoughlin added the bugfix with the comment stuff in his last PR. However, it looks like now the test is failing (or at least is flaky). I will have a look at it.
