### ISSUE TITLE
Upload spectrum test is broken

### ISSUE THREAD

**Issue by guynir42** [skyportal/skyportal#3956]
Locally I am getting an error on the form that says "function nested too deeply". I don't see anything in the logs so I am guessing this is a javascript error. 
I will try to look into it myself but if anyone remembers messing around with this form recently that may be a good time to look back into it.

**Comment by mcoughlin** [comment]
@guynir42 Any obvious point where this occurs? This test passes locally for me..

**Comment by Theodlz** [comment]
Hi Guy, I will try to run it locally to see if I get the error as well.

**Comment by Theodlz** [comment]
I did run into that same problem when running the test more than 10 times. Unfortunately, the console doesn't really specify where the error comes from... I will try to add some logs here and there to figure out where it comes from.

**Comment by mcoughlin** [comment]
@Theodlz validating with v6 rather than v8 passed which indicates the form is somehow invalid based on my reading. I suspect it is the dependency part somehow being problematic. Do you see anything obvious?

**Comment by Theodlz** [comment]
It comes from the browser, putting limits on how deep can function calls be nested (this seems to happen only on firefox)
