### ISSUE TITLE
Photometry versions

### ISSUE THREAD

**Issue by guynir42** [skyportal/skyportal#3960]
The core of the problem we have with photometry has to do with de-duplication. 
Right now the deduplication index includes: `obj_id, instrument_id, origin, mjd, flux, fluxerr`. 
This is useful for preventing the same service from accidentally posting multiple times the same thing. 
But it doesn't prevent posting multiple photometry for one source and the same image, but taken by e.g., different pipelines. 
So for example if I have the alerts photometry taken at some MJD and then the forced photometry will have the same object/instrument/MJD but the flux will be different. 

The way I see it, we should be saving these different versions of the same measurement, but only display the best one. There's some debate over what is best, but hopefully we can figure out a good default so we never need to worry about this stuff. 

This also should include other ideas I've recently run into when talking to people in context of LSST data: about versioning the photometry similarly to how we version the redshift for sources. The idea is that you'd have a reproducible way to say "the photometry on this source when I wrote this paper was attached to this hash, and that is recoverable from skyportal even if we later added more advanced processing of the data like forced photometry. 

I can think of some ways to do all of this, but I'd love to hear your thoughts on this as well.
@mcoughlin @stefanv @profjsb @Theodlz

**Comment by stefanv** [comment]
If you have different sets of columns that matter under various contexts, and you need to control that programmatically outside Postgres, one option could be to store multiple hashes on each row.

You then have some flexibility in what you consider to be "the same". For example, you could use a custom hashing functions that would generate the same hash for coordinates very near one another.

**Comment by guynir42** [comment]
I was thinking more along the lines of "this photometry was made by pipeline X version Y which is the same X/Y combination for all the photometry points uploaded for some time, and then a month later Y+1, and so on. And when you plot/retrieve the photometry you'd get the "most recent" version unless you want to deliberately "check out" an older version.

**Comment by mcoughlin** [comment]
@guynir42 I wonder if to this end, we could use origin to track this (i.e. we do not need another column), but start requiring an origin when posting?

**Comment by guynir42** [comment]
I think the origin has a place in this but I don't know if it can save us adding extra columns. 
There's a real difference between forced / alert photometry. This could be an enum of allowed types, and then you'd be able to flip through them on the front end. 
And the origin could be used to say which pipeline it came from but you'd probably want another column for the version/hash of the specific reduction. 
If you wrap all of this information into a single free-text string you lose a lot of control over it.

**Comment by mcoughlin** [comment]
@guynir42 This is true. I do like the idea of a switch for forced and alert photometry in particular!

**Comment by Theodlz** [comment]
For forced photometry, we set the "origin" of the photometry as "fp" (same for alert-based photometry, we set it to "alert_fp"). On the frontend there's a switch to hide/show forced phot on the candidate scanning page. But we need to add it on the source page too. Closing this one in favor of https://github.com/skyportal/skyportal/issues/4832
