### ISSUE TITLE
Editable OpenAI preferences

### ISSUE THREAD

**Issue by mcoughlin** [skyportal/skyportal#4037]
We should consider allowing the user to change their OpenAI preferences, i.e. those set in the config:

temperature: 0.2
      max_tokens: 350
      top_p: 1.0
      frequency_penalty: 0.0
      model: gpt-3.5-turbo
      presence_penalty: 1.0
      prompt: Using markdown (with appropriate URL links), in one human-readable paragraph please summarize the following comments about this astronomical source. If classification and/or redshift are given, then note those in the summary. This summary will be primarily read by professional astronomers to help them with their work.

**Comment by Theodlz** [comment]
Just to check, what is the behavior that we expect from the openai config in config.yaml, and what a user can set in his own preferences? When (and maybe who) do we use the config.yaml one, is their any limitations and when do we want to use the user defined one instead?

Is it as simple as if nothing in user preferences -> use the config one? Maybe @profjsb can answer this one more accurately.
