### ISSUE TITLE
Replace caching in finder chart routines

### ISSUE THREAD

**Issue by stefanv** [skyportal/skyportal#404]
We should provide a generic mechanism for caching outputs, so that individual routines do not need to manage that complex logic.

**Comment by profjsb** [comment]
Is this something that can be done at the nginx level? The challenge here is that some data products need very rapid refreshing (e.g. a light curve) while others can be lazily refreshed (e.g., finding chart).

**Comment by dannygoldstein** [comment]
I believe this has been addressed by #888
