### ISSUE TITLE
Unable to delete failed SEDM requests

### ISSUE THREAD

**Issue by scizen9** [skyportal/skyportal#4059]
On the source page, when you request SEDM followup, the front end deletes all data in the form, if you make a mistake in one field.  This caused several failed requests that show up with missing fields, which were flagged during submission.  However, when I try to delete them, it refuses to delete them because the very missing fields that caused them to fail.

This is the most recent deploy 20230323.

**Comment by Theodlz** [comment]
@scizen9 closing this after discussing with Don few weeks ago. We agreed that this will anyway disappear with time as all new requests don't have that bug, and we don't really need a bugfix for that.
