### ISSUE TITLE
Allow for FITS thumbnail uploads to allow display of thumbnails with js9

### ISSUE THREAD

**Issue by profjsb** [skyportal/skyportal#410]
It looks like thumbnails from LSST will be in FITS format.  The current Thumbnail handler only allows PNG in the native format and so we lose dynamic range and WCS information if a FITS image is stored as PNGs. I suggest we add FITS as a valid format for thumbnails and store the image as such. This will allow for js9 vizualization as well.

**Comment by dannygoldstein** [comment]
@profjsb Can you update this issue following your investigations to JS9 and the discussion in https://github.com/skyportal/skyportal/issues/157?

**Comment by profjsb** [comment]
Not implemented
