### ISSUE TITLE
simplejson 3.19.1 breaking changes: data-loading methods not compliant with hdf5 files

### ISSUE THREAD

**Issue by Theodlz** [skyportal/skyportal#4104]
A new realease of simplejson causes errors when trying to load galaxy catalogs using make load_demo_data. 

In https://github.com/skyportal/skyportal/pull/4103 we pinned the previous version as the max version so that it can work again. However, it's best if we make changes to be compliant with the new version of the package.

**Comment by mcoughlin** [comment]
We updated this earlier this week.
