### ISSUE TITLE
Photometric series permanent data: permission issue

### ISSUE THREAD

**Issue by Theodlz** [skyportal/skyportal#4198]
It looks like https://github.com/skyportal/skyportal/pull/4025 broke the docker build! I think it just isn't able to create the permanent data folder. Probably something to add in the docker file or docker-compose file?
@guynir42 @mcoughlin 

We need to fix this as it is stopping us from redeploying.

**Comment by guynir42** [comment]
@Theodlz can you link to the error you see in the docker build? Is it just a missing `mkdir` that we need to add?

**Comment by mcoughlin** [comment]
@guynir42 I took care of this one.
