### ISSUE TITLE
gwemopt options displayed on Skyportal

### ISSUE THREAD

**Issue by tahumada** [skyportal/skyportal#4206]
we could use the `--max_nb_tiles` argument to control the time used on each plan while we figure out how to properly set the start and end time

**Comment by tahumada** [comment]
this line produces a schedule lasting ~2 hours 
`python gwemopt_run --telescopes ZTF --doTiles --doPlots --doSchedule --doSkymap --doMovie --timeallocationType powerlaw --scheduleType greedy -o '/Users/tahumada/Data/snipergw/glg_healpix_all_bn230511945.fit/ZTF/gwemopt' --gpstime 1367885310.100023 --skymap /Users/tahumada/Data/snipergw/skymaps/glg_healpix_all_bn230511945.fit --filters g,r,g --exposuretimes 180.0,180.0,180.0 --doSingleExposure --doAlternatingFilters --tilingDir /Users/tahumada/Research/snipergw/snipergw/gwemopt/tiling --doBalanceExposure --configDirectory /Users/tahumada/Research/snipergw/snipergw/gwemopt/config --powerlaw_cl 0.9 --doMovie --airmass 2.5 --mindiff 30 --max_nb_tiles 15,15,15 --doMaxTiles
`

**Comment by Theodlz** [comment]
@tahumada you can already do that. From the form you can set a max nb of tiles (default to 100), plus a checkbox that says if you want to use it or not called "Threshold on number of fields?". Just used it on GRB230511 and it works just fine.
