### ISSUE TITLE
GCN event page - GCN status

### ISSUE THREAD

**Issue by tahumada** [skyportal/skyportal#4211]
1) let every person in the group edit the GCN status, currently it works when I give them admin permits
2) include the ability to add comments to the 'Undefined' GCN status, not just on the rejected/confirmed sources

**Comment by mcoughlin** [comment]
@tahumada for (1), you should just give them the "Manage GCN" privilege, no need to make them admins. Can you check and confirm with someone that works? For (2), we will work on it.

**Comment by Theodlz** [comment]
@mcoughlin I can confirm that 1 works, and 2 has been addressed in one of your PRs recently. Closing.
