### ISSUE TITLE
Forced photometry form has many redundant fields

### ISSUE THREAD

**Issue by robertdstein** [skyportal/skyportal#4222]
Somewhat related to #4221 , the ZTF forced photometry form has a ton of ToO-related fields which have nothing to do with forced photometry, and should be ignored.

Here's an example:

<img width="728" alt="Screenshot 2023-05-16 at 2 03 56 PM" src="https://github.com/skyportal/skyportal/assets/14312838/ca850fb6-1a9f-4acc-a295-72f9c11630be">
<img width="722" alt="Screenshot 2023-05-16 at 2 04 05 PM" src="https://github.com/skyportal/skyportal/assets/14312838/1770c6a8-9a11-4679-839c-ff08ec9be957">

You also have to explicitly choose a "forced photometry" request even if there are no "triggered" credentials provided.

It would be great if requesting ZTF forced photometry worked the same way as ATLAS. When a credential set for forced photometry was selected (can we tag these in the drop down?, right it's it's confusing and I resort to putting FORCED PHOTOMETRY in the PI name), then only had start/end time form should appear, plus perhaps sigma threshold for #4221 .

Also, it would be good if reasonable defaults were used for the times, e.g last 30 days as the window.

**Comment by mcoughlin** [comment]
I got this one.
