### ISSUE TITLE
Reporting a source to TNS does not work

### ISSUE THREAD

**Issue by virajkaram** [skyportal/skyportal#4225]
The form to submit a single source to TNS does not work. Upon submitting the form using the Fritz TNS bot, I sometimes see an error message which just says `reply:`, or sometimes see that it ran successfully (see below).

However, even with the success message, the source does not actually get reported to TNS, which can be verified by going to TNS or by checking on the source page (e.g. https://fritz.science/source/ZTF23aajkmoo)
<img width="1440" alt="Screenshot 2023-05-16 at 2 07 04 PM" src="https://github.com/skyportal/skyportal/assets/20256511/ec91ec36-636e-43e9-b863-585d3a343130">

**Comment by Theodlz** [comment]
@mcoughlin any idea? Looks like posting to TNS works (the API calls gives us a 200) most of the time. Could it be that TNS is then rejecting/cancelling the submission for any reason?

**Comment by mcoughlin** [comment]
Can we print out what the response is and return it?

**Comment by Theodlz** [comment]
Update: We figured out with @virajkaram what is the problem here. Will open a PR soon.

**Comment by virajkaram** [comment]
@Theodlz just confirming that the fix we spoke about has not been implemented yet?

**Comment by Theodlz** [comment]
It was actually. Its hardcoded to use ZTF's id. At least it worked perfectly locally. Does it not work in production still?

**Comment by virajkaram** [comment]
@Theodlz No it does not - here is an example source : https://fritz.science/source/ZTF23aajktxm

**Comment by mcoughlin** [comment]
@virajkaram Can you confirm that it now works?
