### ISSUE TITLE
Automatic reporting to TNS

### ISSUE THREAD

**Issue by virajkaram** [skyportal/skyportal#4227]
It would be nice to have sources automatically reported to TNS once they are saved to the EMGW group.
An alternative could be a button (on the GCN event page) that reports all sources associated with the GCN event to TNS.

**Comment by Theodlz** [comment]
Hi @virajkaram @robertdstein. What do you guys have in mind exactly? Should it report all sources that have been "highlighted/confirmed"? Or all sources in general except the rejected ones?

**Comment by robertdstein** [comment]
I think the vision is that everything saved to the emgw group is a likely transient (AGN/stars/bogus go straight to the reject group), and therefore everything is immediately reported once saved to the group

**Comment by mcoughlin** [comment]
I suggest we start with something where we press a button and a GCN's objects are saved to TNS (once the TNS posting is better understood...)

**Comment by Theodlz** [comment]
@virajkaram to keep you updated: The backend is already implemented by @mcoughlin . I'm working on some frontend for us to activate/deactivate the auto submission and in general add/edit/delete tns robots from the frontend.

**Comment by Theodlz** [comment]
Issue addressed in #4326 and #4279
