### ISSUE TITLE
Rename "confirm" button for GCN events

### ISSUE THREAD

**Issue by robertdstein** [skyportal/skyportal#4228]
Relaying from MMA call:

Right now we have three icons for sources in the GCN event source table: confirm, reject or undefined. The confirm button does not seem super useful (we are unlikely to forget which source is a kilonova), so it would make sense to rename this "highlight" where it highlights promising sources. If those sources are subsequently ruled out, then we can recategorise.

Screenshot example:
<img width="1509" alt="Screenshot 2023-05-16 at 2 32 07 PM" src="https://github.com/skyportal/skyportal/assets/14312838/22bd0ee8-f9a5-414d-aa63-4ca8a7bd7e3a">

**Comment by Theodlz** [comment]
Hi @robertdstein. Agreed! Will take care of that issue. In the backend the table is already called "sourcesconfirmedingcn" so that won't change, but I'll just change what's written on the frontend component then.

**Comment by mcoughlin** [comment]
@Theodlz can we close this?
