### ISSUE TITLE
Sort by GCN Status

### ISSUE THREAD

**Issue by robertdstein** [skyportal/skyportal#4229]
Relaying from MMA call:

Right now it is not possible to sort candidates by GCN status. We can hide rejected sources, but cannot otherwise sort/rank sources by the GCN status tag. It would be good if we could have "confirm/highlight", "undefined", "reject". There are also unlabelled, which should go high up. 

(somewhat related to #4228 )

**Comment by Theodlz** [comment]
> Relaying from MMA call:
> 
> Right now it is not possible to sort candidates by GCN status. We can hide rejected sources, but cannot otherwise sort/rank sources by the GCN status tag. It would be good if we could have "confirm/highlight", "undefined", "reject". There are also unlabelled, which should go high up.
> 
> (somewhat related to #4228 )

Hi Robert. Just to make it clear, there is only "green check", "question mark", and "reject" which correspond to "True", "null", and "False" respectively. There us no unlabelled. That is just a frontend bug introduced by the latest backend change (where if setting to undefined the row in the table is not deleted. 

That aside, I'll take care of that issue.

**Comment by Theodlz** [comment]
@mcoughlin in your last PR I know you changed that behavior. Is that what you had in mind? I'm just trying to understand how in the SourceHandler we want to filter based on that. Given that its not saved on the source object itself it's non trivial to filter on that. We could just fetch the sources, then fetch the sources in GCN Status, filter in python, apply pagination and then return. Not sure what is the norm for this kind of filters that need to query tables where potentially the condition to keep a source is that we don't have an entry.

**Comment by mcoughlin** [comment]
https://github.com/skyportal/skyportal/pull/4233/files

If you want the highlighted ones, can just do this right?

**Comment by Theodlz** [comment]
Sure but I mean I think they want to sort and not filter out.
That means fetching the sources with whatever filter they give except this one.
Then query the sources in gcn table, and then sort by highlight=>undefined(i.e no rows) => rejected, or the opposite.

Well technically this can be achieved easily from the frontend, but only on the current page which is why I am asking myself how to best do it in the backend. I'll open a PR tomorrow and see what I can do.

**Comment by mcoughlin** [comment]
@Theodlz What did you end up deciding here? Need any help?

**Comment by Theodlz** [comment]
Issue addressed in #4339, closing
