### ISSUE TITLE
Default sources on GCN event page should be increased

### ISSUE THREAD

**Issue by robertdstein** [skyportal/skyportal#4230]
Relaying from MMA call:

The default number of sources to display on the GCN event page (10) is too low, and it would make scanning easier if the default was 100.

(related to #4229 and #4228 )

**Comment by Theodlz** [comment]
Sure! Any reason why people don't want to just... change page? I agree that 10 is not enough however, so will increase for sure.

**Comment by robertdstein** [comment]
I am just relaying what was said on the MMA call here, and unfortunately cannot provide you with any more detailed justification on this one
