### ISSUE TITLE
GCN event page - source tab

### ISSUE THREAD

**Issue by tahumada** [skyportal/skyportal#4231]
1. GCN source table does not allow for download, there is a button but doesn't work
2. (minor) when you use the filter and there is no match, you can't go back to the table and have to query again

**Comment by Theodlz** [comment]
Hi @tahumada. Just to be clear, what you mean is that you are applying filters to the sources table displayed on the gcn page, other than just the localization and so on? Like you add constraints on other parameters?

**Comment by mcoughlin** [comment]
@Theodlz can we close this one?

**Comment by Theodlz** [comment]
@mcoughlin I will go over each issue after deploy today and closed if users confirm that this is addressed.
