### ISSUE TITLE
GCN event map

### ISSUE THREAD

**Issue by tahumada** [skyportal/skyportal#4240]
1. the fields shown in the map are listed under 'id' instead of 'field_id'
2. can you plot the primary grid on top of the secondary grid?

**Comment by Theodlz** [comment]
On it

**Comment by tahumada** [comment]
also, could we add a button to gwemopt, so that we use the primary grid only?
the gwemopt arg is `--doUsePrimary`

**Comment by Theodlz** [comment]
> also, could we add a button to gwemopt, so that we use the primary grid only? the gwemopt arg is `--doUsePrimary`

Will do

**Comment by mcoughlin** [comment]
@Theodlz I will do the primary thing
