### ISSUE TITLE
Treasure Map submission from analysis tab on GCN page

### ISSUE THREAD

**Issue by tahumada** [skyportal/skyportal#4258]
The button to submit to treasure map from analysis tab on GCN page does not work, as it performs the observation's query again and times out. @Theodlz knows where the issue is

```
redux-logger.js:1  action skyportal/SUBMIT_OBSERVATIONS_TREASUREMAP @ 15:05:51.078
/api/observation/treasuremap/1:1     Failed to load resource: the server responded with a status of 504 ()
react_devtools_backend_compact.js:2367 JSON decoding error: SyntaxError: Unexpected token '<', "<html>
<h"... is not valid JSON
overrideMethod @ react_devtools_backend_compact.js:2367
showNotification @ Notifications.jsx:89
_callee$ @ API.js:61
tryCatch @ API.js:2
eval @ API.js:2
eval @ API.js:2
asyncGeneratorStep @ API.js:2
_throw @ API.js:2
redux-logger.js:1  action baselayer/SHOW_NOTIFICATION @ 15:06:51.096
redux-logger.js:1  action skyportal/SUBMIT_OBSERVATIONS_TREASUREMAP_FAIL @ 15:06:51.098
```

**Comment by swyatt7** [comment]
Let me know if there is an issue on the Treasure Map side here.

Best,

-SW

**Comment by Theodlz** [comment]
@tahumada to keep you updated: Submission to treasuremap is fixed, meaning that the code works (i could submit both executed and planned observations locally). However it looks like we have performance related issues in production, which prevent the submission (fetching the observations from the database takes too long). I'll try to fix it tomorrow and/or on Friday.

**Comment by Theodlz** [comment]
closing this issue as it has been tested successfully in production.
