### ISSUE TITLE
Add tags to GCN event source tab for easier highligh/rejection 

### ISSUE THREAD

**Issue by tahumada** [skyportal/skyportal#4280]
In the GCN event source tab, we would like to have tag for more consistent  highligh/rejection, also allowing for free format
@Theodlz knows a bit more

SUMMARY of TAGS:

Highlight
LOCAL 
NEW - FP
RED - FP
FAST - FP
RED - ALERT
FAST - ALERT

Reject
FAR
OLD - FP
SLOW 
ROCK
STELLAR
AGN
SpecReject

**Comment by Theodlz** [comment]
@tahumada will take care of it

**Comment by Theodlz** [comment]
Addressed in #4355, closing.
