### ISSUE TITLE
Use of alias/easily searchable GCN events

### ISSUE THREAD

**Issue by robertdstein** [skyportal/skyportal#4300]
We are getting a lot of GCN events, which will quickly become unmanageable. It would be great if we could use aliases to easily go back to an event several months from now, e.g S230527ch. Right now I think we would need to get the event name, look up the event time, then go to Fritz and search by time to identify the event. Having some easy way of retrieving a GCN event using its associated name, e.g by introducing the concept of an alias, would be extremely helpful. 

This is a lower priority issue now that will become more important as O4 goes on.

**Comment by Theodlz** [comment]
Hi @robertdstein , I'll take care of it.

**Comment by Theodlz** [comment]
Issue addressed in #4338, closing
