### ISSUE TITLE
GCN crossmatch in the source page

### ISSUE THREAD

**Issue by tahumada** [skyportal/skyportal#4336]
when crossmatching a source to GCN it shows a long list. Maybe it can be a dropdown menu? 

Example https://fritz.science/source/ZTF23aamzcfe

**Comment by tahumada** [comment]
btw I used the default values and it apparently shows all the GCNs that is spatially consistent, but it doesn't take date into consideration

**Comment by tahumada** [comment]
Maybe we could set the default to first detection to a week after

**Comment by Theodlz** [comment]
Issue has been addressed in #4340 and #4344. Closing
