### ISSUE TITLE
Vanishing sources on GCN event page

### ISSUE THREAD

**Issue by robertdstein** [skyportal/skyportal#4396]
Right now, ZTF sources which are coincident with GCN events will disappear once you run forced photometry on them, if they have a predection in forced photometry. At that point you can never get them back in the GCN source list. It makes sanity checking/bookkeeping a nightmare. We discussed already that we would like the GCN page to only consider alert photometry when deciding if sources are temporally coincident (they are already tagged separately in Skyportal). Since this popped up again tonight, I'm making an issue to track it.

**Comment by mcoughlin** [comment]
@robertdstein This should now be resolved, as any source pinned as ambiguous or confirmed will still appear despite forced photometry being added. Let us know how this goes for the next event and feel free to reopen.
