### ISSUE TITLE
Modifying filter names for photometry passed to analysis service

### ISSUE THREAD

**Issue by bfhealy** [skyportal/skyportal#4481]
During our efforts to add an NMMA analysis service to skyportal/fritz (https://github.com/nuclear-multimessenger-astronomy/nmma/pull/145), we have encountered an inconsistency between expected and supplied filter names. Skyportal provides ZTF filters as `g`, `r` and `i`, but NMMA expects `ztfg`, `ztfr` and `ztfi`.

Posting this issue to discuss the best way forward. We could change the supplied filter names within skyportal and/or fritz, or we could make the change downstream in the NMMA API code itself (e.g. use the `instrument_name` field to identify ZTF photometry, then map the filters following the photometry handoff from skyportal to NMMA).

**Comment by mcoughlin** [comment]
@bfhealy I suggest fixing Skyportal to provide the sncosmo filter names, which are how they are stored in Skyportal.

**Comment by bfhealy** [comment]
@mcoughlin The issue actually turned out to come from the NMMA API itself (see https://github.com/nuclear-multimessenger-astronomy/nmma/pull/200), so I'll close this issue.
