### ISSUE TITLE
Persistent docker volume to store thumbnails etc. in docker-compose.yaml

### ISSUE THREAD

**Issue by dmitryduev** [skyportal/skyportal#450]
While the db data persist, upon `docker-compose down` thumbnails (and I presume some other stuff) disappear. Can you please add a persistent docker volume in `docker-compose.yaml` and a proper path mapping in the corresponding service (not sure what exactly the latter should be, thus filing this issue as opposed to a PR). Thanks!

**Comment by dannygoldstein** [comment]
@dmitryduev @stefanv what's the status of this issue?

**Comment by dmitryduev** [comment]
This particular issue was addressed in #776
