### ISSUE TITLE
Investigate caching strategy

### ISSUE THREAD

**Issue by stefanv** [skyportal/skyportal#452]
When thumbnail-heavy pages are rendered, we want to make sure that those are served directly through nginx.  However, there may be Python-based logic involved to determine when cached thumbnails should be invalidated.  One option would be to have a micro-service that deals with generating expensive products for sources, that can be triggered as necessary.

Related tangentially to #450

**Comment by acrellin** [comment]
We also want to cache photometry plot data.

**Comment by acrellin** [comment]
We closed this on the clubhouse side. Closing here.

**Comment by stefanv** [comment]
I don't think this issue is resolved.  We need to have a general caching mechanism for thumbnails, the star chart PDFs / images, etc.

**Comment by dannygoldstein** [comment]
@stefanv is this addressed by #888?

**Comment by stefanv** [comment]
Implemented caching in finder charts.
