### ISSUE TITLE
Error when vetting candidates

### ISSUE THREAD

**Issue by JannisNe** [skyportal/skyportal#4526]
When trying to vet candidates, i.e. click on the edit button on a source on a GCN event page and try to reject, accept, etc., I get the appended error message.
<img width="1512" alt="Bildschirmfoto 2023-09-12 um 11 38 46" src="https://github.com/skyportal/skyportal/assets/28898481/ae4a5246-7831-4fb8-95fc-43b36d64df6a">

**Comment by Theodlz** [comment]
Thanks for reporting @JannisNe. I'll take a look at it today!

**Comment by Theodlz** [comment]
I failed to reproduce that bug on a local instance. As Michael mentioned, I think we need more info about what happened for you to get there.

**Comment by Theodlz** [comment]
Going to that even page, and querying sources, I've been able to reject successfully. So I guess that just going to the event -> querying sources in emgw group -> reject doesn't get it to miss these fields. Must be something else in between

**Comment by Theodlz** [comment]
Ok I think I got it @JannisNe. Did you go to the source page, and then go back to the gcn event page? What happens there is that the different state variables that contain this kind of info (localization name and cumprob) aren't set anymore. I'll see how that can be fixed. Switching from one page to another makes it tricky. That aside, @mcoughlin we might want to make sure that clicking on a source page opens a new tab. Maybe more reasonable now that the frontend is cached properly.

**Comment by JannisNe** [comment]
Sorry for the late reply. Yes, opening the sources in a different tab solves it!

**Comment by Theodlz** [comment]
@JannisNe just a little update. I'll fix this in 2 PRs:
- first PR, make sure that the default behavior is opening a new tab. Along with that change, trying a new package to give new tabs the previous tabs data, in an effort to reduce how many API calls we send to the backend and speed up the whole thing.
- Keeping in redux (a sort of local tiny db/cache, which is what I'll be passing from one tab to another for example) the parameters used to query sources from the gcnEvent page. That way, even if you leave the event page and come back to it, the reject button won't bug.

I'll let you know when any of these changes are in effect, so you can maybe help us verify how well it works!

**Comment by Theodlz** [comment]
The first PR has been merged. @JannisNe let me know if that already helps.
