### ISSUE TITLE
Legacysurvey skyviewer is not a stable endpoint

### ISSUE THREAD

**Issue by dannygoldstein** [skyportal/skyportal#456]
For making finder charts, http://legacysurvey.org/ is not a stable endpoint - the skyviewer goes down for NERSC maintenance (~1x/month).

This causes `test_finder` to fail if it is run when the site is down

**Comment by acrellin** [comment]
I've seen this locally, as well

**Comment by profjsb** [comment]
I'll fix this by removing the requirement for DESI test to pass. But I'm still ok with using DESI as one of the possible finding chart sources.

**Comment by profjsb** [comment]
Closed by PR #460
