### ISSUE TITLE
Incorporate passbands from SVO

### ISSUE THREAD

**Issue by dannygoldstein** [skyportal/skyportal#459]
simply requires bumping `sncosmo` to version with this issue addressed 

* http://github.com/sncosmo/sncosmo/issues/268

**Comment by dannygoldstein** [comment]
[ch910]

**Comment by dannygoldstein** [comment]
Now that this PR has been merged,

https://github.com/astropy/astroquery/pull/1498

I need to open an sncosmo EP to get the SVO filters sucked in

**Comment by dmitryduev** [comment]
Stalled, closing.
