### ISSUE TITLE
Slight offset between background color and plot color 

### ISSUE THREAD

**Issue by dannygoldstein** [skyportal/skyportal#461]
There is a slight offset in color between the page background and the plot background

<img width="668" alt="Screen Shot 2020-05-21 at 8 30 16 PM" src="https://user-images.githubusercontent.com/2769632/82618817-1d7d9c80-9ba2-11ea-8361-0a1e2baa17b1.png">

Request that we update the CSS to make the plots appear to be the same color as the page

**Comment by dannygoldstein** [comment]
This is on Chrome Version 81.0.4044.138 (Official Build) (64-bit) on OSX 10.14.4 (18E226)

**Comment by acrellin** [comment]
I find it frames the plots nicely, actually. Fine with changing it, though.

**Comment by stefanv** [comment]
Let's change this while updating to Bokeh 2. Working on that gradually.

**Comment by dannygoldstein** [comment]
This has been fixed with the use of `Paper` as the containing component for the source page plots
