### ISSUE TITLE
Fixing the Resizing of the 'Add a Source' Drag Down on the Dashboard

### ISSUE THREAD

**Issue by pronav5000** [skyportal/skyportal#4627]
Name: Bug report
About: Create a report to help us improve
Title: Fixing the Resizing of the 'Add a Source' Drag Down on the Dashboard
Labels: bug
Assignees: 'Pranav Karthik'

**Describe the bug**
On the dashboard of the Skyportal interface, attempting to resize the 'Add a Source' menu does not properly work; no sidebar pops up when it is shrunk and it retains its original size, squeezing out of its box

**To Reproduce**

1. Go to the Skyportal interface using local host.
2. Click on the dashboard
3. Scroll down to the 'Add a Source' box.
4. Clicking on the corner to resize, and shrinking the box does not affect the text, which now squeezes out of the box. Moving it around does work as intended, meaning other boxes can overlap with the text that juts out.

**Expected behavior**
Shrinking the box should cause a sidebar to appear that allows you to scroll up and down within the box.

**Screenshots**
![image](https://github.com/skyportal/skyportal/assets/45305455/7ba520a9-4664-41d0-9797-fc39a27b4aa8)
![image](https://github.com/skyportal/skyportal/assets/45305455/5fbc544c-abf8-4386-afc8-90dbfdf4cfd4)

**Platform information:**

- SkyPortal version: 
- Interface: 
  - [✓] I am using the API

**Comment by Theodlz** [comment]
We removed that widget
