### ISSUE TITLE
Default save behavior

### ISSUE THREAD

**Issue by dannygoldstein** [skyportal/skyportal#466]
@mansikasliwal @acrellin @profjsb 

We are working on the scanning page and want to confirm the default save button behavior. 

What we are currently envisioning is the following:

<img width="468" alt="Screen Shot 2020-05-26 at 7 56 22 PM" src="https://user-images.githubusercontent.com/2769632/82961317-fc92be00-9f8a-11ea-8161-b5dee0b9300d.png">

What do you think?

**Comment by acrellin** [comment]
material-ui doesn't provide split buttons like this, but bootstrap does (https://react-bootstrap.github.io/components/dropdowns/#split-button-dropdowns). @stefanv how opposed to incorporating a bootstrap button are you?

**Comment by acrellin** [comment]
(deleted previous comment - it can indeed be done with material-ui)

**Comment by acrellin** [comment]
Currently, there is a multi-action button (identical in behavior to github's PR merge button) where the default action is to save to the group(s) for which the candidate passed a filter:

![](https://user-images.githubusercontent.com/7230285/83804343-d512b400-a662-11ea-9914-9ec9bdc262c6.png)

Clicking the caret shows another option called "Select groups & save":

![](https://user-images.githubusercontent.com/7230285/83804413-f07dbf00-a662-11ea-9512-2f442b797b0f.png)

When this action is selected & the button is clicked, the user is shown a dialog with a list of checkboxes for all of their groups, with those groups for which the candidate passed a filter checked by default:

![](https://user-images.githubusercontent.com/7230285/83667187-df5d8100-a582-11ea-86ec-243df3643239.png)

**Comment by acrellin** [comment]
Closing per our discussion where it was determined that needing to change the default target groups would be an infrequent occurrence
