### ISSUE TITLE
Generate smaller, simpler photometry plots for scanning page

### ISSUE THREAD

**Issue by acrellin** [skyportal/skyportal#469]
These could potentially be pre-generated upon POSTing of new candidates

**Comment by dannygoldstein** [comment]
Perhaps we could have some keyword args in `photometry_plot` to control figure size, toggle figure features, etc.

**Comment by acrellin** [comment]
I've already implemented the former in
https://github.com/skyportal/skyportal/pull/454/files#diff-55d24d7b7e030bc25d648edaa97eded2R177

**Comment by acrellin** [comment]
This has been addressed by vega plots
