### ISSUE TITLE
Include mag/magerr with frontend photometry downloads

### ISSUE THREAD

**Issue by bfhealy** [skyportal/skyportal#4706]
Frontend photometry downloads currently include `flux` and `fluxerr` values, but not `mag` and `magerr`. If a user is downloading photometry from the frontend for an analysis like NMMA, a conversion to magnitudes using the included zeropoint will be required. We could avoid this conversion if we also downloaded the magnitudes/errors directly.

**Comment by Theodlz** [comment]
Hi @bfhealy, are you talking about the "download lightcurve" button on the photometry plot, or the download button on the top right of the photometry table? The latter includes mag info, and the former flux. Though we should honestly just have both mag and flux and only one format @mcoughlin

**Comment by bfhealy** [comment]
Hi @Theodlz, I'm referring to the "Download Lightcurve" button on the photometry plot. After I posted this issue, I used the top right download button to get the info I needed, but I agree it would be preferable to serve the same format either way.

**Comment by Theodlz** [comment]
I think that we should get rid of one of these two buttons, we definitely don't need both. And at least to me, reusing the existing download button on the mui datatable (like we have on every other page) is what makes the most sense.

**Comment by Theodlz** [comment]
removed the button on the plot, so we only use the button on the table
