### ISSUE TITLE
Implementing New Program Selection on Candidates

### ISSUE THREAD

**Issue by kcasbon** [skyportal/skyportal#4712]
The new Program Selection feature will be a searchable grid of checkboxes, allowing for multi-selection. It should be scrollable as option list may grow quite long.

<img width="630" alt="Screenshot 2024-01-10 at 11 48 28 PM" src="https://github.com/skyportal/skyportal/assets/112792721/26edc047-4edc-40b4-b9ad-f98e8039ba50">

**Comment by Theodlz** [comment]
Added in the candidates page V2 PR
