### ISSUE TITLE
Navbar: never move page content?

### ISSUE THREAD

**Issue by Theodlz** [skyportal/skyportal#4720]
So with my last PR, we have that minimized version of the navbar on the left where we only have icons, but we can open it to see the whole thing with the text.

But the behavior once opened on the desktop is the same, it moves the content of the page and remains open. 

On mobile, it's different. Instead, it opens on top of everything, just like a MUI Dialog would but anchored to the side.

I am wondering if we wouldn't benefit from changing the desktop behavior to match the mobile one. And maybe, show the full menu (with text for each icon) anytime we hover it and not just on click of the menu icon in the top left.

This way, we would never have to move the content of the page because of that menu, which we already know creates a lot of trouble. For instance, even if the plotly plot is fully responsive when I resize the page or close the right panel on the source page, I can notice some slightly weirder behavior when interacting with the menu, where the resizing when closing it doesn't go back to using the full width. It's not too bad, but still something to consider.

A good example is Gmail. You can click the menu icon to force the menu to stay fully open and move the page content to the right, or you can hover icons for a few seconds and it will open it but temporarily and on top of the page content without moving anything.

What do you think @mcoughlin @stefanv? I suggest opening Gmail on your laptop to see the kind of behavior I have in mind.

**Comment by mcoughlin** [comment]
@Theodlz Just tried it on gmail, it is indeed nice. And now I understand some of your inspiration ;)

**Comment by Theodlz** [comment]
> @Theodlz Just tried it on gmail, it is indeed nice. And now I understand some of your inspiration ;)

What do you think would be best on desktop:
- Show full menu on top of content on hover + the menu icon that you can click to have a persistent full menu that does move the content of the page to the right. This is the current gmail behavior.
- Show full menu on top of content on hover, remove the menu icon meaning not persistent fully opened menu. The mnu icon stays for mobile naturally.

**Comment by Theodlz** [comment]
Could also be exactly like on mobile: persisent on click of the icon menu but on top of the content so we never move anything. That's what github does for example

**Comment by mcoughlin** [comment]
I like the idea of not moving stuff, will need to play around a bit more to understand which behavior seems nicest.

**Comment by Theodlz** [comment]
Addressed a while ago, navbar is now always showing but only the icons, and can be extended (but on top of the page, not moving its content).
