### ISSUE TITLE
Galactic latitude/longitude properties

### ISSUE THREAD

**Issue by profjsb** [skyportal/skyportal#473]
Create hybrid properties in both `Photometry` and `Obj` that allow the user to query using `l` and `b` of the data just as easily as `ra` and `dec`. Likely using `@hybrid_property` of SQLAlchemy. One thing that is unclear is how these properties would couple to PostGIS indexing.

**Comment by dannygoldstein** [comment]
Not sure whether standard indexing schemes for equatorial coordinates can also be used for galactic. CC @segasai @lpsinger

**Comment by segasai** [comment]
From q3c point of view it doesn't matter what coordinate system it is. If the coordinates are longitude, latitude in degrees, with latitude going from -90 to 90, it'll work.

**Comment by profjsb** [comment]
Addressed in #716 and #863
