### ISSUE TITLE
`make run_testing` does not remake the database

### ISSUE THREAD

**Issue by dannygoldstein** [skyportal/skyportal#475]
`make run_testing` currently does not remake the testing database if it does not exist, or reinitialize it (with new models) if it already exists. This can sometimes lead to the database structure being out of sync with the app

**Comment by acrellin** [comment]
I don't know that it should, just as make run doesn't.

**Comment by stefanv** [comment]
`make run_testing` should not, but `make test` should.

**Comment by dannygoldstein** [comment]
In that case I agree with @profjsb that it would be quite useful to have a `make db_freshstart` or similar command.

**Comment by acrellin** [comment]
Closing, moving `make db_freshstart` discussion to https://github.com/skyportal/skyportal/issues/476
