### ISSUE TITLE
Missing photometry point owners/streams in downloaded table

### ISSUE THREAD

**Issue by bfhealy** [skyportal/skyportal#4754]
After downloading a photometry table from the frontend, the `owner` and `streams` columns contain `[object Object]` for each entry instead of the username/streams associated with each point.

**Comment by mcoughlin** [comment]
Opened PR here: https://github.com/skyportal/skyportal/pulls

**Comment by Theodlz** [comment]
For this PR let's keep it to one of the two, as adding both requires additional changes like dropping the native MUI method to build headers of the csv to have a custom one.

**Comment by Theodlz** [comment]
Just let me know what is best. I guess that strings is maybe better for your application?

**Comment by bfhealy** [comment]
@Theodlz I think strings would be easiest to work with, but either format is reasonable.

**Comment by Theodlz** [comment]
Got it, merged with the strings 👍
