### ISSUE TITLE
Document `load_seed_data` target

### ISSUE THREAD

**Issue by acrellin** [skyportal/skyportal#476]

**Comment by stefanv** [comment]
Shall we just have `make db_init` also clear the test db if it exists?

**Comment by acrellin** [comment]
Yeah, that sounds reasonable to me.

**Comment by dannygoldstein** [comment]
Would be good if it also works for the test DB

**Comment by acrellin** [comment]
Should this be closed now that we have the `db_seed` target?

**Comment by stefanv** [comment]
I think `make db_init` still needs to be modified to also clear the test database, if it exists.

**Comment by acrellin** [comment]
Is this now satisfied by `db_seed`, etc?

**Comment by profjsb** [comment]
Ping @stefanv

**Comment by stefanv** [comment]
This has been addressed.  db_init also removes the test db, and test_frontend explicitly clears the test db.

I added https://github.com/cesium-ml/baselayer/pull/270 to make it more explicit what is happening in the background.

**Comment by guynir42** [comment]
@stefanv can we close this?
