### ISSUE TITLE
Vega vs AB magnitudes

### ISSUE THREAD

**Issue by santier14** [skyportal/skyportal#4808]
Dear all, 

In the summary table and in the report, if you are uploading photometry in vega, then it is IMPOSSIBLE to visualize your data in vaga system as there have been converted in AB, in this sens, if you have made a typo on the data, it is impossible to double check because it is not anymore accessible. To face on, I would like if possible to have a slide button that you can visualize the photometry either in vega or ab

**Comment by Theodlz** [comment]
Added by @mcoughlin. You now have a toggle on top of the photometry form, and on top of the photometry table
