### ISSUE TITLE
Individual Allocation Page: additional free text field

### ISSUE THREAD

**Issue by Theodlz** [skyportal/skyportal#4829]
The current allocation page shows a list of targets that users have assigned to that allocation to be observed.

It would be good to add another text field there (as an extra column) where users can add free form text, just like the "comments" that people can leave on observing runs.

**Comment by theobonzi** [comment]
@Theodlz

**Comment by antoine-le-calloch** [comment]
In progress. @Theodlz

**Comment by Theodlz** [comment]
@theobonzi @antoine-le-calloch it's good practice to mention the issue on the PR's description, so that the issue and the PR get "linked". There's always ways to do that explicitely from the UI (in the panel on the right I believe).
