### ISSUE TITLE
Import stdpipeweb results into skyportal

### ISSUE THREAD

**Issue by santier14** [skyportal/skyportal#4842]
**Feature Summary**
Establishing the connection between Skyportal and stdpipe web to directly import the results into the database involves creating a button on Skyportal. This button will retrieve the following values based on a stdpipe web task number: magnitude, magnitude error, magnitude system (Vega/AB), number of exposures (if any), exposure time (if any), and filter (based on sncosmo nomenclature), indicated in the format stdpipeweb-task-number.

If we were to create a button in stdpipe for "send to Skyportal," it might be difficult to select groups, telescopes, etc. Therefore, it's simpler to just indicate the stdpipeweb task number in the photometry form. Additionally, if stdpipe web returns "nan," it indicates that the source is not detected, which requires further consideration. At the moment, we are not addressing the detection of new transient sources "after subtraction."

Another possibility, will be to fetch all results in stdweb attached to a "location" of forced photometry and to import every page

**Usage / behavior**
The user should be able to have preformatted results and not to copy paste with error from stdpipe web to skyportal 

**Alternative Solutions**
Either it is a button on stdpipeweb, either a button in skyportal

**Additional context**
Do not know how to make screen shot
http://grandma-stdpipe.ijclab.in2p3.fr/

**Comment by Theodlz** [comment]
@santier14 as discussed with Sergey this will be implemented in stdpipe web itself, not skyportal
