### ISSUE TITLE
WINTER request deletion does not work

### ISSUE THREAD

**Issue by robertdstein** [skyportal/skyportal#4895]
Please fill out relevant sections below; remove those that are unused.

**Describe the bug**
Trying to delete a WINTER request raises an error

**To Reproduce**
Go to any source
Request WINTER data
Try to delete WINTER observations

I confirm this is not just a frontend bug. The request stays in the queue.

**Expected behavior**
It should be deleted.

**Screenshots**
<img width="476" alt="Screenshot 2024-04-25 at 08 58 47" src="https://github.com/skyportal/skyportal/assets/14312838/6de08363-1592-411b-ae9c-779597d2007b">

**Platform information:**

- SkyPortal version: (find this in the [About](https://fritz.science/about) page)
- Interface
  - [ ] I am using the API
  - [x] I am browsing on a desktop
  - [ ] I am browsing on a phone
  - [ ] I am browsing on a tablet

**Additional context**

**Comment by mcoughlin** [comment]
https://github.com/skyportal/skyportal/blob/main/skyportal/facility_apis/winter.py#L177 Can you check that the API is nominally doing the right thing?

**Comment by robertdstein** [comment]
I think that looks fine in principle: http://winter.caltech.edu:82/docs#/default/Delete_a_named_ToO_too_delete_delete
I even vaguely remember successfully testing this out at least once.

AFAICT this is some python/object-oriented problem not related to the API itself.

**Comment by Theodlz** [comment]
Should be fixed it, looks like the `static_method` decorator was missing (or just adding self, same result here anyway).

https://github.com/skyportal/skyportal/pull/4898

**Comment by Theodlz** [comment]
i appreciate the detailed issue, thx Robert!

**Comment by robertdstein** [comment]
Thanks!

**Comment by Theodlz** [comment]
@robertdstein did you have a chance to try that again in production? Just want to make sure that it works now because closing that issue, but I'd rather not try it myself on a random existing follow-up request.

**Comment by robertdstein** [comment]
I just tried this, and it raised an error twice before deleting on the third attempt. There was an error message including the API password, so I'm not going to share the screenshot here. Maybe let's sit together and test this further?

**Comment by robertdstein** [comment]
@Theodlz and I were able to reproduce eventually. I think this happens on the server side if requests are created then deleted in quick succession. Will be fixed on server eventually, but in the interim just waiting 60s and retrying seems to work reliably.
