### ISSUE TITLE
photometry/photometry_id endpoint does not exist

### ISSUE THREAD

**Issue by DanielWarshofsky** [skyportal/skyportal#4896]
Please fill out relevant sections below; remove those that are unused.

**Describe the bug**
The https://fritz.science/api/photometry/photometry_id endpoint does not exist

**To Reproduce**

```
params={'photometry_id':10873392005921,'format':'mag'}
url = urllib.parse.urljoin("https://fritz.science", f'/api/photometry/photometry_id')
headers = {'Authorization': f'token {fritz_token}'}
r = requests.get(url, headers=headers, params=params)
print(r.json()['message'])
```
yields the message `Invalid API endpoint`

**Expected behavior**
Should receive photometry data as detailed in docs here https://docs.fritz.science/api.html#tag/photometry/paths/~1api~1photometry~1photometry_id/get
 

**Platform information:**
Im using the API

**Comment by mcoughlin** [comment]
What about url = urllib.parse.urljoin("https://fritz.science", f'/api/photometry/10873392005921')

?

**Comment by DanielWarshofsky** [comment]
yeilds `PhotometryHandler.get() missing 1 required positional argument: 'photometry_id'`

**Comment by Theodlz** [comment]
Very recent photometry points have ids in the order of:

`https://fritz.science/api/photometry/555529420`

which as you can see, is significantly smaller than this ID you are using here!

**Comment by Theodlz** [comment]
(you should be able to just copy paste this URL and see the datapoints btw)

**Comment by Theodlz** [comment]
@DanielWarshofsky these are lightcurve IDs from the ZTF data releases from Kowalski yes, that's very different (and completely separate) from the photometry endpoint of SkyPortal/Fritz to retrieve the data we have in there.

What are you trying to achieve exactly? Maybe I can make suggestions for the implementation you need.

**Comment by DanielWarshofsky** [comment]
I ended up using the ids to create sources via the archive endpoint and then downloading the photometry from there. There were not many ids so this was not an issue for my implementation

**Comment by Theodlz** [comment]
@DanielWarshofsky as discussed I will still make it possible to search persistent sources by ID to get around that problem in the future. I'll tag you here once that is implemented.

**Comment by Theodlz** [comment]
Done! Closing this issue
