### ISSUE TITLE
All options shifted to the left of the screen when selecting "generic instruments" when adding photometry

### ISSUE THREAD

**Issue by MPillas** [skyportal/skyportal#4929]
All options (e.g. "share with group" or "filters") shifted to the left of the screen when selecting "generic instruments" when adding photometry so I cannot see them anymore. And I need to click on each row blindly and one by one to find the filter I want for instance (screen shot attached).

To reproduce:
- go to a source's page
- click on "add photometry"
- click on "use a form"
- select "generic instrument"
- try to select another option like "share with group"

<img width="1350" alt="Capture d’écran 2024-05-04 à 09 41 37" src="https://github.com/skyportal/skyportal/assets/73175012/7a18d984-c34b-44cc-b45a-5a3042d7f716">

**Comment by mcoughlin** [comment]
@MPillas what browser are you on? Is this in full screen mode? I am struggling to reproduce.

**Comment by Theodlz** [comment]
I can definitely replicate it @MPillas @mcoughlin. I'm on it.

**Comment by mcoughlin** [comment]
@Theodlz did you fix this?

**Comment by Theodlz** [comment]
Nop! Let me give it a go this morning maybe

**Comment by Theodlz** [comment]
Could be as simple as not printing the full list of supported filters right next to the instrument name. Given that it's in the dropdown once selected, it's not that useful. Let's just remove that since it's the problem

**Comment by Theodlz** [comment]
https://github.com/skyportal/skyportal/pull/5149
