### ISSUE TITLE
Investigate best strategy for handling modal dialog boxes

### ISSUE THREAD

**Issue by stefanv** [skyportal/skyportal#496]
See also https://github.com/skyportal/skyportal/pull/493#discussion_r435425934

**Comment by acrellin** [comment]
We only have two or three, and I don't see an easy way to create a generalized component that won't add a lot of complexity. Can we close this, @stefanv ?

**Comment by stefanv** [comment]
You were talking about a general mechanism for handling the opening/closing, but if you don't think that is viable any longer, then sure.
