### ISSUE TITLE
Improve homepage

### ISSUE THREAD

**Issue by bnaul** [skyportal/skyportal#50]
- [x] Search by source id (or other fields? type, etc.?)
- [x] Filter sources by group
- [x] Recent events
- [x] Links to user profile/settings, group management

Original for reference:
<img width="802" alt="screenshot 2017-10-06 13 30 18" src="https://user-images.githubusercontent.com/903655/31297383-a3c3cc34-aa9a-11e7-9510-3c9a1e19e327.png">

**Comment by stefanv** [comment]
- [ ] List of starred favorites
