### ISSUE TITLE
New columns requested in Sources view.

### ISSUE THREAD

**Issue by howardisaacson** [skyportal/skyportal#5141]
I am deploying a version of Skyportal for our Microlensing project at UC Berkeley. Since the project is not transient oriented, we have different variables that we want to search for and prioritize.

**Feature Summary**
It would be valuable for us to have additional columns on the Sources page that would help us to classify microlensing events. We are requesting the following columns be added so they can be used in sorting/filtering sources:

t0        --> Time of Max Brightness    or Time (MB)
t0_err    --> Time of Max Brightness    or Time (MB) Err
tE        --> Time of Einstein Crossing or Time (EC)
tE_err    --> Time of Einstein Crossing or Time (EC) Err
Ibase     --> Baseline Mag (Iband) 
Ibase_err --> Baseline Mag (Iband) Err 
srcfrac   --> Source Flux Frac
srcfrac_err > Source Flux Frac Err
alert_url  -> Alert URL

**Usage / behavior**
These new columns would be used in the same way as RA, DEC, Redshift, and Classification columns are used.

**Alternative Solutions**
If new columns are not possible, is there an alternate way to include this data in a way that we can filter it?

**Comment by mcoughlin** [comment]
@howardisaacson these look very appropriate for annotations to me, for which you can make operator based filtering. There are examples in the tests showing how this works. Let us know if it seems like that would be sufficient for you.

**Comment by howardisaacson** [comment]
This is working for now. Thank you for the suggestion.
