### ISSUE TITLE
Missing database column causing problems.

### ISSUE THREAD

**Issue by howardisaacson** [skyportal/skyportal#5145]
Hello, In developing my own version of skyportal,  I  had everything working until last week. I am now having trouble when I click on a single source, I receive the following error (see screenshot). 

It appears to be looking for galaxys.catalog_id.  When examining the database, I do see galaxys.catalog_id.  Is it possible that when updating my fork of the skyportal repo last week, that something in the database schema changed?  I see that 'database migrations' are part of the documentation, but I am not sure if this is what I need to do.

Any help would be appreciated.

```
skyportal-# \d galaxys
                                          Table "public.galaxys"
     Column     |            Type             | Collation | Nullable |               Default               
----------------+-----------------------------+-----------+----------+-------------------------------------
 catalog_name   | character varying           |           | not null | 
 name           | character varying           |           | not null | 
 alt_name       | character varying           |           |          | 
 distmpc        | double precision            |           |          | 
 distmpc_unc    | double precision            |           |          | 
 healpix        | bigint                      |           |          | 
 redshift       | double precision            |           |          | 
 redshift_error | double precision            |           |          | 
 sfr_fuv        | double precision            |           |          | 
 sfr_w4         | double precision            |           |          | 
 mstar          | double precision            |           |          | 
 magb           | double precision            |           |          | 
 magk           | double precision            |           |          | 
 mag_fuv        | double precision            |           |          | 
 mag_nuv        | double precision            |           |          | 
 mag_w1         | double precision            |           |          | 
 mag_w2         | double precision            |           |          | 
 mag_w3         | double precision            |           |          | 
 mag_w4         | double precision            |           |          | 
 a              | double precision            |           |          | 
 b2a            | double precision            |           |          | 
 pa             | double precision            |           |          | 
 btc            | double precision            |           |          | 
 id             | integer                     |           | not null | nextval('galaxys_id_seq'::regclass)
 created_at     | timestamp without time zone |           | not null | 
 modified       | timestamp without time zone |           | not null | 
 ra             | double precision            |           |          | 
 dec            | double precision            |           |          | 
Indexes:
    "galaxys_pkey" PRIMARY KEY, btree (id)
    "galaxys_name_key" UNIQUE CONSTRAINT, btree (name)
    "ix_galaxys_catalog_name" btree (catalog_name)
    "ix_galaxys_created_at" btree (created_at)
    "ix_galaxys_distmpc" btree (distmpc)
    "ix_galaxys_healpix" btree (healpix)
    "ix_galaxys_magb" btree (magb)
    "ix_galaxys_magk" btree (magk)
    "ix_galaxys_mstar" btree (mstar)
    "ix_galaxys_point" btree ((cosd(ra) * cosd("dec")), (sind(ra) * cosd("dec")), sind("dec"))
    "ix_galaxys_redshift" btree (redshift)
    "ix_galaxys_sfr_fuv" btree (sfr_fuv)
Referenced by:
    TABLE "objs" CONSTRAINT "objs_host_id_fkey" FOREIGN KEY (host_id) REFERENCES galaxys(id) ON DELETE CASCADE

```

**Comment by mcoughlin** [comment]
@howardisaacson I do not see the attached error, feel free to email it to us if it is challenging to upload. @Theodlz may know offhand if something changed recently.

**Comment by howardisaacson** [comment]
Oops. I thought I attached it via screenshot. Here is the text of the error that shows up on the source page when clicking from the source view.

Cannot retrieve source: (psycopg2.errors.UndefinedColumn) column galaxys.catalog_id does not exist LINE 1: SELECT galaxys.catalog_id, galaxys.name, galaxys.alt_name, g... ^ [SQL: SELECT galaxys.catalog_id, galaxys.name, galaxys.alt_name, galaxys.distmpc, galaxys.distmpc_unc, galaxys.healpix, galaxys.redshift, galaxys.redshift_error, galaxys.sfr_fuv, galaxys.sfr_w4, galaxys.mstar, galaxys.magb, galaxys.magk, galaxys.mag_fuv, galaxys.mag_nuv, galaxys.mag_w1, galaxys.mag_w2, galaxys.mag_w3, galaxys.mag_w4, galaxys.a, galaxys.b2a, galaxys.pa, galaxys.btc, galaxys.id, galaxys.created_at, galaxys.modified, galaxys.ra, galaxys.dec FROM galaxys WHERE cosd(galaxys.ra) * cosd(galaxys.dec) BETWEEN cosd(%(cosd_1)s) * cosd(%(cosd_2)s) - %(sind_1)s * sind(%(sind_2)s) AND cosd(%(cosd_1)s) * cosd(%(cosd_2)s) + %(sind_3)s * sind(%(sind_2)s) AND sind(galaxys.ra) * cosd(galaxys.dec) BETWEEN sind(%(sind_4)s) * cosd(%(cosd_3)s) - %(sind_5)s * sind(%(sind_2)s) AND sind(%(sind_4)s) * cosd(%(cosd_3)s) + %(sind_6)s * sind(%(sind_2)s) AND sind(galaxys.dec) BETWEEN sind(%(sind_7)s) - %(sind_8)s * sind(%(sind_2)s) AND sind(%(sind_7)s) + %(sind_9)s * sind(%(sind_2)s) AND %(param_1)s + cosd(galaxys.ra) * cosd(galaxys.dec) * cosd(%(cosd_1)s) * cosd(%(cosd_2)s) + sind(galaxys.ra) * cosd(galaxys.dec) * sind(%(sind_4)s) * cosd(%(cosd_3)s) + sind(galaxys.dec) * sind(%(sind_7)s) >= cosd(%(cosd_4)s)] [parameters: {'cosd_1': 269.8773333333333, 'cosd_2': -28.998061111111113, 'sind_1': 2, 'sind_2': 0.002777777777777778, 'sind_3': 2, 'sind_4': 269.8773333333333, 'cosd_3': -28.998061111111113, 'sind_5': 2, 'sind_6': 2, 'sind_7': -28.998061111111113, 'sind_8': 2, 'sind_9': 2, 'param_1': 0, 'cosd_4': 0.002777777777777778}] (Background on this error at: https://sqlalche.me/e/20/f405)

**Comment by mcoughlin** [comment]
And your fork is current with main, and it says that database migrations are up to date?

Any chance you don't care about the data in there and can start again? Or is this your production server now?

**Comment by Theodlz** [comment]
I answered @howardisaacson by email @howardisaacson. But to me looks like his skyportal has been updated and looks for a column that is indeed in the new schema, but his DB is still running on the old schema. 

His instance is deployed on a K8s cluster though so on start up the migration should be automatic. 

Could be interesting to run `PYTHONPATH=. alembic -x config=config.yaml upgrade head` and see if that does migrate the DB. But first, I would copy paste here the content of `log/migration.log`

**Comment by howardisaacson** [comment]
I think I have this solved. I was able to discard the old database, bring skyportal up to date with main, and re-initialize the database. I did 'stamp' the database, but was unable to do the migration. In any case, it seems to be working now. Thanks for your help!
