### ISSUE TITLE
Last detected

### ISSUE THREAD

**Issue by dannygoldstein** [skyportal/skyportal#516]
The current implementation updates `obj.last_detected` whenever a new photometry point comes in from an image taken at a time greater than the current value of `obj.last_detected`. This is not exactly the right thing to do as photometry can come in corresponding to non-detections.

**Comment by acrellin** [comment]
Let's just add a simple `if flux is not None`, or whatever the relevant
check is, before updating `last_detected`, then.

**Comment by acrellin** [comment]
Fixed in #517
