### ISSUE TITLE
Database performance issue

### ISSUE THREAD

**Issue by howardisaacson** [skyportal/skyportal#5193]
In my deployment of skyportal, called MNTLEAF, I have my local version running well, but the cloud (Rancher platform) version runs incredibly slow. The primary log on Rancher is producing the error: 

"LOG:  unexpected EOF on client connection with an open transaction"

Does anyone have suggestions on what may be cause this error and performance issue?

**Comment by mcoughlin** [comment]
@howardisaacson Maybe you can give us some specs on the deployment? Does Rancher provide any monitoring insights like RAM usage, etc?

**Comment by howardisaacson** [comment]
I have checked with the NERSC/SPIN/Rancher folks, and they claim that resources become available on demand:

"Spin currently does not use CPU affinity or pinning, so workloads have access to all cores on the nodes where they run. Remember, though, nodes are shared, and the expectation is that workloads are not doing computational tasks that would produce continuous, heavy CPU load. "

**Comment by mcoughlin** [comment]
Can you run top or some other processing evaluation to see what if that seems to be true? Also, how much physical memory is on the machine?

**Comment by howardisaacson** [comment]
The Production Cluster has : 8 nodes w/ 64 cores and 4TB of RAM each.  
Here is the top command from the app deployment. Usage appears low, with lots of resources available.

```
top - 23:52:36 up  6:42,  0 users,  load average: 1.20, 1.31, 1.55
Tasks: 169 total,   1 running, 168 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0.0 us,  0.2 sy,  0.0 ni, 99.8 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
MiB Mem : 4124520.+total, 3932770.+free,  55697.6 used, 136052.1 buff/cache
MiB Swap:      0.0 total,      0.0 free,      0.0 used. 4053272.+avail Mem 

    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND  
    104 skyport+  20   0 6232924 540012 184008 S   6.7   0.0   0:32.05 python   
   3821 skyport+  20   0    7880   3640   3064 R   6.7   0.0   0:00.01 top      
```

**Comment by mcoughlin** [comment]
Any idea of good things to check @Theodlz?

**Comment by howardisaacson** [comment]
I am also getting 'websocket authentication failures' on the frontend.

**Comment by mcoughlin** [comment]
How many instances of the app are deployed? You should be able to use more instances given the resources available.

**Comment by howardisaacson** [comment]
Only a single instance. There are currently no users.

**Comment by howardisaacson** [comment]
Follow-up:  I met with the NERSC/SPIN folks. I confirmed that I have the resources that I need to run my version of skyportal. 
I created a new container and permanent storage for the database, and re-initiated it. I see fewer errors on the front end, but performance is the same.
I will next run some tests to see if there are database performance issues.

**Comment by howardisaacson** [comment]
It seems my problems lie in the database. I am continuing to debug. 
I see many ROLLBACK commands that I do not understand the source of.

Here is the latest error that I am encountering, in case anyone has seen this before.
skyportal/skyportal/handlers/api/source.py:288: SAWarning: Class cosd will not make use of SQL compilation caching as it does not set the 'inherit_cache' attribute to ``True``.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this object can make use of the cache key generated by the superclass.  Alternatively, this attribute may be set to False which will disable this warning. (Background on this error at: https://sqlalche.me/e/20/cprf)

**Comment by mcoughlin** [comment]
What version of postgres?

**Comment by howardisaacson** [comment]
postgres 14.4

**Comment by Theodlz** [comment]
Hi @howardisaacson.
- postgres 14.4 should be fine, you can try 15 too, but we used 14.4 for a long time and its solid.
- the performance warning you got, as it mentions, occurs when calling `cosd` (cosine), useful for cone searches. That means that it has nothing to do with anything that is **not** a spatial query (we only need a cosine operator for the cone searches), so it is not related to the the performance issues that you are having.

**Comment by howardisaacson** [comment]
Thanks Theo,  I am going to try to reset the database (yet) again, and test performance with the demo data only.  Maybe something with how I am uploading the data is causing problems.

**Comment by Theodlz** [comment]
Ok! I really don't think the data being there or not is the problem (I mean we want the DB to hold a lot of it anyway).

Let me know next time your app is up, if you are willing to let me access it and make me an admin, I can try to help debug it a bit (with the API I can download the logs).

**Comment by Theodlz** [comment]
But yeah, we have SkyPortal running in kubernetes (both locally and on the google cloud console), on VMs, on mac, on linux, ... and this never happened, so there must be something specific to the deployment on rancher that is causing this, but I wonder what it could be...

**Comment by howardisaacson** [comment]
Thanks Theo. I managed to get it into a non-working state, so I will send you details when it's working again.

**Comment by howardisaacson** [comment]
Thanks for your help @Theodlz !!!  
For the record, it was a cloud resource allocation issue.
