### ISSUE TITLE
password authentication failure connecting to database for `make db_clear`

### ISSUE THREAD

**Issue by rknop** [skyportal/skyportal#5346]
Please fill out relevant sections below; remove those that are unused.

**Describe the bug**
I ran `make db_clear`, and among the outputs was:

```
[✗] Removing database [skyportal]
Could not delete database: 

  psql: error: connection to server at "postgres" (10.42.7.223), port 5432 failed: FATAL:  password authentication failed for user "postgres"
```

These are the relevant sections from my `config.yaml`:

```
database:
  database: skyportal
  host: postgres
  port: 5432
  user: skyportal
  password: <password>
```

If I run psql manually, I can connect:

```
(skyportal_env) skyportal@skyportal-76699d47b7-tpvnj:/skyportal$ psql -h postgres -U skyportal skyportal
Password for user skyportal: 
psql (14.13 (Ubuntu 14.13-0ubuntu0.22.04.1), server 14.4 (Debian 14.4-1.pgdg110+1))
Type "help" for help.

skyportal=# 

```

It looks like baselayer was not picking up my postgres config, as it tried to use user `postgres` rather than `skyportal`.  In fact, given that the container environment had `POSTGRES_USER=skyportal`, then `make db_clear` shoudln't be trying to delete the `skyportal` user.

**To Reproduce**

1. Install containerized skyportal with `POSTGRES_USER` other than `postgres`
2. make db_init
3. make db_clear
4. See `baselayer/tools/db_init.py -f --config=config.yaml` reporting fatal error.

**Expected behavior**
I wouldn't expect a reported fatal error on running `make db_clear`.  (Whether or not this is really fatal is unclear.  If `db_clear` did everything else it was supposed to do other than delete the `skyportal` user, then it functioned as expected, and it was just the error message that was alarming.)

**Screenshots**

**Platform information:**

Kubernetes cluster running running image built from repo's `Dockerfile` with a modified `docker.yaml`

- SkyPortal version: v1.0.0 (github tag)
- Interface
  - [ ] I am using the API
  - [ ] I am browsing on a desktop
  - [ ] I am browsing on a phone
  - [ ] I am browsing on a tablet

**Additional context**

**Comment by Theodlz** [comment]
Hi @rknop, to me here it looks like its trying to delete the `skyportal` database, not the user.

**Comment by Theodlz** [comment]
when running something like make db_clear baselayer will drop the skyportal & skyportal_test databases but it does not delete any user.

**Comment by Theodlz** [comment]
make db_clear is a bit more of a dev thing, to quickly delete a DB. Even if we make it work with another user account here I wouldn't expect that we allow such a dangerous cmd to run in a production env like docker.

**Comment by Theodlz** [comment]
@stefanv any thoughts?

**Comment by stefanv** [comment]
To answer the original question: that access issue has to be addressed in pg_hba.conf

**Comment by rknop** [comment]
Oh, duh, I should have known pg_hba.conf

...but that surprises me.  It means that the Postgres docker image can't be used as is, and yet your docker-compose.yaml file does use it.

**Comment by Theodlz** [comment]
db_clear is more of a dev thing, we don't really expect this to ever run in a production environment.

With the docker image of postgres, you initialize it with a custom user AND database to which it has access to. So in a way to does make sense that you can't delete that database that was initialized along with the container. The permissions postgres sets up are probably so that the custom user can only access the db that's setup with it.

**Comment by Theodlz** [comment]
If you want to clear the db, you might as well just drop the volume and reboot the postgres container to recreate it.

**Comment by rknop** [comment]
Yes, that makes sense.  (Closing the issue since you've convinced me this isn't an issue.)
