### ISSUE TITLE
Field `group_ids` not documented for `/api/telescope`

### ISSUE THREAD

**Issue by stefanv** [skyportal/skyportal#571]
https://skyportal.io/docs/api.html#/paths/~1api~1telescope/post

From `handlers/api/telescope.py`, I see that:

```
group_ids = data.pop('group_ids')
```

1. The field should be documented
2. Can the group now default to system wide?

@acrellin I took the liberty of assigning you, given that you wrote this endpoint, but feel free to refer it to someone else.

**Comment by acrellin** [comment]
Closing as we are removing telescope ACLs
