### ISSUE TITLE
Upload photometry page fails to render if urlFor is clicked before source page finishes rendering

### ISSUE THREAD

**Issue by dannygoldstein** [skyportal/skyportal#593]
If one goes to 

http://localhost:5000/source/16fil

Then clicks the "upload photometry" button before the page finishes loading, then the upload photometry page at

http://localhost:5000/upload_photometry/16fil

fails with 

<img width="1451" alt="Screen Shot 2020-07-22 at 12 39 29 AM" src="https://user-images.githubusercontent.com/2769632/88148687-d2890100-cbb3-11ea-8e37-0a3a7e48e495.png">

**Comment by dannygoldstein** [comment]
It works fine, though, if you refresh the url for the upload_photometry page

**Comment by stefanv** [comment]
Is this before the page has finished loading, or before skyportal his finished starting up? Latter is expected, and gives that error. 

We can probably do a better check in some places, but api calls cannot succeed before the API is served.

**Comment by dannygoldstein** [comment]
The former.

________________________________
