### ISSUE TITLE
Redirect to /groups when deleting group

### ISSUE THREAD

**Issue by dmitryduev** [skyportal/skyportal#595]
![image](https://user-images.githubusercontent.com/7557205/88221701-b61faf80-cc19-11ea-8ba5-d5c4dfcea6a2.png)
![image](https://user-images.githubusercontent.com/7557205/88221726-bf108100-cc19-11ea-8790-8619fbd85c42.png)

**Comment by dannygoldstein** [comment]
This is now fixed
