### ISSUE TITLE
Improve `[websocket] Forwarding message to all users` to be more descriptive

### ISSUE THREAD

**Issue by stefanv** [skyportal/skyportal#623]
This isn't very helpful in the logs, other than to know something has happened.  Perhaps we can print an ACTION_TYPE or similar?

**Comment by acrellin** [comment]
@stefanv Do we even really want to keep these `websocket_server` messages in the logs? Currently we have two messages being logged each time a WS push is initialized; one from `flow`, and one from `websocket_server`. Shall we remove one of these to clean up the logs a bit?

**Comment by acrellin** [comment]
e.g. 
```
[12:18:16 flow] Pushing action skyportal/REFRESH_SOURCE to user * 
[12:18:16 websocket_server] Forwarding message to all users       
```

**Comment by acrellin** [comment]
Also, considering the the log messages are always paired as above, it's pretty obvious what the message was that `websocket_server` is referring to. So is this even still an issue?

**Comment by acrellin** [comment]
@stefanv  -- any thoughts here?

**Comment by acrellin** [comment]
@stefanv any further thoughts here? I'm closing for now, but please feel free to reopen if you still feel more is needed here

**Comment by stefanv** [comment]
Probably fine as is; we can't really assume any specific payload from the baselayer side, making it hard to provide more information without publishing much more verbose logs.
