### ISSUE TITLE
Re-skin baselayer's notifications with MUI?

### ISSUE THREAD

**Issue by dmitryduev** [skyportal/skyportal#634]
Using [this](https://github.com/iamhosseindhv/notistack), for example

**Comment by acrellin** [comment]
@dmitryduev is this still something you'd like to see?

**Comment by dmitryduev** [comment]
Huh, it's been a while :) Don't really care, what we have looks good as is. At the time, I think, I was re-skinning some other component and thought of this from the consistency point of view. Feel free to close if you don't feel like it's a good idea.

**Comment by stefanv** [comment]
The way things are currently wired up, we'd need to make the change in baselayer, or rewrite notifications in SkyPortal.  It would be fairly easy to re-skin the existing notifications, so that's another alternative.

I'll close for now, but feel free to re-open if this becomes a priority.
