### ISSUE TITLE
Get telescopes by name

### ISSUE THREAD

**Issue by dmitryduev** [skyportal/skyportal#639]
Following up on a conversation with @acrellin:
Telescope names should be unique and it should thus be possible to get a telescope by its name with, e.g. ` GET /api/telescopes/name/<telescope_name>`

**Comment by acrellin** [comment]
Also, consider whether to also implement fetching by name for groups, users, and instruments (we'll need to ensure that the `name`/`username` columns are always unique for this)

**Comment by acrellin** [comment]
@profjsb @dannygoldstein any reason we can't make telescope and instrument names unique so that we can add an endpoint to fetch by name?
