### ISSUE TITLE
Map growth marshal colors to vega plot photometry 

### ISSUE THREAD

**Issue by dannygoldstein** [skyportal/skyportal#681]
I'm ok with an opinionated set of color assignments to different filters but shouldn't these all live in one place (e.g. the DB/enum file) and be grabbed dynamically from there? Also, what if the photometry is not from ztf (e.g. it's a Gatinni-only source)?

_Originally posted by @profjsb in https://github.com/skyportal/skyportal/pull/599_

**Comment by stefanv** [comment]
I have an issue open with Vega Lite, because they don't currently support having a set of options for known values, and a fallback for others.

https://github.com/vega/vega-lite/issues/6708

**Comment by guynir42** [comment]
addressed by SP #2734
