### ISSUE TITLE
AssignmentList calls `fetchUser` too many times

### ISSUE THREAD

**Issue by dannygoldstein** [skyportal/skyportal#699]
As `fetchUser` is not currently encapsulated using `useEffect` in AssignmentList, it often issues far too many requests to the backend on loading the source page. 

![image](https://user-images.githubusercontent.com/2769632/89958670-50f32480-dbef-11ea-8a99-b17dbaf47b86.png)

**Comment by acrellin** [comment]
@dannygoldstein this is with the above patch: 
![image](https://user-images.githubusercontent.com/7230285/90698212-0d269d80-e235-11ea-9ffd-d4c2615c5cb6.png)

**Comment by dannygoldstein** [comment]
@acrellin Hmm... I think this may be due to this change:

https://github.com/skyportal/skyportal/pull/700/commits/22c725ec6c1bafcab5ed17e5af2be4cdf20b8e64#diff-e8c57da4867e74381dc2aa305844253dL33

Since `uniqueRequesterIDs` is assigned to a new Array on the heap each time the enclosing function body is executed, it will always render as having "changed" (the memory address will change). But if you spread the contents of the uniquified, sorted array, those element should stay the same from render to render.

**Comment by dannygoldstein** [comment]
@acrellin Here is a SSCCE that illustrates this:

```
> (skyportal2) Dannys-MBP:skyportal danny$ node
> [1, 2, 3] === [1, 2, 3]
false
> [1, 2, 3] == [1, 2, 3]
false
```

**Comment by dannygoldstein** [comment]
versus the previous version (spread syntax)

```
> [1, 2, 3].map((e, i) => e === [1, 2, 3][i]);
[ true, true, true ]
```

**Comment by stefanv** [comment]
You can also use `.every` instead of `.map` to avoid the last reduction.
