### ISSUE TITLE
Make the project name/info configurable

### ISSUE THREAD

**Issue by profjsb** [skyportal/skyportal#718]
Make the project name and information on the landing page configurable (e.g. in `config.yaml`)
![SkyPortal](https://user-images.githubusercontent.com/480799/90341248-d9d4dc00-dfb2-11ea-9362-ec9788871268.jpg)

The top banner and About page should also be configurable:
![SkyPortal](https://user-images.githubusercontent.com/480799/90341297-451eae00-dfb3-11ea-9bbe-039f3bc71d87.jpg)

**Comment by stefanv** [comment]
"About" is already a configurable component that can be exchanged in `config.yaml`.

Modified the login page text in https://github.com/skyportal/skyportal/pull/721

**Comment by acrellin** [comment]
This has been implemented
