### ISSUE TITLE
become_user does not work as expected

### ISSUE THREAD

**Issue by profjsb** [skyportal/skyportal#726]
the front-end endpoint /become_user now shows a JSON response instead of changing to a new user.
![Kapture 2020-08-19 at 13 54 00](https://user-images.githubusercontent.com/480799/90688555-7a313780-e223-11ea-943b-6ca6e285f428.gif)

**Comment by acrellin** [comment]
This is a feature, not a bug. See @stefanv 's recent PR - https://github.com/skyportal/skyportal/pull/696
