### ISSUE TITLE
Shane offsets trigger warning

### ISSUE THREAD

**Issue by dannygoldstein** [skyportal/skyportal#743]
If I hit,

`http://localhost:5000/api/sources/14gqr/offsets?facility=Shane`

the backend raises

`Warning: Do not recognize this starlist format. Using Keck.`

**Comment by profjsb** [comment]
the `facility` key only implements the two starlist formats that I could find on the web. You could make a lookup table to decide which to use for the observing run if need be.

**Comment by profjsb** [comment]
So each instrument could have a `starlist_type` in the DB, defaulting to Keck (e.g.).

**Comment by dannygoldstein** [comment]
Fixed by https://github.com/skyportal/skyportal/pull/1084
