### ISSUE TITLE
how do we implement follow up request infrastructure?

### ISSUE THREAD

**Issue by dannygoldstein** [skyportal/skyportal#745]
This is a quick write up of a discussion we had today at the iteration meeting, on the implementation of infrastructure for follow-up requests. 

The question is whether to have the follow-up requests and associated instrument APIs live within SkyPortal, or to have their definitions be deferred to extension modules (like Fritz).

At the end of our call, seems like we were leaning toward:

   * Keep the base follow-up requests stuff in Skyportal
   * Provide a contract within skyportal for defining additional APIs

Here is my straw man implementation:

1. in `skyportal/skyportal` , have a directory, `facility_apis/` , which contains `__init__.py`.
2. in `facility_apis/`  there would be a file, `base.py`, which defines the contract developers need to implement to add in their own APIs. the contract/interface would look something like

```python
class FollowUpAPI(object):
    @staticmethod
    def submit(request):
        return NotImplemented
    @staticmethod
    def update(request_id, updated_fields):
        return NotImplemented
    @staticmethod
    def get(request_id):
        return NotImplemented
    @staticmethod
    def delete(request_id):
        return NotImplemented
```

3. Implementations of this interface would have to subclass FollowUpAPI
4. then, in the database, for instruments that have an API, there would be an api_id column, an api relationship, and a FollowUpAPI table. the FollowUpAPI table would pass information to the frontend, specifically about the properties needed to render the follow-up request form for requests under a particular API. this would just be JSON. The follow-up API table would also maintain a column called `api_class`, which would be a string. the string would be used to access the corresponding API in `facility_apis` as follows:

```python
from skyportal import facility_apis
api = getattr(facility_apis, mapped_api_instance.api_class)
```

where `mapped_api_instance` is an instance of a `FollowUpAPI` database record. then you have `api` as the class that is an implementaiton of `FollowUpAPI`, and you can call static methods like

```python
api.submit(followup_request)
```

**Comment by stefanv** [comment]
My comment from Slack:

My concerns are not so much around how we build the hooks in Python; I think what you proposed is viable.  I'd worry about: what mechanism does a facility use to report back status (e.g., what if they need to hit an endpoint to report back?).  Some facilities may immediately return the status, others may return a URL that you need to visit in the future to check on the status.

A JSONB field in the database would be able to store any metadata related to the request, no problem.
But to act on what is in there may not always be so easy since, as I mentioned during our last discussion, SkyPortal has no way of running events at arbitrary times.  You could install a cron-job, but that may not be ideal.

*Edit:* One idea for follow-up: render the response so that there is a button the user can click to get a status update.  Not ideal, but may work if we don't want to build this out as a job-queue micro-service.

**Comment by guynir42** [comment]
I agree with @dannygoldstein, and I think it is good to make this as easy as possible to add new APIs, without committing to any specific interface ourselves. 

I also think that @stefanv's suggestion to put a button for later checking in on the requests is good enough.

**Comment by dannygoldstein** [comment]
[ch544]

**Comment by stefanv** [comment]
@dannygoldstein How different are these telescopes?  We may need an extra method called `schema` or similar to first query the structure that the data is supposed to be in.

We would then have to render that JSON dynamically as a form on the frontend.

E.g., one telescope may have an extra field "priority", another "description", and yet another "telephone_number_to_text".

**Comment by dannygoldstein** [comment]
> @dannygoldstein How different are these telescopes? We may need an extra method called `schema` or similar to first query the structure that the data is supposed to be in.

> We would then have to render that JSON dynamically as a form on the frontend.

Each API database record will contain a `form` attribute, which will contain all `JSON` needed by `react-hook-form` to render the followup request form on the frontend. My intention is that this field will be sufficient for describing the data structure for followup requests. 

> E.g., one telescope may have an extra field "priority", another "description", and yet another "telephone_number_to_text".

The telescopes are all very different and will each support different API methods. The `form` or `schema` attribute (maybe we could have both?) should take care of all of this...

**Comment by dannygoldstein** [comment]
> My comment from Slack:
> 
> > My concerns are not so much around how we build the hooks in Python; I think what you proposed is viable.  I'd worry about: what mechanism does a facility use to report back status (e.g., what if they need to hit an endpoint to report back?).  Some facilities may immediately return the status, others may return a URL that you need to visit in the future to check on the status.
> 
> > A JSONB field in the database would be able to store any metadata related to the request, no problem.
> > But to act on what is in there may not always be so easy since, as I mentioned during our last discussion, SkyPortal has no way of running events at arbitrary times.  You could install a cron-job, but that may not be ideal.
> 
> One idea for follow-up: render the response so that there is a button the user can click to get a status update. Not ideal, but may work if we don't want to build this out as a job-queue micro-service.

My idea is as follows: 

Each active API will define a `FollowupApiMessageHandler` that will be defined within the corresponding user-defined `FollowUpAPI` class and installed as a skyportal endpoint serving at a specific address on startup via a hook. These handlers will listen for POSTs from the observing facilities and handle them as needed. They will also log them to a `FollowUpRequestRespones` table that can be queried for the latest request status from the observatory, etc. 

There shouldn't be any need for maintaining a queue within skyportal, for any robotic facility. All of that is managed by the observatories themselves. 

Some facilities implement endpoints you can use for status-checking, but not all of them. SEDM does this, but LT does not.

**Comment by stefanv** [comment]
> Each API database record will contain a `form` attribute, which will contain all `JSON` needed by `react-hook-form` to render the followup request form on the frontend. My intention is that this field will be sufficient for describing the data structure for followup requests.

Question then is how do you get plugin authors to specify this; ideally, it would be via their plugin (so a method in the Python, or a stand-alone file that ships next to the Python).

**Comment by dannygoldstein** [comment]
> > Each API database record will contain a `form` attribute, which will contain all `JSON` needed by `react-hook-form` to render the followup request form on the frontend. My intention is that this field will be sufficient for describing the data structure for followup requests.
> 
> Question then is how do you get plugin authors to specify this; ideally, it would be via their plugin (so a method in the Python, or a stand-alone file that ships next to the Python).

Was just about to write this. I think you are right. Should live in the Python class. I think we can safely dispatch the `FollowUpAPI` database table and track everything from the plugins.

**Comment by stefanv** [comment]
To be clear, I was just talking about how to specify what the frontend-rendered entry form should look like.
