### ISSUE TITLE
top sources and news feed leak information

### ISSUE THREAD

**Issue by dannygoldstein** [skyportal/skyportal#746]
On master, I see information about sources in the news feed and top sources windows that I do not have access to in the SourceList.

<img width="1072" alt="Screen Shot 2020-08-25 at 11 46 22 PM" src="https://user-images.githubusercontent.com/2769632/91270447-7d4d8b80-e72d-11ea-99d8-f2148f6f717a.png">

**Comment by acrellin** [comment]
It looks like the news feed and top sources use user.acessible_groups,
while the source handler uses user.groups. There is no leak, just
inconsistency.

**Comment by acrellin** [comment]
Should the sources handler be updated to filter on user.acessible_groups?
