### ISSUE TITLE
user profile / avatar overlaps skyportal logo on top bar on mobile

### ISSUE THREAD

**Issue by dannygoldstein** [skyportal/skyportal#761]
<img width="341" alt="Screen Shot 2020-08-29 at 1 13 53 PM" src="https://user-images.githubusercontent.com/2769632/91645390-94280280-e9f9-11ea-893f-5a8c77b53575.png">

**Comment by stefanv** [comment]
Side bar should fold by default too?

**Comment by profjsb** [comment]
I think the Logo/Project Name should disappear as well, and perhaps the username should also go (leaving the avatar and the dropdown icon).

**Comment by kmshin1397** [comment]
#778
