### ISSUE TITLE
dark background is used even when dark mode is not enabled

### ISSUE THREAD

**Issue by dannygoldstein** [skyportal/skyportal#765]
Looks like a dark background is used even when dark mode is not enabled? This makes  text difficult to read:
<img width="1909" alt="Screen Shot 2020-08-30 at 4 14 29 PM" src="https://user-images.githubusercontent.com/2769632/91671502-1db00100-eadc-11ea-8f48-ebea3409a888.png">

_Originally posted by @dannygoldstein in https://github.com/skyportal/skyportal/pull/724#issuecomment-683483487_

**Comment by kmshin1397** [comment]
Do you see it dark even after refreshing? It shouldn't be like that in light mode...

**Comment by acrellin** [comment]
@kmshin1397 yes, I see this after refreshing, but changing dark mode to on and then back off again seems to fix it (light background throughout)
