### ISSUE TITLE
When logged in as `provisioned_admin`, scanning page shows no results upon clicking "Search"

### ISSUE THREAD

**Issue by acrellin** [skyportal/skyportal#793]
![vega_candidate_error](https://user-images.githubusercontent.com/7230285/91920045-b7aeaf80-ec7c-11ea-84f2-5e555baa78fc.gif)

**Comment by dannygoldstein** [comment]
does this not also happen for other admin users, e.g., group admin? wondering if this may be related to users that have many more `accessible groups`  than membership groups?

**Comment by acrellin** [comment]
@dannygoldstein when I switched to testadmin (user ID 2 after running make load_demo_data w/ clean DB), the error does not occur.

**Comment by acrellin** [comment]
@dannygoldstein I can't figure out why that would affect the vega plots
