### ISSUE TITLE
Finding chart generator

### ISSUE THREAD

**Issue by profjsb** [skyportal/skyportal#80]
Add a button to generate (and cache) a finding chart for a given source.

The finder should show (by default):
  - an optical image of the field (5 arcmin on a side, PS1 or SDSS or DSS)
  - the location of three-five stars near the position
  - a calculation of the angular offsets from those stars to the source position

Should be viewable on the page and downloadable as a PDF.

A second version should allow the user to configure field size, orientation, number of stars, etc.

**Comment by stefanv** [comment]
@profjsb I searched for Python packages that would generate these and found (ordered from what I consider to be most to least usable for our purpose):

- https://fpavogt.github.io/fcmaker/
- https://astroplan.readthedocs.io/en/latest/tutorials/plots.html#finder-image
- https://github.com/Fingel/fchart
- https://github.com/zkbt/the-friendly-stars

Would the output of any of these suffice?

**Comment by stefanv** [comment]
Closed by #398.
