### ISSUE TITLE
Track multiple source positions

### ISSUE THREAD

**Issue by profjsb** [skyportal/skyportal#81]
At the DB level, we should keep track of a few positions (and their uncertainties) of the source:

1) The source position at the time of discovery 
   - if this isn't in the initial packet as a separate field, then use the first detection value

2) A user updated position
   - default is to the use the initial source
   - a user may choose to update this over time (not allowed to move it from the original position by XX arcsec or more)

3) A *calculated* position
  - a weighted average position derived from the detections table -- this position will change as more candidates are added to the source.

**Comment by dannygoldstein** [comment]
I believe this is more or less done - we track ra, dec, ra_dis, dec_dis, and the calculated positions are used in the finder chart generation
