### ISSUE TITLE
Update user icon and name in the top right corner upon Profile update

### ISSUE THREAD

**Issue by dmitryduev** [skyportal/skyportal#830]
![image](https://user-images.githubusercontent.com/7557205/92177215-eb144a00-edf4-11ea-9038-05d3856cfd42.png)

**Comment by acrellin** [comment]
What's the issue here?

**Comment by acrellin** [comment]
For some reason the WS message handler in profile.js is not being registered with the main messageHandler instance -- it never gets run when incoming messages are received. Will dig a bit deeper into this soon.

**Comment by stefanv** [comment]
Yeah... when the username changes, the websocket is no longer authenticated :D
