### ISSUE TITLE
TNS

### ISSUE THREAD

**Issue by profjsb** [skyportal/skyportal#848]
## Minimal

- Either query kowalski (for Fritz) or TNS and map the taxonomy of classifications to local taxonomy in SP.
- add a Button on Source page to re-check TNS (and perhaps other web resources), so that is can be done manually

## Nice to Have

- Do this asynchronously so as not to slow the experience.
- Grab and upload any spectra from TNS to this Source

**Comment by dmitryduev** [comment]
Stalled, closing for now.
