### ISSUE TITLE
Docker Compose Version to Demo SkyPortal

### ISSUE THREAD

**Issue by profjsb** [skyportal/skyportal#85]
Similar to Cesium Web, make a docker compose file that can be run to get a full version of SkyPortal up and running locally.

**Comment by stefanv** [comment]
This is already in place, and is the mechanism used to launch skyportal.io.

See https://github.com/skyportal/skyportal/blob/master/docker-compose.yaml and https://github.com/skyportal/skyportal/blob/master/Dockerfile

**Comment by profjsb** [comment]
Will someone confirm that the compose/Dockerfile still work?

**Comment by profjsb** [comment]
This is related to [PR #86](https://github.com/skyportal/skyportal/pull/86)

**Comment by profjsb** [comment]
completed in PR #86
