### ISSUE TITLE
Permissions clash when an alert passes multiple filters

### ISSUE THREAD

**Issue by dmitryduev** [skyportal/skyportal#860]
- Happens when a candidate passes multiple filters and the user does not have access to one of the corresponding groups
- This is why it works with the super user, or when the candidate data only belong to a single group that the user is part of
- Some join query to grab the comments partially returns stuff such as the comment id and such (which it shouldn't), but not the obj_id (as it should)

Example error:
```
(raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely) (psycopg2.errors.NotNullViolation) null value in column "obj_id" violates not-null constraint DETAIL: Failing row contains (226, 2020-09-05 07:17:45.831564, 2020-09-05 07:21:36.055237, FWHM: 1.1773988008499146, null, null, null, null, null, 1, null). [SQL: UPDATE comments SET modified=timezone(%(timezone_1)s, CURRENT_TIMESTAMP), obj_id=%(obj_id)s WHERE comments.id = %(comments_id)s] [parameters: ({'timezone_1': 'UTC', 'obj_id': None, 'comments_id': 226}, {'timezone_1': 'UTC', 'obj_id': None, 'comments_id': 227}, {'timezone_1': 'UTC', 'obj_id': None, 'comments_id': 228}, {'timezone_1': 'UTC', 'obj_id': None, 'comments_id': 229}, {'timezone_1': 'UTC', 'obj_id': None, 'comments_id': 230}, {'timezone_1': 'UTC', 'obj_id': None, 'comments_id': 231}, {'timezone_1': 'UTC', 'obj_id': None, 'comments_id': 232}, {'timezone_1': 'UTC', 'obj_id': None, 'comments_id': 233} ... displaying 10 of 25 total bound parameter sets ... {'timezone_1': 'UTC', 'obj_id': None, 'comments_id': 249}, {'timezone_1': 'UTC', 'obj_id': None, 'comments_id': 250})] (Background on this error at: http://sqlalche.me/e/gkpj)
```

**Comment by acrellin** [comment]
Looks like obj_id isn't being loaded somewhere, but I don't see where the
permissions clash is. Would love more details from you if possible.

**Comment by dmitryduev** [comment]
@acrellin: here's how to reproduce this locally:

```bash
$ make db_clear; make db_init; make_run
```

```bash
$ make load_demo_data
```

Then using the provisioned_admin's token from `.tokens.yaml`, POST a comment:

```json
{
    "obj_id": "14gqr_unsaved_copy",
    "text": "lol",
    "group_ids": [7]
}
```

Then in the browser `/become_user/4` (`fulluser`) and navigate to `candidates` -- you will see the error.
7 is the gourp_id of Program_B, and `fulluser` is not a member of it, but `14gqr_unsaved_copy` was posted to Program_A, which that user _can_ see.

**Comment by acrellin** [comment]
Great, thanks Dima! Will fix.
