### ISSUE TITLE
Add overflow-y to My groups widget

### ISSUE THREAD

**Issue by dmitryduev** [skyportal/skyportal#896]
![image](https://user-images.githubusercontent.com/7557205/92993578-879ab400-f4a7-11ea-8325-90ebc75b2977.png)

**Comment by profjsb** [comment]
To keep this widget the same size, should probably just add a scrollbar.

**Comment by kmshin1397** [comment]
@profjsb What do you think about just adding a scrollbar and turning off the resizable handle for this widget then? It is currently the only widget set to be resizable, and I think I put it that way because you set it that way in one of the earlier layouts at some point.

**Comment by dmitryduev** [comment]
@kmshin1397 please just add a scrollbar and turn off the resize handle.
