### ISSUE TITLE
Fix group ownership

### ISSUE THREAD

**Issue by profjsb** [skyportal/skyportal#90]
When a super admin creates a group and then leaves the group, that group is removed even if there is another admin of that group.

Each group should have an owner and an owner cannot leave (and delete) a group until they assign ownership to another group admin.

**Comment by acrellin** [comment]
I can't reproduce this.  When I create a group as admin, then remove myself from the group, I still see the group listed under All Groups, and can still view it (showing no members).  Please describe how to reproduce this.
