### ISSUE TITLE
postgres authentication error

### ISSUE THREAD

**Issue by AlexGKim** [skyportal/skyportal#907]
I am installing a dockerized SkyPortal on NERSC.

I get the following errors from the database container.

```
2020-09-15 00:39:34.596 UTC [113] FATAL:  password authentication failed for user "skyportal"
2020-09-15 00:39:34.596 UTC [113] DETAIL:  Password does not match for user "skyportal".
	Connection matched pg_hba.conf line 98: "host all all all md5"
```

Before line 98 of pg_hba.conf I have added

```
host skyportal skyportal 127.0.0.1/32 trust
host skyportal_test skyportal 127.0.0.1/32 trust
```

I have checked that the environmental variables, particularly the password which is obtained as a secret, are correct.

```
root@db-6489bc7848-n5tlg:/var/lib/postgresql/data/pgdata# printenv POSTGRES_USER
skyportal
root@db-6489bc7848-n5tlg:/var/lib/postgresql/data/pgdata# printenv POSTGRES_PASSWORD_FILE
/secrets/password
```

**Comment by dannygoldstein** [comment]
Hi @AlexGKim, good to see you here !

Are you connecting to postgres from within the postgres docker container or from outside the postgres docker container?

**Comment by AlexGKim** [comment]
Thanks Danny for the response.

The errors I get are from within the postgres docker container, which at the moment is not connected to the SkyPortal app.  The container is connected to an external volume.

root@db-6489bc7848-n5tlg:/# ls -l /var/lib/postgresql/data/
total 8
drwx------ 19 postgres root 8192 Sep 15 00:51 pgdata

Alex

**Comment by dannygoldstein** [comment]
Can you try replacing `127.0.0.1/32` with `localhost`?

**Comment by AlexGKim** [comment]
That seems to have worked!  Thanks!

Is this error something I should worry about?

2020-09-15 04:44:01.039 UTC [1] LOG:  starting PostgreSQL 12.2 (Debian 12.2-2.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
9/14/2020 9:44:01 PM 2020-09-15 04:44:01.041 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
9/14/2020 9:44:01 PM 2020-09-15 04:44:01.042 UTC [1] LOG:  could not create IPv6 socket for address "::": Address family not supported by protocol
9/14/2020 9:44:01 PM

**Comment by dannygoldstein** [comment]
@AlexGKim  Great glad to hear it.  Nope, if the log level is `LOG` (as opposed to e.g., WARNING or FATAL), it's just info, not an error.

**Comment by AlexGKim** [comment]
Rescind that.  The password error has reappeared.  Took a moment for them to start up.

Alex

**Comment by dannygoldstein** [comment]
But are you able to connect from within the container?

**Comment by AlexGKim** [comment]
Indeed I can connect from within the container.  I am doing so as root, so I am not sure whether postgres bothers checking even though I am signing is as skyportal.

Alex

**Comment by dannygoldstein** [comment]
OK that's good. The authentication errors in the log may be from another client (not the one you are running in the container) trying to establish a connection to postgres with outdated credentials. Could there be a postgres client or python process somewhere that has been left attempting to connect to Spin?

**Comment by AlexGKim** [comment]
This has been solved.  As I learned from Danny, postgres credentials are not passed by system variables but by the docker.yaml file.
