### ISSUE TITLE
PhoneNumber is not JSON serializable

### ISSUE THREAD

**Issue by AlexGKim** [skyportal/skyportal#935]
I get the following error when connecting to http://sp.skyportal.development.svc.spin.nersc.org/

> ERROR:tornado.application:Uncaught exception GET /api/internal/instrument_forms (127.0.0.1)
> HTTPServerRequest(protocol='http', host='sp.skyportal.development.svc.spin.nersc.org', method='GET', uri='/api/internal/instrument_forms', version='HTTP/1.0', r
> emote_ip='127.0.0.1')
> Traceback (most recent call last):
>   File "/skyportal_env/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1243, in _execute_context
>     self.dialect.do_execute(
>   File "/skyportal_env/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
> I have no name!@app-bcbd5b8d4-rsnz4:/skyportal/log$ tail app.log 
>     for chunk in chunks:
>   File "/skyportal_env/lib/python3.8/site-packages/simplejson/encoder.py", line 716, in _iterencode
>     o = _default(o)
>   File "/skyportal/baselayer/app/json_util.py", line 48, in default
>     return json.JSONEncoder.default(self, o)
>   File "/skyportal_env/lib/python3.8/site-packages/simplejson/encoder.py", line 272, in default
>     raise TypeError('Object of type %s is not JSON serializable' %
> TypeError: Object of type PhoneNumber is not JSON serializable
> [!] Error in `/api/internal/profile`: Object of type PhoneNumber is not JSON serializable
> WARNING:tornado.access:400 GET /api/internal/profile (127.0.0.1) 8.17ms

**Comment by dannygoldstein** [comment]
@AlexGKim This is fixed on master in #927 based on cesium-ml/baselayer#147
