### ISSUE TITLE
Adding a classification is broken for provisioned_admin user

### ISSUE THREAD

**Issue by kmshin1397** [skyportal/skyportal#938]
![Screenshot 2020-09-17 135637](https://user-images.githubusercontent.com/17696889/93527396-a953cb00-f8ed-11ea-8729-a55b8de6bd64.png)

**Comment by kmshin1397** [comment]
Think it's just the provisioned_admin - perhaps just my local database

**Comment by kmshin1397** [comment]
Issue persists after db clear.

**Comment by kmshin1397** [comment]
Ah nvm provisioned_admin just isn't a part of either of the demo groups.

**Comment by profjsb** [comment]
We should still be catching this on the backend and issuing an alert.
