### ISSUE TITLE
Error running make load_demo_data

### ISSUE THREAD

**Issue by AlexGKim** [skyportal/skyportal#944]
I am getting the following error when running make load_demo_data in a docker container.

> [06:32:54 flow] Pushing action skyportal/REFRESH_SOURCE to user *
> [06:32:54 flow] Pushing action skyportal/REFRESH_SOURCE to user *
> [06:32:54 flow] Pushing action skyportal/REFRESH_SOURCE to user *
> [06:32:54 flow] Pushing action skyportal/REFRESH_SOURCE to user *
> [06:32:54 flow] Pushing action skyportal/REFRESH_SOURCE to user *
> [06:32:54 flow] Pushing action skyportal/REFRESH_SOURCE to user *
> [06:32:54 flow] Pushing action skyportal/REFRESH_SOURCE to user *
> [06:32:54 flow] Pushing action skyportal/REFRESH_SOURCE to user *
> [!] Error in `/api/thumbnail`: Insufficient permissions.
> WARNING:tornado.access:400 POST /api/thumbnail (127.0.0.1) 14.60ms
> [!] Error in `/api/thumbnail`: Insufficient permissions.
> WARNING:tornado.access:400 POST /api/thumbnail (127.0.0.1) 12.57ms
> [!] Error in `/api/thumbnail`: Insufficient permissions.
> WARNING:tornado.access:400 POST /api/thumbnail (127.0.0.1) 9.17ms
> [!] Error in `/api/thumbnail`: Specified source does not yet have any photometry data.
> WARNING:tornado.access:400 POST /api/thumbnail (127.0.0.1) 10.87ms
> [!] Error in `/api/thumbnail`: Specified source does not yet have any photometry data.
> WARNING:tornado.access:400 POST /api/thumbnail (127.0.0.1) 9.52ms
> [!] Error in `/api/thumbnail`: Specified source does not yet have any photometry data.
> WARNING:tornado.access:400 POST /api/thumbnail (127.0.0.1) 9.45ms
> [!] Error in `/api/thumbnail`: Insufficient permissions.
> WARNING:tornado.access:400 POST /api/thumbnail (127.0.0.1) 8.32ms
> [!] Error in `/api/thumbnail`: Insufficient permissions.
> WARNING:tornado.access:400 POST /api/thumbnail (127.0.0.1) 8.60ms
> [!] Error in `/api/thumbnail`: Insufficient permissions.
> WARNING:tornado.access:400 POST /api/thumbnail (127.0.0.1) 9.04ms
> [!] Error in `/api/thumbnail`: Specified source does not yet have any photometry data.
> WARNING:tornado.access:400 POST /api/thumbnail (127.0.0.1) 9.74ms
> [!] Error in `/api/thumbnail`: Specified source does not yet have any photometry data.
> WARNING:tornado.access:400 POST /api/thumbnail (127.0.0.1) 9.10ms
> [!] Error in `/api/thumbnail`: Specified source does not yet have any photometry data.
> WARNING:tornado.access:400 POST /api/thumbnail (127.0.0.1) 9.55ms

**Comment by dannygoldstein** [comment]
@AlexGKim did this get fixed by wiping the DB ?

**Comment by AlexGKim** [comment]
Wiping the DB helped but I am confronted over and over again by "insufficient permission".  It would be great to get a list of all directories that are created and used since as non-root I don't by default have permissions.

**Comment by AlexGKim** [comment]
This is the error as it appears now.

> [05:31:10 flow] Pushing action skyportal/REFRESH_SOURCE to user *
> [05:31:10 flow] Pushing action skyportal/REFRESH_SOURCE to user *
> [05:31:10 flow] Pushing action skyportal/REFRESH_SOURCE to user *
> [05:31:10 flow] Pushing action skyportal/REFRESH_SOURCE to user *
> [05:31:10 flow] Pushing action skyportal/REFRESH_SOURCE to user *
> [05:31:10 flow] Pushing action skyportal/REFRESH_SOURCE to user *
> [05:31:10 flow] Pushing action skyportal/REFRESH_SOURCE to user *
> [05:31:10 flow] Pushing action skyportal/REFRESH_SOURCE to user *
> [!] Error in `/api/thumbnail`: Insufficient permissions.
> WARNING:tornado.access:400 POST /api/thumbnail (127.0.0.1) 18.02ms
> [!] Error in `/api/thumbnail`: Insufficient permissions.
> WARNING:tornado.access:400 POST /api/thumbnail (127.0.0.1) 10.77ms
> [!] Error in `/api/thumbnail`: Insufficient permissions.
> WARNING:tornado.access:400 POST /api/thumbnail (127.0.0.1) 9.99ms
> [!] Error in `/api/thumbnail`: Specified source does not yet have any photometry data.
> WARNING:tornado.access:400 POST /api/thumbnail (127.0.0.1) 12.39ms
> [!] Error in `/api/thumbnail`: Specified source does not yet have any photometry data.
> WARNING:tornado.access:400 POST /api/thumbnail (127.0.0.1) 11.01ms
> [!] Error in `/api/thumbnail`: Specified source does not yet have any photometry data.
> WARNING:tornado.access:400 POST /api/thumbnail (127.0.0.1) 13.20ms
> [!] Error in `/api/thumbnail`: Insufficient permissions.
> WARNING:tornado.access:400 POST /api/thumbnail (127.0.0.1) 9.36ms
> [!] Error in `/api/thumbnail`: Insufficient permissions.
> WARNING:tornado.access:400 POST /api/thumbnail (127.0.0.1) 12.42ms
> [!] Error in `/api/thumbnail`: Insufficient permissions.
> WARNING:tornado.access:400 POST /api/thumbnail (127.0.0.1) 11.82ms
> [!] Error in `/api/thumbnail`: Specified source does not yet have any photometry data.
> WARNING:tornado.access:400 POST /api/thumbnail (127.0.0.1) 10.40ms
> [!] Error in `/api/thumbnail`: Specified source does not yet have any photometry data.
> WARNING:tornado.access:400 POST /api/thumbnail (127.0.0.1) 12.05ms
> [!] Error in `/api/thumbnail`: Specified source does not yet have any photometry data.
> WARNING:tornado.access:400 POST /api/thumbnail (127.0.0.1) 9.34ms
>

**Comment by dannygoldstein** [comment]
Fixed with a DB wipe and rerunning `make load_demo_data`.
