### ISSUE TITLE
All users are being logged in as the same user

### ISSUE THREAD

**Issue by AlexGKim** [skyportal/skyportal#945]
Everyone who signs into SkyPortal with their own credentials are getting logged on as my SkyPortal user.

I am running 

commit c6348bfd869beffd6533f214024e636d4dd52e6d (upstream/master)

@dmitryduev Danny Goldstein tells me that this bug was resolved in a previous version.  The database being used was filled by an early version of SkyPortal.

**Comment by dmitryduev** [comment]
@AlexGKim a similar bug was resolved, what you are describing we haven't actually seen (multiple users log in as one other user); there may be further issues that need our attention. I would recommend changing the secret key in the config, that will invalidate users' cookies and force them to. If possible, I'd also zoink everything and started clean.

**Comment by AlexGKim** [comment]
The problem was occurring for people logging into SkyPortal for the first time.  I started with a new clean database.  Logged in and was prompted to input my personal information.  Then I got a second person to log in for the first time and after google authentication landed on my SkyPortal account.

I did not change the secret key because it takes 30 minutes to 2 hours to do one test cycle.  Is it likely to be the problem?

**Comment by AlexGKim** [comment]
I also changed the secret and the problem persists.

**Comment by dannygoldstein** [comment]
Current theory after a Zoom with @AlexGKim is that this is related to running in debug mode.

**Comment by acrellin** [comment]
@AlexGKim can you confirm that you have set debug_login: False in your config.yaml file?

**Comment by AlexGKim** [comment]
Indeed this problem was resolved in a conversation with @dannygoldstein.  I was running in test mode.  This issue can be closed.
