### ISSUE TITLE
Show PS1 and/or SDSS cutouts directly on source and scanning pages

### ISSUE THREAD

**Issue by cfremling** [skyportal/skyportal#946]
It can be of great help to see SDSS or PS1 to visually check for a host galaxy and/or stellar counterparts.
On the scanning page this could be optional through a checkbox in case there is a general slowdown. However, it is critical that other surveys / catalogs can be easily accessed when scanning even before a source has been saved.

**Comment by dannygoldstein** [comment]
@cfremling I believe @dmitryduev is closing in on a solution here. Should be integrated soon.

Danny
