### ISSUE TITLE
Sorting on scanning page

### ISSUE THREAD

**Issue by cfremling** [skyportal/skyportal#947]
I would like to request the ability to sort the scanning page, based on computations made by the filters. For example, if we compute an age based on the first historical detection, it would be great if we could sort the entire scanning page to put young/new canididates first.

**Comment by AndyTza** [comment]
I also think it would be particularly useful when the user selects the parameter they want to sort by for it to be displayed right next to the cutout images (i.e see image below)

<img width="1434" alt="Screen Shot 2020-09-25 at 12 22 15 PM" src="https://user-images.githubusercontent.com/22720676/94291811-14268700-ff2a-11ea-8914-e35b2e160eba.png">

**Comment by stefanv** [comment]
Related: https://github.com/skyportal/skyportal/issues/961

**Comment by dannygoldstein** [comment]
@cfremling @AndyTza: Update, we have a good model for this now, @guynir42  is leading up the backend development (PR should be in today) and @kmshin1397 is going to be implementing this on the frontend.

**Comment by dannygoldstein** [comment]
Fixed by #1068
