### ISSUE TITLE
Query for new photometry and spectra

### ISSUE THREAD

**Issue by cfremling** [skyportal/skyportal#949]
We need a way to query for data from specific telescopes. For example, to see all sources that have been observed within a certain time interval and to list the observations (photometry or spectra) that were obtained. e.g., recent photometry from LCO-1m, LCO-2m, recent spectra from P200/DBSP, Keck/LRIS

**Comment by acrellin** [comment]
Addressed by #997

**Comment by dannygoldstein** [comment]
Closed by #1507
