### ISSUE TITLE
ra/dec strings in comments are attempted to be rendered as emojis

### ISSUE THREAD

**Issue by dmitryduev** [skyportal/skyportal#957]
E.g.:
![image](https://user-images.githubusercontent.com/7557205/93705441-322b5c00-fad2-11ea-996f-256677e77073.png)

A simple solution would be to ignore comments posted by provisioned_admin.

**Comment by mcoughlin** [comment]
@kmshin1397 What do you think of something like:
const emojiSupport = (text) => {
    text.value.replace(/:\w+:/gi,
                       emoji.getUnicode(name).includes("undefined") ? name : (name) => emoji.getUnicode(name));
I can't quite make it work, but I think that's simply my lack of java skillz. But some kind of tertiary operator to do the check?

**Comment by dmitryduev** [comment]
up
