### ISSUE TITLE
Render plot sizes correctly on mobile (responsive scaling)

### ISSUE THREAD

**Issue by stefanv** [skyportal/skyportal#96]
https://stackoverflow.com/questions/46526446/how-to-configure-bokeh-plot-to-have-responsive-width-and-fixed-height

**Comment by stefanv** [comment]
This should be easier once https://github.com/skyportal/skyportal/issues/82 is completed.  https://github.com/skyportal/skyportal/pull/307 makes an initial attempt.

**Comment by acrellin** [comment]
Addressed in https://github.com/skyportal/skyportal/pull/1595
