### ISSUE TITLE
Querying metadata associated with obj's

### ISSUE THREAD

**Issue by dmitryduev** [skyportal/skyportal#961]
We need the ability to query obj by metadata stored in either comments or alt_data. 

We need to explore this in detail.

- Allow storing collections in comments and not just strings?
- Use alt_data to store structured (meta)data, e.g. auto-annotations? In this case, it needs to be exposed on a number of pages.
- Ability to query and filter obj's based on the metadata. Use something like `https://github.com/kapouille/mongoquery`? Or query postgres' jsonb fields directly?

**Comment by profjsb** [comment]
The good news is that the query engine on JSONB is JSONPATH (like XPATH) and is fully implemented in PG12:
https://www.postgresql.org/docs/12/functions-json.html#FUNCTIONS-SQLJSON-PATH

**Comment by dannygoldstein** [comment]
Right now autoannotations are implemented as comments. But autoannotations, unlike comments, need to be searchable, filterable, sortable, and storable as not just plain text but also as floating points and integers. 

I'd advocate for developing a separate `Annotation` model that encapsulates these notions, with the main column storing JSONB @profjsb and @dmitryduev suggest.

**Comment by guynir42** [comment]
I am now working on this, and wanted to know if right now we are generating any auto-annotations and where in the code they are generated? Thanks!

**Comment by dannygoldstein** [comment]
Fixed by #979 and #1068
