### ISSUE TITLE
Confusing navigation after saving source

### ISSUE THREAD

**Issue by stefanv** [skyportal/skyportal#974]
When saving a candidate, users sometimes click the ID to navigate to the new source.  The dark blue button ("previously saved") takes you to the source instead.

We should make it clear in the UI which is the source and which is the candidate page.

(Issue observed that "source does not allow comments", but is because candidate does not allow comments.)

**Comment by dannygoldstein** [comment]
Closing as we are going to move away from candidate pages - and just have a single `Obj` page for both sources and candidates.
