### ISSUE TITLE
Requested feature: more compact comments

### ISSUE THREAD

**Issue by stefanv** [skyportal/skyportal#976]

**Comment by scizen9** [comment]
Here are some screenshots of the growth marshal showing a target with lots of comments.  Top  shows header and auto annotations and bottom shows how comments are entered.  This also illustrates the utility of comments for supporting a conversation about the object where people work out followup strategies.

![image](https://user-images.githubusercontent.com/6845428/115593852-e28c5900-a289-11eb-9161-e22d9e918727.png)
![image](https://user-images.githubusercontent.com/6845428/115593905-f637bf80-a289-11eb-939f-d5962cfca0f5.png)

**Comment by joelachance** [comment]
Ok, I haven't added the date as shown above, but wasn't sure if we wanted it as I thought it might clutter things a bit. Let me know thoughts! Red 'X' on hover. The trash can doesn't play quite as nice with more compacted heights.

<img width="524" alt="Screen Shot 2021-05-02 at 11 40 10 PM" src="https://user-images.githubusercontent.com/3891660/116841846-0ad85980-aba0-11eb-989e-71e2615b91bf.png">

**Comment by dmitryduev** [comment]
This is reeeally nice @joelachance, thank you! My one comment is: I would make this a user preference and add a toggle to user Profile.

**Comment by joelachance** [comment]
I agree @dmitryduev, I'd like that as a user preference too. I was looking last night, and after they get dispatched to Redux they get posted to postgres. Can we add anything to user preferences without adding a db column?

**Comment by joelachance** [comment]
Also, I'm noticing when I attempt to commit, the pre-commit hook runs, passes, and then the commit never ends up in git log. Has anyone seen this before?

**Comment by stefanv** [comment]
> I agree @dmitryduev, I'd like that as a user preference too. I was looking last night, and after they get dispatched to Redux they get posted to postgres. Can we add anything to user preferences without adding a db column?

Preferences are stored as JSONB, so no new column would be necessary.

**Comment by stefanv** [comment]
> Also, I'm noticing when I attempt to commit, the pre-commit hook runs, passes, and then the commit never ends up in git log. Has anyone seen this before?

Weird, no, I've never seen that.  The only time a commit shouldn't be added is if something in the pre-commit hook failed.  Maybe try and upgrade `pre-commit` itself?

**Comment by joelachance** [comment]
Ok, here's an update, let me know what everyone thinks! The 'i' is a hover tooltip, where you'll see the time stamp.

<img width="451" alt="Screen Shot 2021-05-17 at 10 46 18 PM" src="https://user-images.githubusercontent.com/3891660/118587213-d51b9f00-b761-11eb-9cd4-a5c00cfd5bc2.png">


@stefanv, agreed, strange. I did re-install pre-commit with no luck. I'm using skyportal env, I may re-install and see if that does the trick. Right now the pre-commit will run, but in order to commit anything you have to use `--no-verify`, which isn't great.

**Comment by joelachance** [comment]
Also, +1 to removing the bubble if everyone is on board, I'm not sure it's necessary in compact or regular view.

**Comment by stefanv** [comment]
Looks nice, Joe!  I wonder if the `x` should only appear when the message is hovered over?

**Comment by joelachance** [comment]
Sure, how's this? The first screenshot is the hover state on the x. I also swapped the MUI info icon, I think I like this one a bit better.
<img width="439" alt="Screen Shot 2021-05-18 at 10 26 44 PM" src="https://user-images.githubusercontent.com/3891660/118752179-3b6af500-b828-11eb-8a93-b7eb1cf29d03.png">
<img width="441" alt="Screen Shot 2021-05-18 at 10 26 34 PM" src="https://user-images.githubusercontent.com/3891660/118752181-3c038b80-b828-11eb-9db3-ff1eda10c18c.png">

**Comment by stefanv** [comment]
Nice, thank you!
