### ISSUE TITLE
Provide a mechanism to set the superuser

### ISSUE THREAD

**Issue by stefanv** [skyportal/skyportal#98]
Recommended in #54: set the first user to log in as the superuser.

**Comment by acrellin** [comment]
Is this still something we want in addition to https://github.com/skyportal/skyportal/pull/91 ?

**Comment by stefanv** [comment]
Reviewing #91's `skyportal/initial_setup.py`, it looks like that script can be renamed to `tools/adduser.py`, with the `--nodrop` flag changed to `--drop` (False by default).  Then, this should be added to the documentation and also tested.

**Comment by dannygoldstein** [comment]
@stefanv Is this still open?

**Comment by stefanv** [comment]
I think this will be resolved with a docs update, and showing how to ingest the first user via the data loader.

**Comment by dmitryduev** [comment]
@stefanv should we close this?

**Comment by stefanv** [comment]
The documentation shows how to use `make_super_user` for this task.  The docs also mention `become_user` in several places.
