### ISSUE TITLE
Show/Add Program for Each Assigned Source on Observing Runs Page 

### ISSUE THREAD

**Issue by AndyTza** [skyportal/skyportal#980]
- When assigning a source to an observing run night, would it be possible to add which program you're adding it under? This would be particularly useful for sources that are in overlapping programs (i.e CLU and RCF). 

- I think it would be very useful for those who are using the Observing Runs page to see for each candidate what program was the source assigned under (i.e CLU, RCF, and other).

**Comment by dannygoldstein** [comment]
Thanks @AndyTza , this is on our list.
