### ISSUE TITLE
Add Airmass Plot to Observing Runs Page Preview

### ISSUE THREAD

**Issue by AndyTza** [skyportal/skyportal#981]
It would be very useful in Observing Runs Page have under each assigned candidate the airmass plot previewed right next to/or under the target name (instead of actually clicking the arrow). Sometimes when observing, it comes in handy to scan all the airmass plots of the assigned candidates -- this feature would benefit those who are making observing schedules.

**Comment by dannygoldstein** [comment]
Doing this by default will add too much overhead to the page load. We want to keep things loading fast.

If you want to see all the airmass plots, you can load everything  by clicking this arrow: 

<img width="1296" alt="Screen Shot 2020-09-25 at 10 45 42 AM" src="https://user-images.githubusercontent.com/2769632/94299309-5779f900-ff1c-11ea-8d97-0c79983b5789.png">

**Comment by dannygoldstein** [comment]
@AndyTza Note also that you can sort targets by rise time and set time
