### ISSUE TITLE
PS1 cutouts

### ISSUE THREAD

**Issue by dmitryduev** [skyportal/skyportal#998]
Here's code from Mickael Rigault's [ztfquery](https://github.com/MickaelRigault/ztfquery/blob/master/ztfquery/utils/stamps.py) for getting the url for a PS1 cutout with a single GET call: https://gist.github.com/dmitryduev/77ae51ac0fd159c0211244a16133e510

A single query typically takes ~0.8s, but may take longer and I am not sure how far we can go in terms of running multiple queries like that simultaneously without being banned. For this reason (+ the calls would be blocking using the current setup, or significant refactoring would be necessary) I am a bit reluctant to make these calls on the K side before posting to SP in F.

So this is an invitation to think about how to do it on the SP side. Add an option to grab and save the PS1 cutout to `/api/thumbnail.POST`? Create something like "external/standard" thumbnails upon saving a source? @dannygoldstein @profjsb @kmshin1397 thoughts?

**Comment by acrellin** [comment]
Closing as already addressed. In the current implementation, the PS1 cutout URL is generated upon initial source page load, and persisted thereafter.
